// Code generated by goctl. DO NOT EDIT!

package trademodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
)

// avoid unused err
var _ = time.Second

type (
	cpmmFeeTierModel interface {
		Insert(ctx context.Context, data *CpmmFeeTier) error

		FindOne(ctx context.Context, id int64) (*CpmmFeeTier, error)
		Update(ctx context.Context, data *CpmmFeeTier) error

		Delete(ctx context.Context, id int64) error
	}

	defaultCpmmFeeTierModel struct {
		conn  *gorm.DB
		table string
	}

	CpmmFeeTier struct {
		Id             int64     `gorm:"column:id"`
		PoolType       string    `gorm:"column:pool_type"`
		ProgramAddress string    `gorm:"column:program_address"`
		ValueBps       int64     `gorm:"column:value_bps"`
		Label          string    `gorm:"column:label"`
		Description    string    `gorm:"column:description"`
		TickSpacing    int64     `gorm:"column:tick_spacing"`
		ConfigIndex    int64     `gorm:"column:config_index"`
		Address        string    `gorm:"column:address"`
		PriorityOrder  int64     `gorm:"column:priority_order"`
		Version        string    `gorm:"column:version"`
		UpdatedAt      time.Time `gorm:"column:updated_at"`
		CreatedAt      time.Time `gorm:"column:created_at"`
	}
)

var QCpmmFeeTier CpmmFeeTier

func init() {
	InitField(&QCpmmFeeTier)
}

func (CpmmFeeTier) TableName() string {
	return strings.Trim("`cpmm_fee_tiers`", "`")
}

func newCpmmFeeTierModel(conn *gorm.DB) *defaultCpmmFeeTierModel {
	return &defaultCpmmFeeTierModel{
		conn:  conn,
		table: strings.Trim("`cpmm_fee_tiers`", "`"),
	}
}

func (m *defaultCpmmFeeTierModel) Insert(ctx context.Context, data *CpmmFeeTier) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultCpmmFeeTierModel) FindOne(ctx context.Context, id int64) (*CpmmFeeTier, error) {
	var resp CpmmFeeTier
	err := m.conn.WithContext(ctx).Model(&CpmmFeeTier{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err

}

func (m *defaultCpmmFeeTierModel) Update(ctx context.Context, data *CpmmFeeTier) error {
	db := m.conn
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultCpmmFeeTierModel) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Where("`id` = @id", sql.Named("id", id)).Delete(&CpmmFeeTier{}).Error

	return err
}
