// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: market.proto

package marketclient

import (
	"context"

	"richcode.cc/dex/market/market"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ClmmPoolItem                 = market.ClmmPoolItem
	DepthDataPoint               = market.DepthDataPoint
	GetClmmPoolDepthDataRequest  = market.GetClmmPoolDepthDataRequest
	GetClmmPoolDepthDataResponse = market.GetClmmPoolDepthDataResponse
	GetClmmPoolListRequest       = market.GetClmmPoolListRequest
	GetClmmPoolListResponse      = market.GetClmmPoolListResponse
	GetNativeTokenPriceRequest   = market.GetNativeTokenPriceRequest
	GetNativeTokenPriceResponse  = market.GetNativeTokenPriceResponse
	GetPairInfoByTokenRequest    = market.GetPairInfoByTokenRequest
	GetPairInfoByTokenResponse   = market.GetPairInfoByTokenResponse
	GetPoolDetailRequest         = market.GetPoolDetailRequest
	GetPoolDetailResponse        = market.GetPoolDetailResponse
	GetPumpTokenListRequest      = market.GetPumpTokenListRequest
	GetPumpTokenListResponse     = market.GetPumpTokenListResponse
	GetTokenInfoRequest          = market.GetTokenInfoRequest
	GetTokenInfoResponse         = market.GetTokenInfoResponse
	GetUserPositionsRequest      = market.GetUserPositionsRequest
	GetUserPositionsResponse     = market.GetUserPositionsResponse
	PositionItem                 = market.PositionItem
	PumpTokenItem                = market.PumpTokenItem
	PushTokenInfoRequest         = market.PushTokenInfoRequest
	PushTokenInfoResponse        = market.PushTokenInfoResponse
	QuoteClmmRequest             = market.QuoteClmmRequest
	QuoteClmmResponse            = market.QuoteClmmResponse
	QuoteCpmmRequest             = market.QuoteCpmmRequest
	QuoteCpmmResponse            = market.QuoteCpmmResponse

	Market interface {
		GetPumpTokenList(ctx context.Context, in *GetPumpTokenListRequest, opts ...grpc.CallOption) (*GetPumpTokenListResponse, error)
		GetClmmPoolList(ctx context.Context, in *GetClmmPoolListRequest, opts ...grpc.CallOption) (*GetClmmPoolListResponse, error)
		GetPoolDetail(ctx context.Context, in *GetPoolDetailRequest, opts ...grpc.CallOption) (*GetPoolDetailResponse, error)
		PushTokenInfo(ctx context.Context, in *PushTokenInfoRequest, opts ...grpc.CallOption) (*PushTokenInfoResponse, error)
		GetPairInfoByToken(ctx context.Context, in *GetPairInfoByTokenRequest, opts ...grpc.CallOption) (*GetPairInfoByTokenResponse, error)
		GetNativeTokenPrice(ctx context.Context, in *GetNativeTokenPriceRequest, opts ...grpc.CallOption) (*GetNativeTokenPriceResponse, error)
		GetTokenInfo(ctx context.Context, in *GetTokenInfoRequest, opts ...grpc.CallOption) (*GetTokenInfoResponse, error)
		QuoteCpmm(ctx context.Context, in *QuoteCpmmRequest, opts ...grpc.CallOption) (*QuoteCpmmResponse, error)
		QuoteClmm(ctx context.Context, in *QuoteClmmRequest, opts ...grpc.CallOption) (*QuoteClmmResponse, error)
		GetClmmPoolDepthData(ctx context.Context, in *GetClmmPoolDepthDataRequest, opts ...grpc.CallOption) (*GetClmmPoolDepthDataResponse, error)
		// Get user's liquidity positions
		GetUserPositions(ctx context.Context, in *GetUserPositionsRequest, opts ...grpc.CallOption) (*GetUserPositionsResponse, error)
	}

	defaultMarket struct {
		cli zrpc.Client
	}
)

func NewMarket(cli zrpc.Client) Market {
	return &defaultMarket{
		cli: cli,
	}
}

func (m *defaultMarket) GetPumpTokenList(ctx context.Context, in *GetPumpTokenListRequest, opts ...grpc.CallOption) (*GetPumpTokenListResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetPumpTokenList(ctx, in, opts...)
}

func (m *defaultMarket) GetClmmPoolList(ctx context.Context, in *GetClmmPoolListRequest, opts ...grpc.CallOption) (*GetClmmPoolListResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetClmmPoolList(ctx, in, opts...)
}

func (m *defaultMarket) GetPoolDetail(ctx context.Context, in *GetPoolDetailRequest, opts ...grpc.CallOption) (*GetPoolDetailResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetPoolDetail(ctx, in, opts...)
}

func (m *defaultMarket) PushTokenInfo(ctx context.Context, in *PushTokenInfoRequest, opts ...grpc.CallOption) (*PushTokenInfoResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.PushTokenInfo(ctx, in, opts...)
}

func (m *defaultMarket) GetPairInfoByToken(ctx context.Context, in *GetPairInfoByTokenRequest, opts ...grpc.CallOption) (*GetPairInfoByTokenResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetPairInfoByToken(ctx, in, opts...)
}

func (m *defaultMarket) GetNativeTokenPrice(ctx context.Context, in *GetNativeTokenPriceRequest, opts ...grpc.CallOption) (*GetNativeTokenPriceResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetNativeTokenPrice(ctx, in, opts...)
}

func (m *defaultMarket) GetTokenInfo(ctx context.Context, in *GetTokenInfoRequest, opts ...grpc.CallOption) (*GetTokenInfoResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetTokenInfo(ctx, in, opts...)
}

func (m *defaultMarket) QuoteCpmm(ctx context.Context, in *QuoteCpmmRequest, opts ...grpc.CallOption) (*QuoteCpmmResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.QuoteCpmm(ctx, in, opts...)
}

func (m *defaultMarket) QuoteClmm(ctx context.Context, in *QuoteClmmRequest, opts ...grpc.CallOption) (*QuoteClmmResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.QuoteClmm(ctx, in, opts...)
}

func (m *defaultMarket) GetClmmPoolDepthData(ctx context.Context, in *GetClmmPoolDepthDataRequest, opts ...grpc.CallOption) (*GetClmmPoolDepthDataResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetClmmPoolDepthData(ctx, in, opts...)
}

// Get user's liquidity positions
func (m *defaultMarket) GetUserPositions(ctx context.Context, in *GetUserPositionsRequest, opts ...grpc.CallOption) (*GetUserPositionsResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetUserPositions(ctx, in, opts...)
}
