// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: market.proto

package marketclient

import (
	"context"

	"richcode.cc/dex/market/market"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ClmmPoolItem                = market.ClmmPoolItem
	GetClmmPoolListRequest      = market.GetClmmPoolListRequest
	GetClmmPoolListResponse     = market.GetClmmPoolListResponse
	GetNativeTokenPriceRequest  = market.GetNativeTokenPriceRequest
	GetNativeTokenPriceResponse = market.GetNativeTokenPriceResponse
	GetPairInfoByTokenRequest   = market.GetPairInfoByTokenRequest
	GetPairInfoByTokenResponse  = market.GetPairInfoByTokenResponse
	GetPumpTokenListRequest     = market.GetPumpTokenListRequest
	GetPumpTokenListResponse    = market.GetPumpTokenListResponse
	GetTokenInfoRequest         = market.GetTokenInfoRequest
	GetTokenInfoResponse        = market.GetTokenInfoResponse
	PumpTokenItem               = market.PumpTokenItem
	PushTokenInfoRequest        = market.PushTokenInfoRequest
	PushTokenInfoResponse       = market.PushTokenInfoResponse

	Market interface {
		GetPumpTokenList(ctx context.Context, in *GetPumpTokenListRequest, opts ...grpc.CallOption) (*GetPumpTokenListResponse, error)
		GetClmmPoolList(ctx context.Context, in *GetClmmPoolListRequest, opts ...grpc.CallOption) (*GetClmmPoolListResponse, error)
		PushTokenInfo(ctx context.Context, in *PushTokenInfoRequest, opts ...grpc.CallOption) (*PushTokenInfoResponse, error)
		GetPairInfoByToken(ctx context.Context, in *GetPairInfoByTokenRequest, opts ...grpc.CallOption) (*GetPairInfoByTokenResponse, error)
		GetNativeTokenPrice(ctx context.Context, in *GetNativeTokenPriceRequest, opts ...grpc.CallOption) (*GetNativeTokenPriceResponse, error)
		GetTokenInfo(ctx context.Context, in *GetTokenInfoRequest, opts ...grpc.CallOption) (*GetTokenInfoResponse, error)
	}

	defaultMarket struct {
		cli zrpc.Client
	}
)

func NewMarket(cli zrpc.Client) Market {
	return &defaultMarket{
		cli: cli,
	}
}

func (m *defaultMarket) GetPumpTokenList(ctx context.Context, in *GetPumpTokenListRequest, opts ...grpc.CallOption) (*GetPumpTokenListResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetPumpTokenList(ctx, in, opts...)
}

func (m *defaultMarket) GetClmmPoolList(ctx context.Context, in *GetClmmPoolListRequest, opts ...grpc.CallOption) (*GetClmmPoolListResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetClmmPoolList(ctx, in, opts...)
}

func (m *defaultMarket) PushTokenInfo(ctx context.Context, in *PushTokenInfoRequest, opts ...grpc.CallOption) (*PushTokenInfoResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.PushTokenInfo(ctx, in, opts...)
}

func (m *defaultMarket) GetPairInfoByToken(ctx context.Context, in *GetPairInfoByTokenRequest, opts ...grpc.CallOption) (*GetPairInfoByTokenResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetPairInfoByToken(ctx, in, opts...)
}

func (m *defaultMarket) GetNativeTokenPrice(ctx context.Context, in *GetNativeTokenPriceRequest, opts ...grpc.CallOption) (*GetNativeTokenPriceResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetNativeTokenPrice(ctx, in, opts...)
}

func (m *defaultMarket) GetTokenInfo(ctx context.Context, in *GetTokenInfoRequest, opts ...grpc.CallOption) (*GetTokenInfoResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetTokenInfo(ctx, in, opts...)
}
