// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: market.proto

package marketclient

import (
	"context"

	"richcode.cc/dex/market/market"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ClmmPoolItem                 = market.ClmmPoolItem
	DepthDataPoint               = market.DepthDataPoint
	GetClmmPoolDepthDataRequest  = market.GetClmmPoolDepthDataRequest
	GetClmmPoolDepthDataResponse = market.GetClmmPoolDepthDataResponse
	GetClmmPoolListRequest       = market.GetClmmPoolListRequest
	GetClmmPoolListResponse      = market.GetClmmPoolListResponse
	GetLimitOrderBookRequest     = market.GetLimitOrderBookRequest
	GetLimitOrderBookResponse    = market.GetLimitOrderBookResponse
	GetLimitOrderDetailRequest   = market.GetLimitOrderDetailRequest
	GetLimitOrderDetailResponse  = market.GetLimitOrderDetailResponse
	GetLimitOrderFillsRequest    = market.GetLimitOrderFillsRequest
	GetLimitOrderFillsResponse   = market.GetLimitOrderFillsResponse
	GetLimitOrderMarketsRequest  = market.GetLimitOrderMarketsRequest
	GetLimitOrderMarketsResponse = market.GetLimitOrderMarketsResponse
	GetNativeTokenPriceRequest   = market.GetNativeTokenPriceRequest
	GetNativeTokenPriceResponse  = market.GetNativeTokenPriceResponse
	GetPairInfoByTokenRequest    = market.GetPairInfoByTokenRequest
	GetPairInfoByTokenResponse   = market.GetPairInfoByTokenResponse
	GetPoolDetailRequest         = market.GetPoolDetailRequest
	GetPoolDetailResponse        = market.GetPoolDetailResponse
	GetPumpTokenListRequest      = market.GetPumpTokenListRequest
	GetPumpTokenListResponse     = market.GetPumpTokenListResponse
	GetTokenInfoRequest          = market.GetTokenInfoRequest
	GetTokenInfoResponse         = market.GetTokenInfoResponse
	GetUserLimitOrdersRequest    = market.GetUserLimitOrdersRequest
	GetUserLimitOrdersResponse   = market.GetUserLimitOrdersResponse
	GetUserMarginRequest         = market.GetUserMarginRequest
	GetUserMarginResponse        = market.GetUserMarginResponse
	GetUserPositionsRequest      = market.GetUserPositionsRequest
	GetUserPositionsResponse     = market.GetUserPositionsResponse
	MarginAccountItem            = market.MarginAccountItem
	MarketItem                   = market.MarketItem
	OrderBookLevel               = market.OrderBookLevel
	OrderDetailItem              = market.OrderDetailItem
	OrderFillItem                = market.OrderFillItem
	PositionItem                 = market.PositionItem
	PumpTokenItem                = market.PumpTokenItem
	PushTokenInfoRequest         = market.PushTokenInfoRequest
	PushTokenInfoResponse        = market.PushTokenInfoResponse
	QuoteClmmRequest             = market.QuoteClmmRequest
	QuoteClmmResponse            = market.QuoteClmmResponse
	QuoteCpmmRequest             = market.QuoteCpmmRequest
	QuoteCpmmResponse            = market.QuoteCpmmResponse
	SyncMarginBalanceRequest     = market.SyncMarginBalanceRequest
	SyncMarginBalanceResponse    = market.SyncMarginBalanceResponse
	UserOrderItem                = market.UserOrderItem

	Market interface {
		GetPumpTokenList(ctx context.Context, in *GetPumpTokenListRequest, opts ...grpc.CallOption) (*GetPumpTokenListResponse, error)
		GetClmmPoolList(ctx context.Context, in *GetClmmPoolListRequest, opts ...grpc.CallOption) (*GetClmmPoolListResponse, error)
		GetPoolDetail(ctx context.Context, in *GetPoolDetailRequest, opts ...grpc.CallOption) (*GetPoolDetailResponse, error)
		PushTokenInfo(ctx context.Context, in *PushTokenInfoRequest, opts ...grpc.CallOption) (*PushTokenInfoResponse, error)
		GetPairInfoByToken(ctx context.Context, in *GetPairInfoByTokenRequest, opts ...grpc.CallOption) (*GetPairInfoByTokenResponse, error)
		GetNativeTokenPrice(ctx context.Context, in *GetNativeTokenPriceRequest, opts ...grpc.CallOption) (*GetNativeTokenPriceResponse, error)
		GetTokenInfo(ctx context.Context, in *GetTokenInfoRequest, opts ...grpc.CallOption) (*GetTokenInfoResponse, error)
		QuoteCpmm(ctx context.Context, in *QuoteCpmmRequest, opts ...grpc.CallOption) (*QuoteCpmmResponse, error)
		QuoteClmm(ctx context.Context, in *QuoteClmmRequest, opts ...grpc.CallOption) (*QuoteClmmResponse, error)
		GetClmmPoolDepthData(ctx context.Context, in *GetClmmPoolDepthDataRequest, opts ...grpc.CallOption) (*GetClmmPoolDepthDataResponse, error)
		// Get user's liquidity positions
		GetUserPositions(ctx context.Context, in *GetUserPositionsRequest, opts ...grpc.CallOption) (*GetUserPositionsResponse, error)
		// Limit order queries
		GetLimitOrderBook(ctx context.Context, in *GetLimitOrderBookRequest, opts ...grpc.CallOption) (*GetLimitOrderBookResponse, error)
		GetUserLimitOrders(ctx context.Context, in *GetUserLimitOrdersRequest, opts ...grpc.CallOption) (*GetUserLimitOrdersResponse, error)
		GetLimitOrderDetail(ctx context.Context, in *GetLimitOrderDetailRequest, opts ...grpc.CallOption) (*GetLimitOrderDetailResponse, error)
		GetLimitOrderMarkets(ctx context.Context, in *GetLimitOrderMarketsRequest, opts ...grpc.CallOption) (*GetLimitOrderMarketsResponse, error)
		GetUserMargin(ctx context.Context, in *GetUserMarginRequest, opts ...grpc.CallOption) (*GetUserMarginResponse, error)
		// Sync margin account balance from blockchain
		SyncMarginBalance(ctx context.Context, in *SyncMarginBalanceRequest, opts ...grpc.CallOption) (*SyncMarginBalanceResponse, error)
		GetLimitOrderFills(ctx context.Context, in *GetLimitOrderFillsRequest, opts ...grpc.CallOption) (*GetLimitOrderFillsResponse, error)
	}

	defaultMarket struct {
		cli zrpc.Client
	}
)

func NewMarket(cli zrpc.Client) Market {
	return &defaultMarket{
		cli: cli,
	}
}

func (m *defaultMarket) GetPumpTokenList(ctx context.Context, in *GetPumpTokenListRequest, opts ...grpc.CallOption) (*GetPumpTokenListResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetPumpTokenList(ctx, in, opts...)
}

func (m *defaultMarket) GetClmmPoolList(ctx context.Context, in *GetClmmPoolListRequest, opts ...grpc.CallOption) (*GetClmmPoolListResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetClmmPoolList(ctx, in, opts...)
}

func (m *defaultMarket) GetPoolDetail(ctx context.Context, in *GetPoolDetailRequest, opts ...grpc.CallOption) (*GetPoolDetailResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetPoolDetail(ctx, in, opts...)
}

func (m *defaultMarket) PushTokenInfo(ctx context.Context, in *PushTokenInfoRequest, opts ...grpc.CallOption) (*PushTokenInfoResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.PushTokenInfo(ctx, in, opts...)
}

func (m *defaultMarket) GetPairInfoByToken(ctx context.Context, in *GetPairInfoByTokenRequest, opts ...grpc.CallOption) (*GetPairInfoByTokenResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetPairInfoByToken(ctx, in, opts...)
}

func (m *defaultMarket) GetNativeTokenPrice(ctx context.Context, in *GetNativeTokenPriceRequest, opts ...grpc.CallOption) (*GetNativeTokenPriceResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetNativeTokenPrice(ctx, in, opts...)
}

func (m *defaultMarket) GetTokenInfo(ctx context.Context, in *GetTokenInfoRequest, opts ...grpc.CallOption) (*GetTokenInfoResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetTokenInfo(ctx, in, opts...)
}

func (m *defaultMarket) QuoteCpmm(ctx context.Context, in *QuoteCpmmRequest, opts ...grpc.CallOption) (*QuoteCpmmResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.QuoteCpmm(ctx, in, opts...)
}

func (m *defaultMarket) QuoteClmm(ctx context.Context, in *QuoteClmmRequest, opts ...grpc.CallOption) (*QuoteClmmResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.QuoteClmm(ctx, in, opts...)
}

func (m *defaultMarket) GetClmmPoolDepthData(ctx context.Context, in *GetClmmPoolDepthDataRequest, opts ...grpc.CallOption) (*GetClmmPoolDepthDataResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetClmmPoolDepthData(ctx, in, opts...)
}

// Get user's liquidity positions
func (m *defaultMarket) GetUserPositions(ctx context.Context, in *GetUserPositionsRequest, opts ...grpc.CallOption) (*GetUserPositionsResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetUserPositions(ctx, in, opts...)
}

// Limit order queries
func (m *defaultMarket) GetLimitOrderBook(ctx context.Context, in *GetLimitOrderBookRequest, opts ...grpc.CallOption) (*GetLimitOrderBookResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetLimitOrderBook(ctx, in, opts...)
}

func (m *defaultMarket) GetUserLimitOrders(ctx context.Context, in *GetUserLimitOrdersRequest, opts ...grpc.CallOption) (*GetUserLimitOrdersResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetUserLimitOrders(ctx, in, opts...)
}

func (m *defaultMarket) GetLimitOrderDetail(ctx context.Context, in *GetLimitOrderDetailRequest, opts ...grpc.CallOption) (*GetLimitOrderDetailResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetLimitOrderDetail(ctx, in, opts...)
}

func (m *defaultMarket) GetLimitOrderMarkets(ctx context.Context, in *GetLimitOrderMarketsRequest, opts ...grpc.CallOption) (*GetLimitOrderMarketsResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetLimitOrderMarkets(ctx, in, opts...)
}

func (m *defaultMarket) GetUserMargin(ctx context.Context, in *GetUserMarginRequest, opts ...grpc.CallOption) (*GetUserMarginResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetUserMargin(ctx, in, opts...)
}

// Sync margin account balance from blockchain
func (m *defaultMarket) SyncMarginBalance(ctx context.Context, in *SyncMarginBalanceRequest, opts ...grpc.CallOption) (*SyncMarginBalanceResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.SyncMarginBalance(ctx, in, opts...)
}

func (m *defaultMarket) GetLimitOrderFills(ctx context.Context, in *GetLimitOrderFillsRequest, opts ...grpc.CallOption) (*GetLimitOrderFillsResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetLimitOrderFills(ctx, in, opts...)
}
