// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: market.proto

package server

import (
	"context"

	"richcode.cc/dex/market/internal/logic"
	"richcode.cc/dex/market/internal/svc"
	"richcode.cc/dex/market/market"
)

type MarketServer struct {
	svcCtx *svc.ServiceContext
	market.UnimplementedMarketServer
}

func NewMarketServer(svcCtx *svc.ServiceContext) *MarketServer {
	return &MarketServer{
		svcCtx: svcCtx,
	}
}

func (s *MarketServer) GetPumpTokenList(ctx context.Context, in *market.GetPumpTokenListRequest) (*market.GetPumpTokenListResponse, error) {
	l := logic.NewGetPumpTokenListLogic(ctx, s.svcCtx)
	return l.GetPumpTokenList(in)
}

func (s *MarketServer) GetClmmPoolList(ctx context.Context, in *market.GetClmmPoolListRequest) (*market.GetClmmPoolListResponse, error) {
	l := logic.NewGetClmmPoolListLogic(ctx, s.svcCtx)
	return l.GetClmmPoolList(in)
}

func (s *MarketServer) PushTokenInfo(ctx context.Context, in *market.PushTokenInfoRequest) (*market.PushTokenInfoResponse, error) {
	l := logic.NewPushTokenInfoLogic(ctx, s.svcCtx)
	return l.PushTokenInfo(in)
}

func (s *MarketServer) GetPairInfoByToken(ctx context.Context, in *market.GetPairInfoByTokenRequest) (*market.GetPairInfoByTokenResponse, error) {
	l := logic.NewGetPairInfoByTokenLogic(ctx, s.svcCtx)
	return l.GetPairInfoByToken(in)
}

func (s *MarketServer) GetNativeTokenPrice(ctx context.Context, in *market.GetNativeTokenPriceRequest) (*market.GetNativeTokenPriceResponse, error) {
	l := logic.NewGetNativeTokenPriceLogic(ctx, s.svcCtx)
	return l.GetNativeTokenPrice(in)
}

func (s *MarketServer) GetTokenInfo(ctx context.Context, in *market.GetTokenInfoRequest) (*market.GetTokenInfoResponse, error) {
	l := logic.NewGetTokenInfoLogic(ctx, s.svcCtx)
	return l.GetTokenInfo(in)
}
