// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: market.proto

package server

import (
	"context"

	"richcode.cc/dex/market/internal/logic"
	"richcode.cc/dex/market/internal/svc"
	"richcode.cc/dex/market/market"
)

type MarketServer struct {
	svcCtx *svc.ServiceContext
	market.UnimplementedMarketServer
}

func NewMarketServer(svcCtx *svc.ServiceContext) *MarketServer {
	return &MarketServer{
		svcCtx: svcCtx,
	}
}

func (s *MarketServer) GetPumpTokenList(ctx context.Context, in *market.GetPumpTokenListRequest) (*market.GetPumpTokenListResponse, error) {
	l := logic.NewGetPumpTokenListLogic(ctx, s.svcCtx)
	return l.GetPumpTokenList(in)
}

func (s *MarketServer) GetClmmPoolList(ctx context.Context, in *market.GetClmmPoolListRequest) (*market.GetClmmPoolListResponse, error) {
	l := logic.NewGetClmmPoolListLogic(ctx, s.svcCtx)
	return l.GetClmmPoolList(in)
}

func (s *MarketServer) GetPoolDetail(ctx context.Context, in *market.GetPoolDetailRequest) (*market.GetPoolDetailResponse, error) {
	l := logic.NewGetPoolDetailLogic(ctx, s.svcCtx)
	return l.GetPoolDetail(in)
}

func (s *MarketServer) PushTokenInfo(ctx context.Context, in *market.PushTokenInfoRequest) (*market.PushTokenInfoResponse, error) {
	l := logic.NewPushTokenInfoLogic(ctx, s.svcCtx)
	return l.PushTokenInfo(in)
}

func (s *MarketServer) GetPairInfoByToken(ctx context.Context, in *market.GetPairInfoByTokenRequest) (*market.GetPairInfoByTokenResponse, error) {
	l := logic.NewGetPairInfoByTokenLogic(ctx, s.svcCtx)
	return l.GetPairInfoByToken(in)
}

func (s *MarketServer) GetNativeTokenPrice(ctx context.Context, in *market.GetNativeTokenPriceRequest) (*market.GetNativeTokenPriceResponse, error) {
	l := logic.NewGetNativeTokenPriceLogic(ctx, s.svcCtx)
	return l.GetNativeTokenPrice(in)
}

func (s *MarketServer) GetTokenInfo(ctx context.Context, in *market.GetTokenInfoRequest) (*market.GetTokenInfoResponse, error) {
	l := logic.NewGetTokenInfoLogic(ctx, s.svcCtx)
	return l.GetTokenInfo(in)
}

func (s *MarketServer) QuoteCpmm(ctx context.Context, in *market.QuoteCpmmRequest) (*market.QuoteCpmmResponse, error) {
	l := logic.NewQuoteCpmmLogic(ctx, s.svcCtx)
	return l.QuoteCpmm(in)
}

func (s *MarketServer) QuoteClmm(ctx context.Context, in *market.QuoteClmmRequest) (*market.QuoteClmmResponse, error) {
	l := logic.NewQuoteClmmLogic(ctx, s.svcCtx)
	return l.QuoteClmm(in)
}

func (s *MarketServer) GetClmmPoolDepthData(ctx context.Context, in *market.GetClmmPoolDepthDataRequest) (*market.GetClmmPoolDepthDataResponse, error) {
	l := logic.NewGetClmmPoolDepthDataLogic(ctx, s.svcCtx)
	return l.GetClmmPoolDepthData(in)
}

// Get user's liquidity positions
func (s *MarketServer) GetUserPositions(ctx context.Context, in *market.GetUserPositionsRequest) (*market.GetUserPositionsResponse, error) {
	l := logic.NewGetUserPositionsLogic(ctx, s.svcCtx)
	return l.GetUserPositions(in)
}

// Limit order queries
func (s *MarketServer) GetLimitOrderBook(ctx context.Context, in *market.GetLimitOrderBookRequest) (*market.GetLimitOrderBookResponse, error) {
	l := logic.NewGetLimitOrderBookLogic(ctx, s.svcCtx)
	return l.GetLimitOrderBook(in)
}

func (s *MarketServer) GetUserLimitOrders(ctx context.Context, in *market.GetUserLimitOrdersRequest) (*market.GetUserLimitOrdersResponse, error) {
	l := logic.NewGetUserLimitOrdersLogic(ctx, s.svcCtx)
	return l.GetUserLimitOrders(in)
}

func (s *MarketServer) GetLimitOrderDetail(ctx context.Context, in *market.GetLimitOrderDetailRequest) (*market.GetLimitOrderDetailResponse, error) {
	l := logic.NewGetLimitOrderDetailLogic(ctx, s.svcCtx)
	return l.GetLimitOrderDetail(in)
}

func (s *MarketServer) GetLimitOrderMarkets(ctx context.Context, in *market.GetLimitOrderMarketsRequest) (*market.GetLimitOrderMarketsResponse, error) {
	l := logic.NewGetLimitOrderMarketsLogic(ctx, s.svcCtx)
	return l.GetLimitOrderMarkets(in)
}

func (s *MarketServer) GetUserMargin(ctx context.Context, in *market.GetUserMarginRequest) (*market.GetUserMarginResponse, error) {
	l := logic.NewGetUserMarginLogic(ctx, s.svcCtx)
	return l.GetUserMargin(in)
}

// Sync margin account balance from blockchain
func (s *MarketServer) SyncMarginBalance(ctx context.Context, in *market.SyncMarginBalanceRequest) (*market.SyncMarginBalanceResponse, error) {
	l := logic.NewSyncMarginBalanceLogic(ctx, s.svcCtx)
	return l.SyncMarginBalance(in)
}

func (s *MarketServer) GetLimitOrderFills(ctx context.Context, in *market.GetLimitOrderFillsRequest) (*market.GetLimitOrderFillsResponse, error) {
	l := logic.NewGetLimitOrderFillsLogic(ctx, s.svcCtx)
	return l.GetLimitOrderFills(in)
}
