-- CLMM 用户持仓信息表
CREATE TABLE `clmm_position` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `chain_id` int NOT NULL DEFAULT '0' COMMENT '链 ID',
  `user_wallet_address` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '用户钱包地址',
  `pool_state` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '池子状态地址',
  `position_nft_mint` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '持仓 NFT Mint 地址',
  `position_nft_account` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '持仓 NFT 账户地址',
  `personal_position` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '个人持仓状态账户',
  `tick_lower_index` int NOT NULL DEFAULT '0' COMMENT '价格下限 Tick 索引',
  `tick_upper_index` int NOT NULL DEFAULT '0' COMMENT '价格上限 Tick 索引',
  `tick_array_lower_start_index` int NOT NULL DEFAULT '0' COMMENT '下限 Tick 数组起始索引',
  `tick_array_upper_start_index` int NOT NULL DEFAULT '0' COMMENT '上限 Tick 数组起始索引',
  `liquidity` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0' COMMENT '流动性数量（Uint128）',
  `amount_0_max` bigint NOT NULL DEFAULT '0' COMMENT 'Token0 最大数量',
  `amount_1_max` bigint NOT NULL DEFAULT '0' COMMENT 'Token1 最大数量',
  `token_account_0` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'Token0 账户地址',
  `token_account_1` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'Token1 账户地址',
  `token_vault_0` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'Token0 资金库地址',
  `token_vault_1` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'Token1 资金库地址',
  `tx_hash` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '交易哈希',
  `slot` bigint NOT NULL DEFAULT '0' COMMENT '区块 Slot',
  `block_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '区块时间',
  `block_time_stamp` bigint NOT NULL DEFAULT '0' COMMENT '区块时间戳',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` timestamp NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `idx_position_nft_mint` (`position_nft_mint`) USING BTREE,
  KEY `idx_user_wallet` (`user_wallet_address`) USING BTREE,
  KEY `idx_pool_state` (`pool_state`) USING BTREE,
  KEY `idx_tx_hash` (`tx_hash`) USING BTREE,
  KEY `idx_block_time` (`block_time`) USING BTREE,
  KEY `idx_user_pool` (`user_wallet_address`, `pool_state`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='CLMM 用户持仓信息表';

