// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: market.proto

package market

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Market_GetPumpTokenList_FullMethodName     = "/market.Market/GetPumpTokenList"
	Market_GetClmmPoolList_FullMethodName      = "/market.Market/GetClmmPoolList"
	Market_GetPoolDetail_FullMethodName        = "/market.Market/GetPoolDetail"
	Market_PushTokenInfo_FullMethodName        = "/market.Market/PushTokenInfo"
	Market_GetPairInfoByToken_FullMethodName   = "/market.Market/GetPairInfoByToken"
	Market_GetNativeTokenPrice_FullMethodName  = "/market.Market/GetNativeTokenPrice"
	Market_GetTokenInfo_FullMethodName         = "/market.Market/GetTokenInfo"
	Market_QuoteCpmm_FullMethodName            = "/market.Market/QuoteCpmm"
	Market_QuoteClmm_FullMethodName            = "/market.Market/QuoteClmm"
	Market_GetClmmPoolDepthData_FullMethodName = "/market.Market/GetClmmPoolDepthData"
	Market_GetUserPositions_FullMethodName     = "/market.Market/GetUserPositions"
	Market_GetLimitOrderBook_FullMethodName    = "/market.Market/GetLimitOrderBook"
	Market_GetUserLimitOrders_FullMethodName   = "/market.Market/GetUserLimitOrders"
	Market_GetLimitOrderDetail_FullMethodName  = "/market.Market/GetLimitOrderDetail"
	Market_GetLimitOrderMarkets_FullMethodName = "/market.Market/GetLimitOrderMarkets"
	Market_GetUserMargin_FullMethodName        = "/market.Market/GetUserMargin"
	Market_SyncMarginBalance_FullMethodName    = "/market.Market/SyncMarginBalance"
	Market_GetLimitOrderFills_FullMethodName   = "/market.Market/GetLimitOrderFills"
)

// MarketClient is the client API for Market service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketClient interface {
	GetPumpTokenList(ctx context.Context, in *GetPumpTokenListRequest, opts ...grpc.CallOption) (*GetPumpTokenListResponse, error)
	GetClmmPoolList(ctx context.Context, in *GetClmmPoolListRequest, opts ...grpc.CallOption) (*GetClmmPoolListResponse, error)
	GetPoolDetail(ctx context.Context, in *GetPoolDetailRequest, opts ...grpc.CallOption) (*GetPoolDetailResponse, error)
	PushTokenInfo(ctx context.Context, in *PushTokenInfoRequest, opts ...grpc.CallOption) (*PushTokenInfoResponse, error)
	GetPairInfoByToken(ctx context.Context, in *GetPairInfoByTokenRequest, opts ...grpc.CallOption) (*GetPairInfoByTokenResponse, error)
	GetNativeTokenPrice(ctx context.Context, in *GetNativeTokenPriceRequest, opts ...grpc.CallOption) (*GetNativeTokenPriceResponse, error)
	GetTokenInfo(ctx context.Context, in *GetTokenInfoRequest, opts ...grpc.CallOption) (*GetTokenInfoResponse, error)
	QuoteCpmm(ctx context.Context, in *QuoteCpmmRequest, opts ...grpc.CallOption) (*QuoteCpmmResponse, error)
	QuoteClmm(ctx context.Context, in *QuoteClmmRequest, opts ...grpc.CallOption) (*QuoteClmmResponse, error)
	GetClmmPoolDepthData(ctx context.Context, in *GetClmmPoolDepthDataRequest, opts ...grpc.CallOption) (*GetClmmPoolDepthDataResponse, error)
	// Get user's liquidity positions
	GetUserPositions(ctx context.Context, in *GetUserPositionsRequest, opts ...grpc.CallOption) (*GetUserPositionsResponse, error)
	// Limit order queries
	GetLimitOrderBook(ctx context.Context, in *GetLimitOrderBookRequest, opts ...grpc.CallOption) (*GetLimitOrderBookResponse, error)
	GetUserLimitOrders(ctx context.Context, in *GetUserLimitOrdersRequest, opts ...grpc.CallOption) (*GetUserLimitOrdersResponse, error)
	GetLimitOrderDetail(ctx context.Context, in *GetLimitOrderDetailRequest, opts ...grpc.CallOption) (*GetLimitOrderDetailResponse, error)
	GetLimitOrderMarkets(ctx context.Context, in *GetLimitOrderMarketsRequest, opts ...grpc.CallOption) (*GetLimitOrderMarketsResponse, error)
	GetUserMargin(ctx context.Context, in *GetUserMarginRequest, opts ...grpc.CallOption) (*GetUserMarginResponse, error)
	// Sync margin account balance from blockchain
	SyncMarginBalance(ctx context.Context, in *SyncMarginBalanceRequest, opts ...grpc.CallOption) (*SyncMarginBalanceResponse, error)
	GetLimitOrderFills(ctx context.Context, in *GetLimitOrderFillsRequest, opts ...grpc.CallOption) (*GetLimitOrderFillsResponse, error)
}

type marketClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketClient(cc grpc.ClientConnInterface) MarketClient {
	return &marketClient{cc}
}

func (c *marketClient) GetPumpTokenList(ctx context.Context, in *GetPumpTokenListRequest, opts ...grpc.CallOption) (*GetPumpTokenListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPumpTokenListResponse)
	err := c.cc.Invoke(ctx, Market_GetPumpTokenList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetClmmPoolList(ctx context.Context, in *GetClmmPoolListRequest, opts ...grpc.CallOption) (*GetClmmPoolListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClmmPoolListResponse)
	err := c.cc.Invoke(ctx, Market_GetClmmPoolList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetPoolDetail(ctx context.Context, in *GetPoolDetailRequest, opts ...grpc.CallOption) (*GetPoolDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPoolDetailResponse)
	err := c.cc.Invoke(ctx, Market_GetPoolDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) PushTokenInfo(ctx context.Context, in *PushTokenInfoRequest, opts ...grpc.CallOption) (*PushTokenInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushTokenInfoResponse)
	err := c.cc.Invoke(ctx, Market_PushTokenInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetPairInfoByToken(ctx context.Context, in *GetPairInfoByTokenRequest, opts ...grpc.CallOption) (*GetPairInfoByTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPairInfoByTokenResponse)
	err := c.cc.Invoke(ctx, Market_GetPairInfoByToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetNativeTokenPrice(ctx context.Context, in *GetNativeTokenPriceRequest, opts ...grpc.CallOption) (*GetNativeTokenPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNativeTokenPriceResponse)
	err := c.cc.Invoke(ctx, Market_GetNativeTokenPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetTokenInfo(ctx context.Context, in *GetTokenInfoRequest, opts ...grpc.CallOption) (*GetTokenInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenInfoResponse)
	err := c.cc.Invoke(ctx, Market_GetTokenInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) QuoteCpmm(ctx context.Context, in *QuoteCpmmRequest, opts ...grpc.CallOption) (*QuoteCpmmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuoteCpmmResponse)
	err := c.cc.Invoke(ctx, Market_QuoteCpmm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) QuoteClmm(ctx context.Context, in *QuoteClmmRequest, opts ...grpc.CallOption) (*QuoteClmmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuoteClmmResponse)
	err := c.cc.Invoke(ctx, Market_QuoteClmm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetClmmPoolDepthData(ctx context.Context, in *GetClmmPoolDepthDataRequest, opts ...grpc.CallOption) (*GetClmmPoolDepthDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClmmPoolDepthDataResponse)
	err := c.cc.Invoke(ctx, Market_GetClmmPoolDepthData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetUserPositions(ctx context.Context, in *GetUserPositionsRequest, opts ...grpc.CallOption) (*GetUserPositionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserPositionsResponse)
	err := c.cc.Invoke(ctx, Market_GetUserPositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetLimitOrderBook(ctx context.Context, in *GetLimitOrderBookRequest, opts ...grpc.CallOption) (*GetLimitOrderBookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLimitOrderBookResponse)
	err := c.cc.Invoke(ctx, Market_GetLimitOrderBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetUserLimitOrders(ctx context.Context, in *GetUserLimitOrdersRequest, opts ...grpc.CallOption) (*GetUserLimitOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserLimitOrdersResponse)
	err := c.cc.Invoke(ctx, Market_GetUserLimitOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetLimitOrderDetail(ctx context.Context, in *GetLimitOrderDetailRequest, opts ...grpc.CallOption) (*GetLimitOrderDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLimitOrderDetailResponse)
	err := c.cc.Invoke(ctx, Market_GetLimitOrderDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetLimitOrderMarkets(ctx context.Context, in *GetLimitOrderMarketsRequest, opts ...grpc.CallOption) (*GetLimitOrderMarketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLimitOrderMarketsResponse)
	err := c.cc.Invoke(ctx, Market_GetLimitOrderMarkets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetUserMargin(ctx context.Context, in *GetUserMarginRequest, opts ...grpc.CallOption) (*GetUserMarginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserMarginResponse)
	err := c.cc.Invoke(ctx, Market_GetUserMargin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) SyncMarginBalance(ctx context.Context, in *SyncMarginBalanceRequest, opts ...grpc.CallOption) (*SyncMarginBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncMarginBalanceResponse)
	err := c.cc.Invoke(ctx, Market_SyncMarginBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetLimitOrderFills(ctx context.Context, in *GetLimitOrderFillsRequest, opts ...grpc.CallOption) (*GetLimitOrderFillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLimitOrderFillsResponse)
	err := c.cc.Invoke(ctx, Market_GetLimitOrderFills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketServer is the server API for Market service.
// All implementations must embed UnimplementedMarketServer
// for forward compatibility.
type MarketServer interface {
	GetPumpTokenList(context.Context, *GetPumpTokenListRequest) (*GetPumpTokenListResponse, error)
	GetClmmPoolList(context.Context, *GetClmmPoolListRequest) (*GetClmmPoolListResponse, error)
	GetPoolDetail(context.Context, *GetPoolDetailRequest) (*GetPoolDetailResponse, error)
	PushTokenInfo(context.Context, *PushTokenInfoRequest) (*PushTokenInfoResponse, error)
	GetPairInfoByToken(context.Context, *GetPairInfoByTokenRequest) (*GetPairInfoByTokenResponse, error)
	GetNativeTokenPrice(context.Context, *GetNativeTokenPriceRequest) (*GetNativeTokenPriceResponse, error)
	GetTokenInfo(context.Context, *GetTokenInfoRequest) (*GetTokenInfoResponse, error)
	QuoteCpmm(context.Context, *QuoteCpmmRequest) (*QuoteCpmmResponse, error)
	QuoteClmm(context.Context, *QuoteClmmRequest) (*QuoteClmmResponse, error)
	GetClmmPoolDepthData(context.Context, *GetClmmPoolDepthDataRequest) (*GetClmmPoolDepthDataResponse, error)
	// Get user's liquidity positions
	GetUserPositions(context.Context, *GetUserPositionsRequest) (*GetUserPositionsResponse, error)
	// Limit order queries
	GetLimitOrderBook(context.Context, *GetLimitOrderBookRequest) (*GetLimitOrderBookResponse, error)
	GetUserLimitOrders(context.Context, *GetUserLimitOrdersRequest) (*GetUserLimitOrdersResponse, error)
	GetLimitOrderDetail(context.Context, *GetLimitOrderDetailRequest) (*GetLimitOrderDetailResponse, error)
	GetLimitOrderMarkets(context.Context, *GetLimitOrderMarketsRequest) (*GetLimitOrderMarketsResponse, error)
	GetUserMargin(context.Context, *GetUserMarginRequest) (*GetUserMarginResponse, error)
	// Sync margin account balance from blockchain
	SyncMarginBalance(context.Context, *SyncMarginBalanceRequest) (*SyncMarginBalanceResponse, error)
	GetLimitOrderFills(context.Context, *GetLimitOrderFillsRequest) (*GetLimitOrderFillsResponse, error)
	mustEmbedUnimplementedMarketServer()
}

// UnimplementedMarketServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketServer struct{}

func (UnimplementedMarketServer) GetPumpTokenList(context.Context, *GetPumpTokenListRequest) (*GetPumpTokenListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPumpTokenList not implemented")
}
func (UnimplementedMarketServer) GetClmmPoolList(context.Context, *GetClmmPoolListRequest) (*GetClmmPoolListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClmmPoolList not implemented")
}
func (UnimplementedMarketServer) GetPoolDetail(context.Context, *GetPoolDetailRequest) (*GetPoolDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPoolDetail not implemented")
}
func (UnimplementedMarketServer) PushTokenInfo(context.Context, *PushTokenInfoRequest) (*PushTokenInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushTokenInfo not implemented")
}
func (UnimplementedMarketServer) GetPairInfoByToken(context.Context, *GetPairInfoByTokenRequest) (*GetPairInfoByTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPairInfoByToken not implemented")
}
func (UnimplementedMarketServer) GetNativeTokenPrice(context.Context, *GetNativeTokenPriceRequest) (*GetNativeTokenPriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNativeTokenPrice not implemented")
}
func (UnimplementedMarketServer) GetTokenInfo(context.Context, *GetTokenInfoRequest) (*GetTokenInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTokenInfo not implemented")
}
func (UnimplementedMarketServer) QuoteCpmm(context.Context, *QuoteCpmmRequest) (*QuoteCpmmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QuoteCpmm not implemented")
}
func (UnimplementedMarketServer) QuoteClmm(context.Context, *QuoteClmmRequest) (*QuoteClmmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QuoteClmm not implemented")
}
func (UnimplementedMarketServer) GetClmmPoolDepthData(context.Context, *GetClmmPoolDepthDataRequest) (*GetClmmPoolDepthDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClmmPoolDepthData not implemented")
}
func (UnimplementedMarketServer) GetUserPositions(context.Context, *GetUserPositionsRequest) (*GetUserPositionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserPositions not implemented")
}
func (UnimplementedMarketServer) GetLimitOrderBook(context.Context, *GetLimitOrderBookRequest) (*GetLimitOrderBookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLimitOrderBook not implemented")
}
func (UnimplementedMarketServer) GetUserLimitOrders(context.Context, *GetUserLimitOrdersRequest) (*GetUserLimitOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserLimitOrders not implemented")
}
func (UnimplementedMarketServer) GetLimitOrderDetail(context.Context, *GetLimitOrderDetailRequest) (*GetLimitOrderDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLimitOrderDetail not implemented")
}
func (UnimplementedMarketServer) GetLimitOrderMarkets(context.Context, *GetLimitOrderMarketsRequest) (*GetLimitOrderMarketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLimitOrderMarkets not implemented")
}
func (UnimplementedMarketServer) GetUserMargin(context.Context, *GetUserMarginRequest) (*GetUserMarginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserMargin not implemented")
}
func (UnimplementedMarketServer) SyncMarginBalance(context.Context, *SyncMarginBalanceRequest) (*SyncMarginBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncMarginBalance not implemented")
}
func (UnimplementedMarketServer) GetLimitOrderFills(context.Context, *GetLimitOrderFillsRequest) (*GetLimitOrderFillsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLimitOrderFills not implemented")
}
func (UnimplementedMarketServer) mustEmbedUnimplementedMarketServer() {}
func (UnimplementedMarketServer) testEmbeddedByValue()                {}

// UnsafeMarketServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketServer will
// result in compilation errors.
type UnsafeMarketServer interface {
	mustEmbedUnimplementedMarketServer()
}

func RegisterMarketServer(s grpc.ServiceRegistrar, srv MarketServer) {
	// If the following call panics, it indicates UnimplementedMarketServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Market_ServiceDesc, srv)
}

func _Market_GetPumpTokenList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPumpTokenListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetPumpTokenList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetPumpTokenList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetPumpTokenList(ctx, req.(*GetPumpTokenListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetClmmPoolList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClmmPoolListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetClmmPoolList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetClmmPoolList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetClmmPoolList(ctx, req.(*GetClmmPoolListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetPoolDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoolDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetPoolDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetPoolDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetPoolDetail(ctx, req.(*GetPoolDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_PushTokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushTokenInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).PushTokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_PushTokenInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).PushTokenInfo(ctx, req.(*PushTokenInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetPairInfoByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPairInfoByTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetPairInfoByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetPairInfoByToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetPairInfoByToken(ctx, req.(*GetPairInfoByTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetNativeTokenPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNativeTokenPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetNativeTokenPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetNativeTokenPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetNativeTokenPrice(ctx, req.(*GetNativeTokenPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetTokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetTokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetTokenInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetTokenInfo(ctx, req.(*GetTokenInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_QuoteCpmm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteCpmmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).QuoteCpmm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_QuoteCpmm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).QuoteCpmm(ctx, req.(*QuoteCpmmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_QuoteClmm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteClmmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).QuoteClmm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_QuoteClmm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).QuoteClmm(ctx, req.(*QuoteClmmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetClmmPoolDepthData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClmmPoolDepthDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetClmmPoolDepthData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetClmmPoolDepthData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetClmmPoolDepthData(ctx, req.(*GetClmmPoolDepthDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetUserPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetUserPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetUserPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetUserPositions(ctx, req.(*GetUserPositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetLimitOrderBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLimitOrderBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetLimitOrderBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetLimitOrderBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetLimitOrderBook(ctx, req.(*GetLimitOrderBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetUserLimitOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserLimitOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetUserLimitOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetUserLimitOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetUserLimitOrders(ctx, req.(*GetUserLimitOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetLimitOrderDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLimitOrderDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetLimitOrderDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetLimitOrderDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetLimitOrderDetail(ctx, req.(*GetLimitOrderDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetLimitOrderMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLimitOrderMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetLimitOrderMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetLimitOrderMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetLimitOrderMarkets(ctx, req.(*GetLimitOrderMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetUserMargin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserMarginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetUserMargin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetUserMargin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetUserMargin(ctx, req.(*GetUserMarginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_SyncMarginBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncMarginBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).SyncMarginBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_SyncMarginBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).SyncMarginBalance(ctx, req.(*SyncMarginBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetLimitOrderFills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLimitOrderFillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetLimitOrderFills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_GetLimitOrderFills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetLimitOrderFills(ctx, req.(*GetLimitOrderFillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Market_ServiceDesc is the grpc.ServiceDesc for Market service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Market_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "market.Market",
	HandlerType: (*MarketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPumpTokenList",
			Handler:    _Market_GetPumpTokenList_Handler,
		},
		{
			MethodName: "GetClmmPoolList",
			Handler:    _Market_GetClmmPoolList_Handler,
		},
		{
			MethodName: "GetPoolDetail",
			Handler:    _Market_GetPoolDetail_Handler,
		},
		{
			MethodName: "PushTokenInfo",
			Handler:    _Market_PushTokenInfo_Handler,
		},
		{
			MethodName: "GetPairInfoByToken",
			Handler:    _Market_GetPairInfoByToken_Handler,
		},
		{
			MethodName: "GetNativeTokenPrice",
			Handler:    _Market_GetNativeTokenPrice_Handler,
		},
		{
			MethodName: "GetTokenInfo",
			Handler:    _Market_GetTokenInfo_Handler,
		},
		{
			MethodName: "QuoteCpmm",
			Handler:    _Market_QuoteCpmm_Handler,
		},
		{
			MethodName: "QuoteClmm",
			Handler:    _Market_QuoteClmm_Handler,
		},
		{
			MethodName: "GetClmmPoolDepthData",
			Handler:    _Market_GetClmmPoolDepthData_Handler,
		},
		{
			MethodName: "GetUserPositions",
			Handler:    _Market_GetUserPositions_Handler,
		},
		{
			MethodName: "GetLimitOrderBook",
			Handler:    _Market_GetLimitOrderBook_Handler,
		},
		{
			MethodName: "GetUserLimitOrders",
			Handler:    _Market_GetUserLimitOrders_Handler,
		},
		{
			MethodName: "GetLimitOrderDetail",
			Handler:    _Market_GetLimitOrderDetail_Handler,
		},
		{
			MethodName: "GetLimitOrderMarkets",
			Handler:    _Market_GetLimitOrderMarkets_Handler,
		},
		{
			MethodName: "GetUserMargin",
			Handler:    _Market_GetUserMargin_Handler,
		},
		{
			MethodName: "SyncMarginBalance",
			Handler:    _Market_SyncMarginBalance_Handler,
		},
		{
			MethodName: "GetLimitOrderFills",
			Handler:    _Market_GetLimitOrderFills_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market.proto",
}
