// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: market.proto

package market

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetPumpTokenList
type GetPumpTokenListRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChainId        int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	PumpStatus     int32                  `protobuf:"varint,2,opt,name=pump_status,json=pumpStatus,proto3" json:"pump_status,omitempty"`
	SortedType     string                 `protobuf:"bytes,3,opt,name=sorted_type,json=sortedType,proto3" json:"sorted_type,omitempty"`
	HoneypotFilter string                 `protobuf:"bytes,4,opt,name=honeypot_filter,json=honeypotFilter,proto3" json:"honeypot_filter,omitempty"`
	PageNo         int32                  `protobuf:"varint,5,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
	PageSize       int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PumpType       string                 `protobuf:"bytes,7,opt,name=pump_type,json=pumpType,proto3" json:"pump_type,omitempty"` // "pumpfun" or "pumpamm", default "pumpfun"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPumpTokenListRequest) Reset() {
	*x = GetPumpTokenListRequest{}
	mi := &file_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPumpTokenListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPumpTokenListRequest) ProtoMessage() {}

func (x *GetPumpTokenListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPumpTokenListRequest.ProtoReflect.Descriptor instead.
func (*GetPumpTokenListRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{0}
}

func (x *GetPumpTokenListRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetPumpTokenListRequest) GetPumpStatus() int32 {
	if x != nil {
		return x.PumpStatus
	}
	return 0
}

func (x *GetPumpTokenListRequest) GetSortedType() string {
	if x != nil {
		return x.SortedType
	}
	return ""
}

func (x *GetPumpTokenListRequest) GetHoneypotFilter() string {
	if x != nil {
		return x.HoneypotFilter
	}
	return ""
}

func (x *GetPumpTokenListRequest) GetPageNo() int32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *GetPumpTokenListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetPumpTokenListRequest) GetPumpType() string {
	if x != nil {
		return x.PumpType
	}
	return ""
}

type GetPumpTokenListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*PumpTokenItem       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPumpTokenListResponse) Reset() {
	*x = GetPumpTokenListResponse{}
	mi := &file_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPumpTokenListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPumpTokenListResponse) ProtoMessage() {}

func (x *GetPumpTokenListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPumpTokenListResponse.ProtoReflect.Descriptor instead.
func (*GetPumpTokenListResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{1}
}

func (x *GetPumpTokenListResponse) GetList() []*PumpTokenItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetPumpTokenListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PumpTokenItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChainId          int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ChainIcon        string                 `protobuf:"bytes,2,opt,name=chain_icon,json=chainIcon,proto3" json:"chain_icon,omitempty"`
	TokenAddress     string                 `protobuf:"bytes,3,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	TokenIcon        string                 `protobuf:"bytes,4,opt,name=token_icon,json=tokenIcon,proto3" json:"token_icon,omitempty"`
	TokenName        string                 `protobuf:"bytes,5,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`
	LaunchTime       int64                  `protobuf:"varint,6,opt,name=launch_time,json=launchTime,proto3" json:"launch_time,omitempty"`
	MktCap           float64                `protobuf:"fixed64,7,opt,name=mkt_cap,json=mktCap,proto3" json:"mkt_cap,omitempty"`
	HoldCount        int64                  `protobuf:"varint,8,opt,name=hold_count,json=holdCount,proto3" json:"hold_count,omitempty"`
	Txs_24H          uint32                 `protobuf:"varint,9,opt,name=txs_24h,json=txs24h,proto3" json:"txs_24h,omitempty"`
	Vol_24H          float64                `protobuf:"fixed64,10,opt,name=vol_24h,json=vol24h,proto3" json:"vol_24h,omitempty"`
	DomesticProgress float64                `protobuf:"fixed64,11,opt,name=domestic_progress,json=domesticProgress,proto3" json:"domestic_progress,omitempty"`
	TwitterUsername  string                 `protobuf:"bytes,12,opt,name=twitter_username,json=twitterUsername,proto3" json:"twitter_username,omitempty"`
	Telegram         string                 `protobuf:"bytes,13,opt,name=telegram,proto3" json:"telegram,omitempty"`
	Change24         float64                `protobuf:"fixed64,14,opt,name=change24,proto3" json:"change24,omitempty"`
	PairAddress      string                 `protobuf:"bytes,15,opt,name=pair_address,json=pairAddress,proto3" json:"pair_address,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PumpTokenItem) Reset() {
	*x = PumpTokenItem{}
	mi := &file_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PumpTokenItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PumpTokenItem) ProtoMessage() {}

func (x *PumpTokenItem) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PumpTokenItem.ProtoReflect.Descriptor instead.
func (*PumpTokenItem) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{2}
}

func (x *PumpTokenItem) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *PumpTokenItem) GetChainIcon() string {
	if x != nil {
		return x.ChainIcon
	}
	return ""
}

func (x *PumpTokenItem) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *PumpTokenItem) GetTokenIcon() string {
	if x != nil {
		return x.TokenIcon
	}
	return ""
}

func (x *PumpTokenItem) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *PumpTokenItem) GetLaunchTime() int64 {
	if x != nil {
		return x.LaunchTime
	}
	return 0
}

func (x *PumpTokenItem) GetMktCap() float64 {
	if x != nil {
		return x.MktCap
	}
	return 0
}

func (x *PumpTokenItem) GetHoldCount() int64 {
	if x != nil {
		return x.HoldCount
	}
	return 0
}

func (x *PumpTokenItem) GetTxs_24H() uint32 {
	if x != nil {
		return x.Txs_24H
	}
	return 0
}

func (x *PumpTokenItem) GetVol_24H() float64 {
	if x != nil {
		return x.Vol_24H
	}
	return 0
}

func (x *PumpTokenItem) GetDomesticProgress() float64 {
	if x != nil {
		return x.DomesticProgress
	}
	return 0
}

func (x *PumpTokenItem) GetTwitterUsername() string {
	if x != nil {
		return x.TwitterUsername
	}
	return ""
}

func (x *PumpTokenItem) GetTelegram() string {
	if x != nil {
		return x.Telegram
	}
	return ""
}

func (x *PumpTokenItem) GetChange24() float64 {
	if x != nil {
		return x.Change24
	}
	return 0
}

func (x *PumpTokenItem) GetPairAddress() string {
	if x != nil {
		return x.PairAddress
	}
	return ""
}

// GetClmmPoolList
type GetClmmPoolListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	PoolVersion   int32                  `protobuf:"varint,2,opt,name=pool_version,json=poolVersion,proto3" json:"pool_version,omitempty"` // 1 for v1, 2 for v2
	SortedType    string                 `protobuf:"bytes,3,opt,name=sorted_type,json=sortedType,proto3" json:"sorted_type,omitempty"`
	PageNo        int32                  `protobuf:"varint,4,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClmmPoolListRequest) Reset() {
	*x = GetClmmPoolListRequest{}
	mi := &file_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClmmPoolListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClmmPoolListRequest) ProtoMessage() {}

func (x *GetClmmPoolListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClmmPoolListRequest.ProtoReflect.Descriptor instead.
func (*GetClmmPoolListRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{3}
}

func (x *GetClmmPoolListRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetClmmPoolListRequest) GetPoolVersion() int32 {
	if x != nil {
		return x.PoolVersion
	}
	return 0
}

func (x *GetClmmPoolListRequest) GetSortedType() string {
	if x != nil {
		return x.SortedType
	}
	return ""
}

func (x *GetClmmPoolListRequest) GetPageNo() int32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *GetClmmPoolListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetClmmPoolListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ClmmPoolItem        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClmmPoolListResponse) Reset() {
	*x = GetClmmPoolListResponse{}
	mi := &file_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClmmPoolListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClmmPoolListResponse) ProtoMessage() {}

func (x *GetClmmPoolListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClmmPoolListResponse.ProtoReflect.Descriptor instead.
func (*GetClmmPoolListResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{4}
}

func (x *GetClmmPoolListResponse) GetList() []*ClmmPoolItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetClmmPoolListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ClmmPoolItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChainId           int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ChainIcon         string                 `protobuf:"bytes,2,opt,name=chain_icon,json=chainIcon,proto3" json:"chain_icon,omitempty"`
	PoolState         string                 `protobuf:"bytes,3,opt,name=pool_state,json=poolState,proto3" json:"pool_state,omitempty"`                           // Pool state address (like pair_address for pumps)
	InputVaultMint    string                 `protobuf:"bytes,4,opt,name=input_vault_mint,json=inputVaultMint,proto3" json:"input_vault_mint,omitempty"`          // Input token address
	OutputVaultMint   string                 `protobuf:"bytes,5,opt,name=output_vault_mint,json=outputVaultMint,proto3" json:"output_vault_mint,omitempty"`       // Output token address
	InputTokenSymbol  string                 `protobuf:"bytes,6,opt,name=input_token_symbol,json=inputTokenSymbol,proto3" json:"input_token_symbol,omitempty"`    // Input token symbol
	OutputTokenSymbol string                 `protobuf:"bytes,7,opt,name=output_token_symbol,json=outputTokenSymbol,proto3" json:"output_token_symbol,omitempty"` // Output token symbol
	InputTokenIcon    string                 `protobuf:"bytes,8,opt,name=input_token_icon,json=inputTokenIcon,proto3" json:"input_token_icon,omitempty"`          // Input token icon
	OutputTokenIcon   string                 `protobuf:"bytes,9,opt,name=output_token_icon,json=outputTokenIcon,proto3" json:"output_token_icon,omitempty"`       // Output token icon
	TradeFeeRate      int64                  `protobuf:"varint,10,opt,name=trade_fee_rate,json=tradeFeeRate,proto3" json:"trade_fee_rate,omitempty"`              // Trade fee rate
	LaunchTime        int64                  `protobuf:"varint,11,opt,name=launch_time,json=launchTime,proto3" json:"launch_time,omitempty"`                      // Pool creation time
	LiquidityUsd      float64                `protobuf:"fixed64,12,opt,name=liquidity_usd,json=liquidityUsd,proto3" json:"liquidity_usd,omitempty"`               // Liquidity in USD
	Txs_24H           uint32                 `protobuf:"varint,13,opt,name=txs_24h,json=txs24h,proto3" json:"txs_24h,omitempty"`                                  // 24h transactions
	Vol_24H           float64                `protobuf:"fixed64,14,opt,name=vol_24h,json=vol24h,proto3" json:"vol_24h,omitempty"`                                 // 24h volume
	Apr               float64                `protobuf:"fixed64,15,opt,name=apr,proto3" json:"apr,omitempty"`                                                     // Annual percentage rate
	PoolVersion       int32                  `protobuf:"varint,16,opt,name=pool_version,json=poolVersion,proto3" json:"pool_version,omitempty"`                   // 1 for v1, 2 for v2
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClmmPoolItem) Reset() {
	*x = ClmmPoolItem{}
	mi := &file_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClmmPoolItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClmmPoolItem) ProtoMessage() {}

func (x *ClmmPoolItem) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClmmPoolItem.ProtoReflect.Descriptor instead.
func (*ClmmPoolItem) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{5}
}

func (x *ClmmPoolItem) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *ClmmPoolItem) GetChainIcon() string {
	if x != nil {
		return x.ChainIcon
	}
	return ""
}

func (x *ClmmPoolItem) GetPoolState() string {
	if x != nil {
		return x.PoolState
	}
	return ""
}

func (x *ClmmPoolItem) GetInputVaultMint() string {
	if x != nil {
		return x.InputVaultMint
	}
	return ""
}

func (x *ClmmPoolItem) GetOutputVaultMint() string {
	if x != nil {
		return x.OutputVaultMint
	}
	return ""
}

func (x *ClmmPoolItem) GetInputTokenSymbol() string {
	if x != nil {
		return x.InputTokenSymbol
	}
	return ""
}

func (x *ClmmPoolItem) GetOutputTokenSymbol() string {
	if x != nil {
		return x.OutputTokenSymbol
	}
	return ""
}

func (x *ClmmPoolItem) GetInputTokenIcon() string {
	if x != nil {
		return x.InputTokenIcon
	}
	return ""
}

func (x *ClmmPoolItem) GetOutputTokenIcon() string {
	if x != nil {
		return x.OutputTokenIcon
	}
	return ""
}

func (x *ClmmPoolItem) GetTradeFeeRate() int64 {
	if x != nil {
		return x.TradeFeeRate
	}
	return 0
}

func (x *ClmmPoolItem) GetLaunchTime() int64 {
	if x != nil {
		return x.LaunchTime
	}
	return 0
}

func (x *ClmmPoolItem) GetLiquidityUsd() float64 {
	if x != nil {
		return x.LiquidityUsd
	}
	return 0
}

func (x *ClmmPoolItem) GetTxs_24H() uint32 {
	if x != nil {
		return x.Txs_24H
	}
	return 0
}

func (x *ClmmPoolItem) GetVol_24H() float64 {
	if x != nil {
		return x.Vol_24H
	}
	return 0
}

func (x *ClmmPoolItem) GetApr() float64 {
	if x != nil {
		return x.Apr
	}
	return 0
}

func (x *ClmmPoolItem) GetPoolVersion() int32 {
	if x != nil {
		return x.PoolVersion
	}
	return 0
}

type PushTokenInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	TokenAddress  string                 `protobuf:"bytes,2,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	PairAddress   string                 `protobuf:"bytes,3,opt,name=pair_address,json=pairAddress,proto3" json:"pair_address,omitempty"`
	TokenPrice    float64                `protobuf:"fixed64,4,opt,name=token_price,json=tokenPrice,proto3" json:"token_price,omitempty"`
	MktCap        float64                `protobuf:"fixed64,5,opt,name=mkt_cap,json=mktCap,proto3" json:"mkt_cap,omitempty"`
	TokenName     string                 `protobuf:"bytes,6,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`
	TokenSymbol   string                 `protobuf:"bytes,7,opt,name=token_symbol,json=tokenSymbol,proto3" json:"token_symbol,omitempty"`
	TokenIcon     string                 `protobuf:"bytes,8,opt,name=token_icon,json=tokenIcon,proto3" json:"token_icon,omitempty"`
	LaunchTime    int64                  `protobuf:"varint,9,opt,name=launch_time,json=launchTime,proto3" json:"launch_time,omitempty"`
	HoldCount     int64                  `protobuf:"varint,10,opt,name=hold_count,json=holdCount,proto3" json:"hold_count,omitempty"`
	Change_24     float64                `protobuf:"fixed64,11,opt,name=change_24,json=change24,proto3" json:"change_24,omitempty"`
	Txs_24H       int64                  `protobuf:"varint,12,opt,name=txs_24h,json=txs24h,proto3" json:"txs_24h,omitempty"`
	PumpStatus    int32                  `protobuf:"varint,13,opt,name=pump_status,json=pumpStatus,proto3" json:"pump_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushTokenInfoRequest) Reset() {
	*x = PushTokenInfoRequest{}
	mi := &file_market_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushTokenInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushTokenInfoRequest) ProtoMessage() {}

func (x *PushTokenInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushTokenInfoRequest.ProtoReflect.Descriptor instead.
func (*PushTokenInfoRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{6}
}

func (x *PushTokenInfoRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *PushTokenInfoRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *PushTokenInfoRequest) GetPairAddress() string {
	if x != nil {
		return x.PairAddress
	}
	return ""
}

func (x *PushTokenInfoRequest) GetTokenPrice() float64 {
	if x != nil {
		return x.TokenPrice
	}
	return 0
}

func (x *PushTokenInfoRequest) GetMktCap() float64 {
	if x != nil {
		return x.MktCap
	}
	return 0
}

func (x *PushTokenInfoRequest) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *PushTokenInfoRequest) GetTokenSymbol() string {
	if x != nil {
		return x.TokenSymbol
	}
	return ""
}

func (x *PushTokenInfoRequest) GetTokenIcon() string {
	if x != nil {
		return x.TokenIcon
	}
	return ""
}

func (x *PushTokenInfoRequest) GetLaunchTime() int64 {
	if x != nil {
		return x.LaunchTime
	}
	return 0
}

func (x *PushTokenInfoRequest) GetHoldCount() int64 {
	if x != nil {
		return x.HoldCount
	}
	return 0
}

func (x *PushTokenInfoRequest) GetChange_24() float64 {
	if x != nil {
		return x.Change_24
	}
	return 0
}

func (x *PushTokenInfoRequest) GetTxs_24H() int64 {
	if x != nil {
		return x.Txs_24H
	}
	return 0
}

func (x *PushTokenInfoRequest) GetPumpStatus() int32 {
	if x != nil {
		return x.PumpStatus
	}
	return 0
}

type PushTokenInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	TokenAddress  string                 `protobuf:"bytes,2,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Txs_24H       uint32                 `protobuf:"varint,3,opt,name=txs_24h,json=txs24h,proto3" json:"txs_24h,omitempty"`
	Vol_24H       string                 `protobuf:"bytes,4,opt,name=vol_24h,json=vol24h,proto3" json:"vol_24h,omitempty"`
	Change_24     string                 `protobuf:"bytes,5,opt,name=change_24,json=change24,proto3" json:"change_24,omitempty"`
	TokenPrice    string                 `protobuf:"bytes,6,opt,name=token_price,json=tokenPrice,proto3" json:"token_price,omitempty"`
	MktCap        string                 `protobuf:"bytes,7,opt,name=mkt_cap,json=mktCap,proto3" json:"mkt_cap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushTokenInfoResponse) Reset() {
	*x = PushTokenInfoResponse{}
	mi := &file_market_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushTokenInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushTokenInfoResponse) ProtoMessage() {}

func (x *PushTokenInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushTokenInfoResponse.ProtoReflect.Descriptor instead.
func (*PushTokenInfoResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{7}
}

func (x *PushTokenInfoResponse) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *PushTokenInfoResponse) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *PushTokenInfoResponse) GetTxs_24H() uint32 {
	if x != nil {
		return x.Txs_24H
	}
	return 0
}

func (x *PushTokenInfoResponse) GetVol_24H() string {
	if x != nil {
		return x.Vol_24H
	}
	return ""
}

func (x *PushTokenInfoResponse) GetChange_24() string {
	if x != nil {
		return x.Change_24
	}
	return ""
}

func (x *PushTokenInfoResponse) GetTokenPrice() string {
	if x != nil {
		return x.TokenPrice
	}
	return ""
}

func (x *PushTokenInfoResponse) GetMktCap() string {
	if x != nil {
		return x.MktCap
	}
	return ""
}

type GetPairInfoByTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	TokenAddress  string                 `protobuf:"bytes,2,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPairInfoByTokenRequest) Reset() {
	*x = GetPairInfoByTokenRequest{}
	mi := &file_market_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPairInfoByTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPairInfoByTokenRequest) ProtoMessage() {}

func (x *GetPairInfoByTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPairInfoByTokenRequest.ProtoReflect.Descriptor instead.
func (*GetPairInfoByTokenRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{8}
}

func (x *GetPairInfoByTokenRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetPairInfoByTokenRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

type GetPairInfoByTokenResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ChainId                int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`                                                     // Chain ID
	Address                string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                                                                     // Trading pair address
	Name                   string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                                                           // DEX factory version swap name
	FactoryAddress         string                 `protobuf:"bytes,4,opt,name=factory_address,json=factoryAddress,proto3" json:"factory_address,omitempty"`                                 // Factory contract address
	BaseTokenAddress       string                 `protobuf:"bytes,5,opt,name=base_token_address,json=baseTokenAddress,proto3" json:"base_token_address,omitempty"`                         // Base token address
	TokenAddress           string                 `protobuf:"bytes,6,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`                                       // Token address
	BaseTokenSymbol        string                 `protobuf:"bytes,7,opt,name=base_token_symbol,json=baseTokenSymbol,proto3" json:"base_token_symbol,omitempty"`                            // Base token symbol
	TokenSymbol            string                 `protobuf:"bytes,8,opt,name=token_symbol,json=tokenSymbol,proto3" json:"token_symbol,omitempty"`                                          // Token symbol
	BaseTokenDecimal       int64                  `protobuf:"varint,9,opt,name=base_token_decimal,json=baseTokenDecimal,proto3" json:"base_token_decimal,omitempty"`                        // Base token decimals
	TokenDecimal           int64                  `protobuf:"varint,10,opt,name=token_decimal,json=tokenDecimal,proto3" json:"token_decimal,omitempty"`                                     // Token decimals
	BaseTokenIsNativeToken bool                   `protobuf:"varint,11,opt,name=base_token_is_native_token,json=baseTokenIsNativeToken,proto3" json:"base_token_is_native_token,omitempty"` // Is base token native currency
	BaseTokenIsToken0      bool                   `protobuf:"varint,12,opt,name=base_token_is_token0,json=baseTokenIsToken0,proto3" json:"base_token_is_token0,omitempty"`                  // Is base token token0
	InitBaseTokenAmount    float64                `protobuf:"fixed64,13,opt,name=init_base_token_amount,json=initBaseTokenAmount,proto3" json:"init_base_token_amount,omitempty"`           // Initial base token liquidity
	InitTokenAmount        float64                `protobuf:"fixed64,14,opt,name=init_token_amount,json=initTokenAmount,proto3" json:"init_token_amount,omitempty"`                         // Initial token liquidity
	CurrentBaseTokenAmount float64                `protobuf:"fixed64,15,opt,name=current_base_token_amount,json=currentBaseTokenAmount,proto3" json:"current_base_token_amount,omitempty"`  // Current base token liquidity
	CurrentTokenAmount     float64                `protobuf:"fixed64,16,opt,name=current_token_amount,json=currentTokenAmount,proto3" json:"current_token_amount,omitempty"`                // Current token liquidity
	Fdv                    float64                `protobuf:"fixed64,17,opt,name=fdv,proto3" json:"fdv,omitempty"`                                                                          // Fully diluted valuation
	MktCap                 float64                `protobuf:"fixed64,18,opt,name=mkt_cap,json=mktCap,proto3" json:"mkt_cap,omitempty"`                                                      // Market capitalization
	TokenPrice             float64                `protobuf:"fixed64,19,opt,name=token_price,json=tokenPrice,proto3" json:"token_price,omitempty"`                                          // Token price
	BaseTokenPrice         float64                `protobuf:"fixed64,20,opt,name=base_token_price,json=baseTokenPrice,proto3" json:"base_token_price,omitempty"`                            // Base token price
	BlockNum               int64                  `protobuf:"varint,21,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`                                                 // Creation block height
	BlockTime              int64                  `protobuf:"varint,22,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`                                              // Creation block timestamp
	HighestTokenPrice      float64                `protobuf:"fixed64,23,opt,name=highest_token_price,json=highestTokenPrice,proto3" json:"highest_token_price,omitempty"`                   // Highest token price
	LatestTradeTime        int64                  `protobuf:"varint,24,opt,name=latest_trade_time,json=latestTradeTime,proto3" json:"latest_trade_time,omitempty"`                          // Latest on-chain trade timestamp
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetPairInfoByTokenResponse) Reset() {
	*x = GetPairInfoByTokenResponse{}
	mi := &file_market_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPairInfoByTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPairInfoByTokenResponse) ProtoMessage() {}

func (x *GetPairInfoByTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPairInfoByTokenResponse.ProtoReflect.Descriptor instead.
func (*GetPairInfoByTokenResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{9}
}

func (x *GetPairInfoByTokenResponse) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetPairInfoByTokenResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetPairInfoByTokenResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPairInfoByTokenResponse) GetFactoryAddress() string {
	if x != nil {
		return x.FactoryAddress
	}
	return ""
}

func (x *GetPairInfoByTokenResponse) GetBaseTokenAddress() string {
	if x != nil {
		return x.BaseTokenAddress
	}
	return ""
}

func (x *GetPairInfoByTokenResponse) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *GetPairInfoByTokenResponse) GetBaseTokenSymbol() string {
	if x != nil {
		return x.BaseTokenSymbol
	}
	return ""
}

func (x *GetPairInfoByTokenResponse) GetTokenSymbol() string {
	if x != nil {
		return x.TokenSymbol
	}
	return ""
}

func (x *GetPairInfoByTokenResponse) GetBaseTokenDecimal() int64 {
	if x != nil {
		return x.BaseTokenDecimal
	}
	return 0
}

func (x *GetPairInfoByTokenResponse) GetTokenDecimal() int64 {
	if x != nil {
		return x.TokenDecimal
	}
	return 0
}

func (x *GetPairInfoByTokenResponse) GetBaseTokenIsNativeToken() bool {
	if x != nil {
		return x.BaseTokenIsNativeToken
	}
	return false
}

func (x *GetPairInfoByTokenResponse) GetBaseTokenIsToken0() bool {
	if x != nil {
		return x.BaseTokenIsToken0
	}
	return false
}

func (x *GetPairInfoByTokenResponse) GetInitBaseTokenAmount() float64 {
	if x != nil {
		return x.InitBaseTokenAmount
	}
	return 0
}

func (x *GetPairInfoByTokenResponse) GetInitTokenAmount() float64 {
	if x != nil {
		return x.InitTokenAmount
	}
	return 0
}

func (x *GetPairInfoByTokenResponse) GetCurrentBaseTokenAmount() float64 {
	if x != nil {
		return x.CurrentBaseTokenAmount
	}
	return 0
}

func (x *GetPairInfoByTokenResponse) GetCurrentTokenAmount() float64 {
	if x != nil {
		return x.CurrentTokenAmount
	}
	return 0
}

func (x *GetPairInfoByTokenResponse) GetFdv() float64 {
	if x != nil {
		return x.Fdv
	}
	return 0
}

func (x *GetPairInfoByTokenResponse) GetMktCap() float64 {
	if x != nil {
		return x.MktCap
	}
	return 0
}

func (x *GetPairInfoByTokenResponse) GetTokenPrice() float64 {
	if x != nil {
		return x.TokenPrice
	}
	return 0
}

func (x *GetPairInfoByTokenResponse) GetBaseTokenPrice() float64 {
	if x != nil {
		return x.BaseTokenPrice
	}
	return 0
}

func (x *GetPairInfoByTokenResponse) GetBlockNum() int64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *GetPairInfoByTokenResponse) GetBlockTime() int64 {
	if x != nil {
		return x.BlockTime
	}
	return 0
}

func (x *GetPairInfoByTokenResponse) GetHighestTokenPrice() float64 {
	if x != nil {
		return x.HighestTokenPrice
	}
	return 0
}

func (x *GetPairInfoByTokenResponse) GetLatestTradeTime() int64 {
	if x != nil {
		return x.LatestTradeTime
	}
	return 0
}

type GetNativeTokenPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	SearchTime    string                 `protobuf:"bytes,2,opt,name=search_time,json=searchTime,proto3" json:"search_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNativeTokenPriceRequest) Reset() {
	*x = GetNativeTokenPriceRequest{}
	mi := &file_market_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNativeTokenPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNativeTokenPriceRequest) ProtoMessage() {}

func (x *GetNativeTokenPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNativeTokenPriceRequest.ProtoReflect.Descriptor instead.
func (*GetNativeTokenPriceRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{10}
}

func (x *GetNativeTokenPriceRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetNativeTokenPriceRequest) GetSearchTime() string {
	if x != nil {
		return x.SearchTime
	}
	return ""
}

type GetNativeTokenPriceResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BaseTokenPriceUsd float64                `protobuf:"fixed64,1,opt,name=base_token_price_usd,json=baseTokenPriceUsd,proto3" json:"base_token_price_usd,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetNativeTokenPriceResponse) Reset() {
	*x = GetNativeTokenPriceResponse{}
	mi := &file_market_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNativeTokenPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNativeTokenPriceResponse) ProtoMessage() {}

func (x *GetNativeTokenPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNativeTokenPriceResponse.ProtoReflect.Descriptor instead.
func (*GetNativeTokenPriceResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{11}
}

func (x *GetNativeTokenPriceResponse) GetBaseTokenPriceUsd() float64 {
	if x != nil {
		return x.BaseTokenPriceUsd
	}
	return 0
}

type GetTokenInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	TokenAddress  string                 `protobuf:"bytes,2,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenInfoRequest) Reset() {
	*x = GetTokenInfoRequest{}
	mi := &file_market_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenInfoRequest) ProtoMessage() {}

func (x *GetTokenInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenInfoRequest.ProtoReflect.Descriptor instead.
func (*GetTokenInfoRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{12}
}

func (x *GetTokenInfoRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetTokenInfoRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

type GetTokenInfoResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChainId           int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`                                    // Chain ID
	Address           string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                                                    // Token contract address
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                                          // Token name
	Symbol            string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`                                                      // Token symbol
	Decimals          int64                  `protobuf:"varint,5,opt,name=decimals,proto3" json:"decimals,omitempty"`                                                 // Token decimals
	TotalSupply       float64                `protobuf:"fixed64,6,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`                       // Total token supply
	Icon              string                 `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`                                                          // Token icon URL
	HoldCount         int64                  `protobuf:"varint,8,opt,name=hold_count,json=holdCount,proto3" json:"hold_count,omitempty"`                              // Number of holders
	IsCaDropOwner     int64                  `protobuf:"varint,9,opt,name=is_ca_drop_owner,json=isCaDropOwner,proto3" json:"is_ca_drop_owner,omitempty"`              // Owner rights renounced
	IsCaVerify        int64                  `protobuf:"varint,10,opt,name=is_ca_verify,json=isCaVerify,proto3" json:"is_ca_verify,omitempty"`                        // Contract verified
	IsHoneyScam       int64                  `protobuf:"varint,11,opt,name=is_honey_scam,json=isHoneyScam,proto3" json:"is_honey_scam,omitempty"`                     // Honeypot check (Cannot sell)
	IsLiquidLock      int64                  `protobuf:"varint,12,opt,name=is_liquid_lock,json=isLiquidLock,proto3" json:"is_liquid_lock,omitempty"`                  // Liquidity locked
	IsCanPauseTrade   int64                  `protobuf:"varint,13,opt,name=is_can_pause_trade,json=isCanPauseTrade,proto3" json:"is_can_pause_trade,omitempty"`       // Can pause trading
	IsCanChangeTax    int64                  `protobuf:"varint,14,opt,name=is_can_change_tax,json=isCanChangeTax,proto3" json:"is_can_change_tax,omitempty"`          // Can modify tax rate
	IsHaveBlackList   int64                  `protobuf:"varint,15,opt,name=is_have_black_list,json=isHaveBlackList,proto3" json:"is_have_black_list,omitempty"`       // Has blacklist mechanism
	IsCanAllSell      int64                  `protobuf:"varint,16,opt,name=is_can_all_sell,json=isCanAllSell,proto3" json:"is_can_all_sell,omitempty"`                // Can sell entire balance
	IsHaveProxy       int64                  `protobuf:"varint,17,opt,name=is_have_proxy,json=isHaveProxy,proto3" json:"is_have_proxy,omitempty"`                     // Has proxy contract
	IsCanExternalCall int64                  `protobuf:"varint,18,opt,name=is_can_external_call,json=isCanExternalCall,proto3" json:"is_can_external_call,omitempty"` // Contract can make external calls
	IsCanAddToken     int64                  `protobuf:"varint,19,opt,name=is_can_add_token,json=isCanAddToken,proto3" json:"is_can_add_token,omitempty"`             // Contract has minting capability
	IsCanChangeToken  int64                  `protobuf:"varint,20,opt,name=is_can_change_token,json=isCanChangeToken,proto3" json:"is_can_change_token,omitempty"`    // Owner can modify user balances
	SellTax           float64                `protobuf:"fixed64,21,opt,name=sell_tax,json=sellTax,proto3" json:"sell_tax,omitempty"`                                  // Sell tax rate
	BuyTax            float64                `protobuf:"fixed64,22,opt,name=buy_tax,json=buyTax,proto3" json:"buy_tax,omitempty"`                                     // Buy tax rate
	TwitterUsername   string                 `protobuf:"bytes,23,opt,name=twitter_username,json=twitterUsername,proto3" json:"twitter_username,omitempty"`            // Twitter username
	Website           string                 `protobuf:"bytes,24,opt,name=website,proto3" json:"website,omitempty"`                                                   // Official website
	Telegram          string                 `protobuf:"bytes,25,opt,name=telegram,proto3" json:"telegram,omitempty"`                                                 // Telegram link
	IsCheckCa         int64                  `protobuf:"varint,26,opt,name=is_check_ca,json=isCheckCa,proto3" json:"is_check_ca,omitempty"`                           // Contract analysis completed
	CheckCaAt         int64                  `protobuf:"varint,27,opt,name=check_ca_at,json=checkCaAt,proto3" json:"check_ca_at,omitempty"`                           // Contract analysis datetime(3)
	Program           string                 `protobuf:"bytes,28,opt,name=program,proto3" json:"program,omitempty"`                                                   // token owner program
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetTokenInfoResponse) Reset() {
	*x = GetTokenInfoResponse{}
	mi := &file_market_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenInfoResponse) ProtoMessage() {}

func (x *GetTokenInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenInfoResponse.ProtoReflect.Descriptor instead.
func (*GetTokenInfoResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{13}
}

func (x *GetTokenInfoResponse) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetTokenInfoResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetTokenInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTokenInfoResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetTokenInfoResponse) GetDecimals() int64 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *GetTokenInfoResponse) GetTotalSupply() float64 {
	if x != nil {
		return x.TotalSupply
	}
	return 0
}

func (x *GetTokenInfoResponse) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *GetTokenInfoResponse) GetHoldCount() int64 {
	if x != nil {
		return x.HoldCount
	}
	return 0
}

func (x *GetTokenInfoResponse) GetIsCaDropOwner() int64 {
	if x != nil {
		return x.IsCaDropOwner
	}
	return 0
}

func (x *GetTokenInfoResponse) GetIsCaVerify() int64 {
	if x != nil {
		return x.IsCaVerify
	}
	return 0
}

func (x *GetTokenInfoResponse) GetIsHoneyScam() int64 {
	if x != nil {
		return x.IsHoneyScam
	}
	return 0
}

func (x *GetTokenInfoResponse) GetIsLiquidLock() int64 {
	if x != nil {
		return x.IsLiquidLock
	}
	return 0
}

func (x *GetTokenInfoResponse) GetIsCanPauseTrade() int64 {
	if x != nil {
		return x.IsCanPauseTrade
	}
	return 0
}

func (x *GetTokenInfoResponse) GetIsCanChangeTax() int64 {
	if x != nil {
		return x.IsCanChangeTax
	}
	return 0
}

func (x *GetTokenInfoResponse) GetIsHaveBlackList() int64 {
	if x != nil {
		return x.IsHaveBlackList
	}
	return 0
}

func (x *GetTokenInfoResponse) GetIsCanAllSell() int64 {
	if x != nil {
		return x.IsCanAllSell
	}
	return 0
}

func (x *GetTokenInfoResponse) GetIsHaveProxy() int64 {
	if x != nil {
		return x.IsHaveProxy
	}
	return 0
}

func (x *GetTokenInfoResponse) GetIsCanExternalCall() int64 {
	if x != nil {
		return x.IsCanExternalCall
	}
	return 0
}

func (x *GetTokenInfoResponse) GetIsCanAddToken() int64 {
	if x != nil {
		return x.IsCanAddToken
	}
	return 0
}

func (x *GetTokenInfoResponse) GetIsCanChangeToken() int64 {
	if x != nil {
		return x.IsCanChangeToken
	}
	return 0
}

func (x *GetTokenInfoResponse) GetSellTax() float64 {
	if x != nil {
		return x.SellTax
	}
	return 0
}

func (x *GetTokenInfoResponse) GetBuyTax() float64 {
	if x != nil {
		return x.BuyTax
	}
	return 0
}

func (x *GetTokenInfoResponse) GetTwitterUsername() string {
	if x != nil {
		return x.TwitterUsername
	}
	return ""
}

func (x *GetTokenInfoResponse) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *GetTokenInfoResponse) GetTelegram() string {
	if x != nil {
		return x.Telegram
	}
	return ""
}

func (x *GetTokenInfoResponse) GetIsCheckCa() int64 {
	if x != nil {
		return x.IsCheckCa
	}
	return 0
}

func (x *GetTokenInfoResponse) GetCheckCaAt() int64 {
	if x != nil {
		return x.CheckCaAt
	}
	return 0
}

func (x *GetTokenInfoResponse) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

var File_market_proto protoreflect.FileDescriptor

const file_market_proto_rawDesc = "" +
	"\n" +
	"\fmarket.proto\x12\x06market\"\xf2\x01\n" +
	"\x17GetPumpTokenListRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12\x1f\n" +
	"\vpump_status\x18\x02 \x01(\x05R\n" +
	"pumpStatus\x12\x1f\n" +
	"\vsorted_type\x18\x03 \x01(\tR\n" +
	"sortedType\x12'\n" +
	"\x0fhoneypot_filter\x18\x04 \x01(\tR\x0ehoneypotFilter\x12\x17\n" +
	"\apage_no\x18\x05 \x01(\x05R\x06pageNo\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\tpump_type\x18\a \x01(\tR\bpumpType\"[\n" +
	"\x18GetPumpTokenListResponse\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.market.PumpTokenItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xea\x03\n" +
	"\rPumpTokenItem\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12\x1d\n" +
	"\n" +
	"chain_icon\x18\x02 \x01(\tR\tchainIcon\x12#\n" +
	"\rtoken_address\x18\x03 \x01(\tR\ftokenAddress\x12\x1d\n" +
	"\n" +
	"token_icon\x18\x04 \x01(\tR\ttokenIcon\x12\x1d\n" +
	"\n" +
	"token_name\x18\x05 \x01(\tR\ttokenName\x12\x1f\n" +
	"\vlaunch_time\x18\x06 \x01(\x03R\n" +
	"launchTime\x12\x17\n" +
	"\amkt_cap\x18\a \x01(\x01R\x06mktCap\x12\x1d\n" +
	"\n" +
	"hold_count\x18\b \x01(\x03R\tholdCount\x12\x17\n" +
	"\atxs_24h\x18\t \x01(\rR\x06txs24h\x12\x17\n" +
	"\avol_24h\x18\n" +
	" \x01(\x01R\x06vol24h\x12+\n" +
	"\x11domestic_progress\x18\v \x01(\x01R\x10domesticProgress\x12)\n" +
	"\x10twitter_username\x18\f \x01(\tR\x0ftwitterUsername\x12\x1a\n" +
	"\btelegram\x18\r \x01(\tR\btelegram\x12\x1a\n" +
	"\bchange24\x18\x0e \x01(\x01R\bchange24\x12!\n" +
	"\fpair_address\x18\x0f \x01(\tR\vpairAddress\"\xad\x01\n" +
	"\x16GetClmmPoolListRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12!\n" +
	"\fpool_version\x18\x02 \x01(\x05R\vpoolVersion\x12\x1f\n" +
	"\vsorted_type\x18\x03 \x01(\tR\n" +
	"sortedType\x12\x17\n" +
	"\apage_no\x18\x04 \x01(\x05R\x06pageNo\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"Y\n" +
	"\x17GetClmmPoolListResponse\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.market.ClmmPoolItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xc4\x04\n" +
	"\fClmmPoolItem\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12\x1d\n" +
	"\n" +
	"chain_icon\x18\x02 \x01(\tR\tchainIcon\x12\x1d\n" +
	"\n" +
	"pool_state\x18\x03 \x01(\tR\tpoolState\x12(\n" +
	"\x10input_vault_mint\x18\x04 \x01(\tR\x0einputVaultMint\x12*\n" +
	"\x11output_vault_mint\x18\x05 \x01(\tR\x0foutputVaultMint\x12,\n" +
	"\x12input_token_symbol\x18\x06 \x01(\tR\x10inputTokenSymbol\x12.\n" +
	"\x13output_token_symbol\x18\a \x01(\tR\x11outputTokenSymbol\x12(\n" +
	"\x10input_token_icon\x18\b \x01(\tR\x0einputTokenIcon\x12*\n" +
	"\x11output_token_icon\x18\t \x01(\tR\x0foutputTokenIcon\x12$\n" +
	"\x0etrade_fee_rate\x18\n" +
	" \x01(\x03R\ftradeFeeRate\x12\x1f\n" +
	"\vlaunch_time\x18\v \x01(\x03R\n" +
	"launchTime\x12#\n" +
	"\rliquidity_usd\x18\f \x01(\x01R\fliquidityUsd\x12\x17\n" +
	"\atxs_24h\x18\r \x01(\rR\x06txs24h\x12\x17\n" +
	"\avol_24h\x18\x0e \x01(\x01R\x06vol24h\x12\x10\n" +
	"\x03apr\x18\x0f \x01(\x01R\x03apr\x12!\n" +
	"\fpool_version\x18\x10 \x01(\x05R\vpoolVersion\"\xab\x03\n" +
	"\x14PushTokenInfoRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12#\n" +
	"\rtoken_address\x18\x02 \x01(\tR\ftokenAddress\x12!\n" +
	"\fpair_address\x18\x03 \x01(\tR\vpairAddress\x12\x1f\n" +
	"\vtoken_price\x18\x04 \x01(\x01R\n" +
	"tokenPrice\x12\x17\n" +
	"\amkt_cap\x18\x05 \x01(\x01R\x06mktCap\x12\x1d\n" +
	"\n" +
	"token_name\x18\x06 \x01(\tR\ttokenName\x12!\n" +
	"\ftoken_symbol\x18\a \x01(\tR\vtokenSymbol\x12\x1d\n" +
	"\n" +
	"token_icon\x18\b \x01(\tR\ttokenIcon\x12\x1f\n" +
	"\vlaunch_time\x18\t \x01(\x03R\n" +
	"launchTime\x12\x1d\n" +
	"\n" +
	"hold_count\x18\n" +
	" \x01(\x03R\tholdCount\x12\x1b\n" +
	"\tchange_24\x18\v \x01(\x01R\bchange24\x12\x17\n" +
	"\atxs_24h\x18\f \x01(\x03R\x06txs24h\x12\x1f\n" +
	"\vpump_status\x18\r \x01(\x05R\n" +
	"pumpStatus\"\xe0\x01\n" +
	"\x15PushTokenInfoResponse\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12#\n" +
	"\rtoken_address\x18\x02 \x01(\tR\ftokenAddress\x12\x17\n" +
	"\atxs_24h\x18\x03 \x01(\rR\x06txs24h\x12\x17\n" +
	"\avol_24h\x18\x04 \x01(\tR\x06vol24h\x12\x1b\n" +
	"\tchange_24\x18\x05 \x01(\tR\bchange24\x12\x1f\n" +
	"\vtoken_price\x18\x06 \x01(\tR\n" +
	"tokenPrice\x12\x17\n" +
	"\amkt_cap\x18\a \x01(\tR\x06mktCap\"[\n" +
	"\x19GetPairInfoByTokenRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12#\n" +
	"\rtoken_address\x18\x02 \x01(\tR\ftokenAddress\"\xcc\a\n" +
	"\x1aGetPairInfoByTokenResponse\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12'\n" +
	"\x0ffactory_address\x18\x04 \x01(\tR\x0efactoryAddress\x12,\n" +
	"\x12base_token_address\x18\x05 \x01(\tR\x10baseTokenAddress\x12#\n" +
	"\rtoken_address\x18\x06 \x01(\tR\ftokenAddress\x12*\n" +
	"\x11base_token_symbol\x18\a \x01(\tR\x0fbaseTokenSymbol\x12!\n" +
	"\ftoken_symbol\x18\b \x01(\tR\vtokenSymbol\x12,\n" +
	"\x12base_token_decimal\x18\t \x01(\x03R\x10baseTokenDecimal\x12#\n" +
	"\rtoken_decimal\x18\n" +
	" \x01(\x03R\ftokenDecimal\x12:\n" +
	"\x1abase_token_is_native_token\x18\v \x01(\bR\x16baseTokenIsNativeToken\x12/\n" +
	"\x14base_token_is_token0\x18\f \x01(\bR\x11baseTokenIsToken0\x123\n" +
	"\x16init_base_token_amount\x18\r \x01(\x01R\x13initBaseTokenAmount\x12*\n" +
	"\x11init_token_amount\x18\x0e \x01(\x01R\x0finitTokenAmount\x129\n" +
	"\x19current_base_token_amount\x18\x0f \x01(\x01R\x16currentBaseTokenAmount\x120\n" +
	"\x14current_token_amount\x18\x10 \x01(\x01R\x12currentTokenAmount\x12\x10\n" +
	"\x03fdv\x18\x11 \x01(\x01R\x03fdv\x12\x17\n" +
	"\amkt_cap\x18\x12 \x01(\x01R\x06mktCap\x12\x1f\n" +
	"\vtoken_price\x18\x13 \x01(\x01R\n" +
	"tokenPrice\x12(\n" +
	"\x10base_token_price\x18\x14 \x01(\x01R\x0ebaseTokenPrice\x12\x1b\n" +
	"\tblock_num\x18\x15 \x01(\x03R\bblockNum\x12\x1d\n" +
	"\n" +
	"block_time\x18\x16 \x01(\x03R\tblockTime\x12.\n" +
	"\x13highest_token_price\x18\x17 \x01(\x01R\x11highestTokenPrice\x12*\n" +
	"\x11latest_trade_time\x18\x18 \x01(\x03R\x0flatestTradeTime\"X\n" +
	"\x1aGetNativeTokenPriceRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12\x1f\n" +
	"\vsearch_time\x18\x02 \x01(\tR\n" +
	"searchTime\"N\n" +
	"\x1bGetNativeTokenPriceResponse\x12/\n" +
	"\x14base_token_price_usd\x18\x01 \x01(\x01R\x11baseTokenPriceUsd\"U\n" +
	"\x13GetTokenInfoRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12#\n" +
	"\rtoken_address\x18\x02 \x01(\tR\ftokenAddress\"\xc6\a\n" +
	"\x14GetTokenInfoResponse\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bdecimals\x18\x05 \x01(\x03R\bdecimals\x12!\n" +
	"\ftotal_supply\x18\x06 \x01(\x01R\vtotalSupply\x12\x12\n" +
	"\x04icon\x18\a \x01(\tR\x04icon\x12\x1d\n" +
	"\n" +
	"hold_count\x18\b \x01(\x03R\tholdCount\x12'\n" +
	"\x10is_ca_drop_owner\x18\t \x01(\x03R\risCaDropOwner\x12 \n" +
	"\fis_ca_verify\x18\n" +
	" \x01(\x03R\n" +
	"isCaVerify\x12\"\n" +
	"\ris_honey_scam\x18\v \x01(\x03R\visHoneyScam\x12$\n" +
	"\x0eis_liquid_lock\x18\f \x01(\x03R\fisLiquidLock\x12+\n" +
	"\x12is_can_pause_trade\x18\r \x01(\x03R\x0fisCanPauseTrade\x12)\n" +
	"\x11is_can_change_tax\x18\x0e \x01(\x03R\x0eisCanChangeTax\x12+\n" +
	"\x12is_have_black_list\x18\x0f \x01(\x03R\x0fisHaveBlackList\x12%\n" +
	"\x0fis_can_all_sell\x18\x10 \x01(\x03R\fisCanAllSell\x12\"\n" +
	"\ris_have_proxy\x18\x11 \x01(\x03R\visHaveProxy\x12/\n" +
	"\x14is_can_external_call\x18\x12 \x01(\x03R\x11isCanExternalCall\x12'\n" +
	"\x10is_can_add_token\x18\x13 \x01(\x03R\risCanAddToken\x12-\n" +
	"\x13is_can_change_token\x18\x14 \x01(\x03R\x10isCanChangeToken\x12\x19\n" +
	"\bsell_tax\x18\x15 \x01(\x01R\asellTax\x12\x17\n" +
	"\abuy_tax\x18\x16 \x01(\x01R\x06buyTax\x12)\n" +
	"\x10twitter_username\x18\x17 \x01(\tR\x0ftwitterUsername\x12\x18\n" +
	"\awebsite\x18\x18 \x01(\tR\awebsite\x12\x1a\n" +
	"\btelegram\x18\x19 \x01(\tR\btelegram\x12\x1e\n" +
	"\vis_check_ca\x18\x1a \x01(\x03R\tisCheckCa\x12\x1e\n" +
	"\vcheck_ca_at\x18\x1b \x01(\x03R\tcheckCaAt\x12\x18\n" +
	"\aprogram\x18\x1c \x01(\tR\aprogram2\x89\x04\n" +
	"\x06Market\x12U\n" +
	"\x10GetPumpTokenList\x12\x1f.market.GetPumpTokenListRequest\x1a .market.GetPumpTokenListResponse\x12R\n" +
	"\x0fGetClmmPoolList\x12\x1e.market.GetClmmPoolListRequest\x1a\x1f.market.GetClmmPoolListResponse\x12L\n" +
	"\rPushTokenInfo\x12\x1c.market.PushTokenInfoRequest\x1a\x1d.market.PushTokenInfoResponse\x12[\n" +
	"\x12GetPairInfoByToken\x12!.market.GetPairInfoByTokenRequest\x1a\".market.GetPairInfoByTokenResponse\x12^\n" +
	"\x13GetNativeTokenPrice\x12\".market.GetNativeTokenPriceRequest\x1a#.market.GetNativeTokenPriceResponse\x12I\n" +
	"\fGetTokenInfo\x12\x1b.market.GetTokenInfoRequest\x1a\x1c.market.GetTokenInfoResponseB\n" +
	"Z\b./marketb\x06proto3"

var (
	file_market_proto_rawDescOnce sync.Once
	file_market_proto_rawDescData []byte
)

func file_market_proto_rawDescGZIP() []byte {
	file_market_proto_rawDescOnce.Do(func() {
		file_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_proto_rawDesc), len(file_market_proto_rawDesc)))
	})
	return file_market_proto_rawDescData
}

var file_market_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_market_proto_goTypes = []any{
	(*GetPumpTokenListRequest)(nil),     // 0: market.GetPumpTokenListRequest
	(*GetPumpTokenListResponse)(nil),    // 1: market.GetPumpTokenListResponse
	(*PumpTokenItem)(nil),               // 2: market.PumpTokenItem
	(*GetClmmPoolListRequest)(nil),      // 3: market.GetClmmPoolListRequest
	(*GetClmmPoolListResponse)(nil),     // 4: market.GetClmmPoolListResponse
	(*ClmmPoolItem)(nil),                // 5: market.ClmmPoolItem
	(*PushTokenInfoRequest)(nil),        // 6: market.PushTokenInfoRequest
	(*PushTokenInfoResponse)(nil),       // 7: market.PushTokenInfoResponse
	(*GetPairInfoByTokenRequest)(nil),   // 8: market.GetPairInfoByTokenRequest
	(*GetPairInfoByTokenResponse)(nil),  // 9: market.GetPairInfoByTokenResponse
	(*GetNativeTokenPriceRequest)(nil),  // 10: market.GetNativeTokenPriceRequest
	(*GetNativeTokenPriceResponse)(nil), // 11: market.GetNativeTokenPriceResponse
	(*GetTokenInfoRequest)(nil),         // 12: market.GetTokenInfoRequest
	(*GetTokenInfoResponse)(nil),        // 13: market.GetTokenInfoResponse
}
var file_market_proto_depIdxs = []int32{
	2,  // 0: market.GetPumpTokenListResponse.list:type_name -> market.PumpTokenItem
	5,  // 1: market.GetClmmPoolListResponse.list:type_name -> market.ClmmPoolItem
	0,  // 2: market.Market.GetPumpTokenList:input_type -> market.GetPumpTokenListRequest
	3,  // 3: market.Market.GetClmmPoolList:input_type -> market.GetClmmPoolListRequest
	6,  // 4: market.Market.PushTokenInfo:input_type -> market.PushTokenInfoRequest
	8,  // 5: market.Market.GetPairInfoByToken:input_type -> market.GetPairInfoByTokenRequest
	10, // 6: market.Market.GetNativeTokenPrice:input_type -> market.GetNativeTokenPriceRequest
	12, // 7: market.Market.GetTokenInfo:input_type -> market.GetTokenInfoRequest
	1,  // 8: market.Market.GetPumpTokenList:output_type -> market.GetPumpTokenListResponse
	4,  // 9: market.Market.GetClmmPoolList:output_type -> market.GetClmmPoolListResponse
	7,  // 10: market.Market.PushTokenInfo:output_type -> market.PushTokenInfoResponse
	9,  // 11: market.Market.GetPairInfoByToken:output_type -> market.GetPairInfoByTokenResponse
	11, // 12: market.Market.GetNativeTokenPrice:output_type -> market.GetNativeTokenPriceResponse
	13, // 13: market.Market.GetTokenInfo:output_type -> market.GetTokenInfoResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_market_proto_init() }
func file_market_proto_init() {
	if File_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_proto_rawDesc), len(file_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_proto_goTypes,
		DependencyIndexes: file_market_proto_depIdxs,
		MessageInfos:      file_market_proto_msgTypes,
	}.Build()
	File_market_proto = out.File
	file_market_proto_goTypes = nil
	file_market_proto_depIdxs = nil
}
