// Code generated by goctl. DO NOT EDIT!

package limitordermodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
)

// avoid unused err
var _ = time.Second

type (
	limitOrderMarketModel interface {
		Insert(ctx context.Context, data *LimitOrderMarket) error

		FindOne(ctx context.Context, id int64) (*LimitOrderMarket, error)
		FindOneByBaseMintQuoteMintNetwork(ctx context.Context, baseMint string, quoteMint string, network string) (*LimitOrderMarket, error)
		FindOneByMarketPda(ctx context.Context, marketPda string) (*LimitOrderMarket, error)
		Update(ctx context.Context, data *LimitOrderMarket) error

		Delete(ctx context.Context, id int64) error
	}

	defaultLimitOrderMarketModel struct {
		conn  *gorm.DB
		table string
	}

	LimitOrderMarket struct {
		Id             int64          `gorm:"column:id"`              // 主键ID
		MarketPda      string         `gorm:"column:market_pda"`      // 市场 PDA
		BaseMint       string         `gorm:"column:base_mint"`       // base 代币地址
		QuoteMint      string         `gorm:"column:quote_mint"`      // quote 代币地址
		BaseSymbol     string         `gorm:"column:base_symbol"`     // base 代币符号
		QuoteSymbol    string         `gorm:"column:quote_symbol"`    // quote 代币符号
		BaseDecimals   int64          `gorm:"column:base_decimals"`   // base 代币精度
		QuoteDecimals  int64          `gorm:"column:quote_decimals"`  // quote 代币精度
		BaseVault      string         `gorm:"column:base_vault"`      // base 金库 PDA
		QuoteVault     string         `gorm:"column:quote_vault"`     // quote 金库 PDA
		TickSize       int64          `gorm:"column:tick_size"`       // 价格精度（lots）
		MinBaseLot     int64          `gorm:"column:min_base_lot"`    // 最小 base 下单量（lots）
		MinQuoteLot    int64          `gorm:"column:min_quote_lot"`   // 最小 quote 下单量（lots）
		MakerFeeBps    int64          `gorm:"column:maker_fee_bps"`   // maker 费率（bps）
		TakerFeeBps    int64          `gorm:"column:taker_fee_bps"`   // taker 费率（bps）
		FeeAccumulator int64          `gorm:"column:fee_accumulator"` // 累积费用
		SeqNum         int64          `gorm:"column:seq_num"`         // 订单序列号
		PythPriceFeed  sql.NullString `gorm:"column:pyth_price_feed"` // Pyth 价格源
		Paused         int64          `gorm:"column:paused"`          // 暂停状态
		Status         int64          `gorm:"column:status"`          // 市场状态: 0=创建中 1=正常 2=已关闭
		InitTxHash     sql.NullString `gorm:"column:init_tx_hash"`    // 初始化交易哈希
		Network        string         `gorm:"column:network"`         // 网络
		CreatedAt      time.Time      `gorm:"column:created_at"`      // 创建时间
		UpdatedAt      time.Time      `gorm:"column:updated_at"`      // 更新时间
	}
)

var QLimitOrderMarket LimitOrderMarket

func init() {
	InitField(&QLimitOrderMarket)
}

func (LimitOrderMarket) TableName() string {
	return strings.Trim("`limit_order_market`", "`")
}

func newLimitOrderMarketModel(conn *gorm.DB) *defaultLimitOrderMarketModel {
	return &defaultLimitOrderMarketModel{
		conn:  conn,
		table: strings.Trim("`limit_order_market`", "`"),
	}
}

func (m *defaultLimitOrderMarketModel) Insert(ctx context.Context, data *LimitOrderMarket) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultLimitOrderMarketModel) FindOne(ctx context.Context, id int64) (*LimitOrderMarket, error) {
	var resp LimitOrderMarket
	err := m.conn.WithContext(ctx).Model(&LimitOrderMarket{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err

}

func (m *defaultLimitOrderMarketModel) FindOneByBaseMintQuoteMintNetwork(ctx context.Context, baseMint string, quoteMint string, network string) (*LimitOrderMarket, error) {
	var resp LimitOrderMarket
	err := m.conn.WithContext(ctx).Model(&LimitOrderMarket{}).Where("`base_mint` = ? and `quote_mint` = ? and `network` = ?", baseMint, quoteMint, network).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultLimitOrderMarketModel) FindOneByMarketPda(ctx context.Context, marketPda string) (*LimitOrderMarket, error) {
	var resp LimitOrderMarket
	err := m.conn.WithContext(ctx).Model(&LimitOrderMarket{}).Where("`market_pda` = ?", marketPda).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultLimitOrderMarketModel) Update(ctx context.Context, data *LimitOrderMarket) error {
	db := m.conn
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultLimitOrderMarketModel) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Where("`id` = @id", sql.Named("id", id)).Delete(&LimitOrderMarket{}).Error

	return err
}
