// Code generated by goctl. DO NOT EDIT!

package limitordermodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
)

// avoid unused err
var _ = time.Second

type (
	limitOrderModel interface {
		Insert(ctx context.Context, data *LimitOrder) error

		FindOne(ctx context.Context, id int64) (*LimitOrder, error)
		FindOneByOrderPda(ctx context.Context, orderPda string) (*LimitOrder, error)
		Update(ctx context.Context, data *LimitOrder) error

		Delete(ctx context.Context, id int64) error
	}

	defaultLimitOrderModel struct {
		conn  *gorm.DB
		table string
	}

	LimitOrder struct {
		Id                int64          `gorm:"column:id"`                  // 主键ID
		OrderPda          string         `gorm:"column:order_pda"`           // 订单 PDA
		MarketId          int64          `gorm:"column:market_id"`           // 市场 ID（外键）
		MarketPda         string         `gorm:"column:market_pda"`          // 市场 PDA
		Owner             string         `gorm:"column:owner"`               // 订单所有者
		MarginPda         string         `gorm:"column:margin_pda"`          // 保证金账户 PDA
		OrderId           int64          `gorm:"column:order_id"`            // 链上订单序列号
		Side              int64          `gorm:"column:side"`                // 方向: 1=Bid(买) 2=Ask(卖)
		PriceLots         int64          `gorm:"column:price_lots"`          // 价格（lots）
		QtyLots           int64          `gorm:"column:qty_lots"`            // 数量（lots）
		RemainingLots     int64          `gorm:"column:remaining_lots"`      // 剩余数量（lots）
		LockedSide        int64          `gorm:"column:locked_side"`         // 锁定方向: 1=Base 2=Quote
		ExpirySlot        int64          `gorm:"column:expiry_slot"`         // 过期 slot
		MinFillBps        sql.NullInt64  `gorm:"column:min_fill_bps"`        // 最小成交比例（bps）
		SelfTradeBehavior int64          `gorm:"column:self_trade_behavior"` // 自成交行为: 1=DecrementTake 2=CancelNew
		PriceDisplay      float64        `gorm:"column:price_display"`       // 显示价格
		QtyDisplay        float64        `gorm:"column:qty_display"`         // 显示数量
		RemainingDisplay  float64        `gorm:"column:remaining_display"`   // 剩余数量显示
		TotalValueDisplay float64        `gorm:"column:total_value_display"` // 总价值显示
		Status            int64          `gorm:"column:status"`              // 状态: 1=Active 2=Filled 3=Cancelled 4=Expired
		FilledPercent     float64        `gorm:"column:filled_percent"`      // 成交百分比
		CreateTxHash      sql.NullString `gorm:"column:create_tx_hash"`      // 创建交易哈希
		CancelTxHash      sql.NullString `gorm:"column:cancel_tx_hash"`      // 取消交易哈希
		CreatedAt         time.Time      `gorm:"column:created_at"`          // 创建时间
		UpdatedAt         time.Time      `gorm:"column:updated_at"`          // 更新时间
		FilledAt          sql.NullTime   `gorm:"column:filled_at"`           // 完全成交时间
		CancelledAt       sql.NullTime   `gorm:"column:cancelled_at"`        // 取消时间
		ExpiredAt         sql.NullTime   `gorm:"column:expired_at"`          // 过期时间
	}
)

var QLimitOrder LimitOrder

func init() {
	InitField(&QLimitOrder)
}

func (LimitOrder) TableName() string {
	return strings.Trim("`limit_order`", "`")
}

func newLimitOrderModel(conn *gorm.DB) *defaultLimitOrderModel {
	return &defaultLimitOrderModel{
		conn:  conn,
		table: strings.Trim("`limit_order`", "`"),
	}
}

func (m *defaultLimitOrderModel) Insert(ctx context.Context, data *LimitOrder) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultLimitOrderModel) FindOne(ctx context.Context, id int64) (*LimitOrder, error) {
	var resp LimitOrder
	err := m.conn.WithContext(ctx).Model(&LimitOrder{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err

}

func (m *defaultLimitOrderModel) FindOneByOrderPda(ctx context.Context, orderPda string) (*LimitOrder, error) {
	var resp LimitOrder
	err := m.conn.WithContext(ctx).Model(&LimitOrder{}).Where("`order_pda` = ?", orderPda).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultLimitOrderModel) Update(ctx context.Context, data *LimitOrder) error {
	db := m.conn
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultLimitOrderModel) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Where("`id` = @id", sql.Named("id", id)).Delete(&LimitOrder{}).Error

	return err
}
