// Code generated by goctl. DO NOT EDIT!

package limitordermodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
)

// avoid unused err
var _ = time.Second

type (
	limitOrderMarginModel interface {
		Insert(ctx context.Context, data *LimitOrderMargin) error

		FindOne(ctx context.Context, id int64) (*LimitOrderMargin, error)
		FindOneByMarginPda(ctx context.Context, marginPda string) (*LimitOrderMargin, error)
		FindOneByOwnerMarketId(ctx context.Context, owner string, marketId int64) (*LimitOrderMargin, error)
		Update(ctx context.Context, data *LimitOrderMargin) error

		Delete(ctx context.Context, id int64) error
	}

	defaultLimitOrderMarginModel struct {
		conn  *gorm.DB
		table string
	}

	LimitOrderMargin struct {
		Id                 int64          `gorm:"column:id"`                   // 主键ID
		MarginPda          string         `gorm:"column:margin_pda"`           // 保证金账户 PDA
		MarketId           int64          `gorm:"column:market_id"`            // 市场 ID
		MarketPda          string         `gorm:"column:market_pda"`           // 市场 PDA
		Owner              string         `gorm:"column:owner"`                // 用户地址
		BaseFree           int64          `gorm:"column:base_free"`            // base 可用余额（lots）
		BaseLocked         int64          `gorm:"column:base_locked"`          // base 锁定余额（lots）
		QuoteFree          int64          `gorm:"column:quote_free"`           // quote 可用余额（lots）
		QuoteLocked        int64          `gorm:"column:quote_locked"`         // quote 锁定余额（lots）
		BaseFreeDisplay    float64        `gorm:"column:base_free_display"`    // base 可用（显示）
		BaseLockedDisplay  float64        `gorm:"column:base_locked_display"`  // base 锁定（显示）
		QuoteFreeDisplay   float64        `gorm:"column:quote_free_display"`   // quote 可用（显示）
		QuoteLockedDisplay float64        `gorm:"column:quote_locked_display"` // quote 锁定（显示）
		Status             int            `gorm:"column:status"`               // 状态: 0=创建中 1=正常 2=已关闭
		InitTxHash         sql.NullString `gorm:"column:init_tx_hash"`         // 初始化交易哈希
		LastSyncSlot       int64          `gorm:"column:last_sync_slot"`       // 最后同步 slot
		CreatedAt          time.Time      `gorm:"column:created_at"`           // 创建时间
		UpdatedAt          time.Time      `gorm:"column:updated_at"`           // 更新时间
	}
)

var QLimitOrderMargin LimitOrderMargin

func init() {
	InitField(&QLimitOrderMargin)
}

func (LimitOrderMargin) TableName() string {
	return strings.Trim("`limit_order_margin`", "`")
}

func newLimitOrderMarginModel(conn *gorm.DB) *defaultLimitOrderMarginModel {
	return &defaultLimitOrderMarginModel{
		conn:  conn,
		table: strings.Trim("`limit_order_margin`", "`"),
	}
}

func (m *defaultLimitOrderMarginModel) Insert(ctx context.Context, data *LimitOrderMargin) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultLimitOrderMarginModel) FindOne(ctx context.Context, id int64) (*LimitOrderMargin, error) {
	var resp LimitOrderMargin
	err := m.conn.WithContext(ctx).Model(&LimitOrderMargin{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err

}

func (m *defaultLimitOrderMarginModel) FindOneByMarginPda(ctx context.Context, marginPda string) (*LimitOrderMargin, error) {
	var resp LimitOrderMargin
	err := m.conn.WithContext(ctx).Model(&LimitOrderMargin{}).Where("`margin_pda` = ?", marginPda).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultLimitOrderMarginModel) FindOneByOwnerMarketId(ctx context.Context, owner string, marketId int64) (*LimitOrderMargin, error) {
	var resp LimitOrderMargin
	err := m.conn.WithContext(ctx).Model(&LimitOrderMargin{}).Where("`owner` = ? and `market_id` = ?", owner, marketId).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultLimitOrderMarginModel) Update(ctx context.Context, data *LimitOrderMargin) error {
	db := m.conn
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultLimitOrderMarginModel) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Where("`id` = @id", sql.Named("id", id)).Delete(&LimitOrderMargin{}).Error

	return err
}
