// Code generated by goctl. DO NOT EDIT!

package limitordermodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
)

// avoid unused err
var _ = time.Second

type (
	limitOrderFillModel interface {
		Insert(ctx context.Context, data *LimitOrderFill) error

		FindOne(ctx context.Context, id int64) (*LimitOrderFill, error)
		Update(ctx context.Context, data *LimitOrderFill) error

		Delete(ctx context.Context, id int64) error
	}

	defaultLimitOrderFillModel struct {
		conn  *gorm.DB
		table string
	}

	LimitOrderFill struct {
		Id                int64     `gorm:"column:id"`                  // 主键ID
		MakerOrderId      int64     `gorm:"column:maker_order_id"`      // maker 订单 ID
		TakerOrderId      int64     `gorm:"column:taker_order_id"`      // taker 订单 ID
		MarketId          int64     `gorm:"column:market_id"`           // 市场 ID
		MarketPda         string    `gorm:"column:market_pda"`          // 市场 PDA
		Maker             string    `gorm:"column:maker"`               // maker 地址
		Taker             string    `gorm:"column:taker"`               // taker 地址
		QtyLots           int64     `gorm:"column:qty_lots"`            // 成交数量（lots）
		PriceLots         int64     `gorm:"column:price_lots"`          // 成交价格（lots）
		Fee               int64     `gorm:"column:fee"`                 // taker 手续费（quote token, lots）
		QtyDisplay        float64   `gorm:"column:qty_display"`         // 成交数量（显示）
		PriceDisplay      float64   `gorm:"column:price_display"`       // 成交价格（显示）
		FeeDisplay        float64   `gorm:"column:fee_display"`         // 手续费（显示）
		TotalValueDisplay float64   `gorm:"column:total_value_display"` // 成交总价值（显示）
		TxHash            string    `gorm:"column:tx_hash"`             // 撮合交易哈希
		Slot              int64     `gorm:"column:slot"`                // 成交 slot
		CreatedAt         time.Time `gorm:"column:created_at"`          // 成交时间
	}
)

var QLimitOrderFill LimitOrderFill

func init() {
	InitField(&QLimitOrderFill)
}

func (LimitOrderFill) TableName() string {
	return strings.Trim("`limit_order_fill`", "`")
}

func newLimitOrderFillModel(conn *gorm.DB) *defaultLimitOrderFillModel {
	return &defaultLimitOrderFillModel{
		conn:  conn,
		table: strings.Trim("`limit_order_fill`", "`"),
	}
}

func (m *defaultLimitOrderFillModel) Insert(ctx context.Context, data *LimitOrderFill) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultLimitOrderFillModel) FindOne(ctx context.Context, id int64) (*LimitOrderFill, error) {
	var resp LimitOrderFill
	err := m.conn.WithContext(ctx).Model(&LimitOrderFill{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err

}

func (m *defaultLimitOrderFillModel) Update(ctx context.Context, data *LimitOrderFill) error {
	db := m.conn
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultLimitOrderFillModel) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Where("`id` = @id", sql.Named("id", id)).Delete(&LimitOrderFill{}).Error

	return err
}
