// Code generated by goctl. DO NOT EDIT!

package limitordermodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
)

// avoid unused err
var _ = time.Second

type (
	limitOrderConfigModel interface {
		Insert(ctx context.Context, data *LimitOrderConfig) error

		FindOne(ctx context.Context, id int64) (*LimitOrderConfig, error)
		FindOneByProgramIdNetwork(ctx context.Context, programId string, network string) (*LimitOrderConfig, error)
		Update(ctx context.Context, data *LimitOrderConfig) error

		Delete(ctx context.Context, id int64) error
	}

	defaultLimitOrderConfigModel struct {
		conn  *gorm.DB
		table string
	}

	LimitOrderConfig struct {
		Id                    int64          `gorm:"column:id"`                       // 主键ID
		ProgramId             string         `gorm:"column:program_id"`               // Solana 程序 ID
		ConfigPda             string         `gorm:"column:config_pda"`               // 配置账户 PDA
		Admin                 string         `gorm:"column:admin"`                    // 管理员公钥
		Treasury              string         `gorm:"column:treasury"`                 // 金库地址
		Matcher               sql.NullString `gorm:"column:matcher"`                  // 撮合器公钥（NULL=开放给所有人）
		WhitelistRoot         sql.NullString `gorm:"column:whitelist_root"`           // 白名单 Merkle Root (hex)
		WhitelistVersion      int64          `gorm:"column:whitelist_version"`        // 白名单版本号
		PythConfidenceTolBps  int64          `gorm:"column:pyth_confidence_tol_bps"`  // Pyth 置信度容忍（bps）
		PythMaxStalenessSlots int64          `gorm:"column:pyth_max_staleness_slots"` // Pyth 最大过期 slots
		FeeBpsLimit           int64          `gorm:"column:fee_bps_limit"`            // 费率上限（bps）
		Paused                int64          `gorm:"column:paused"`                   // 暂停状态: 0=正常 1=暂停
		Network               string         `gorm:"column:network"`                  // 网络: devnet/mainnet
		CreatedAt             time.Time      `gorm:"column:created_at"`               // 创建时间
		UpdatedAt             time.Time      `gorm:"column:updated_at"`               // 更新时间
	}
)

var QLimitOrderConfig LimitOrderConfig

func init() {
	InitField(&QLimitOrderConfig)
}

func (LimitOrderConfig) TableName() string {
	return strings.Trim("`limit_order_config`", "`")
}

func newLimitOrderConfigModel(conn *gorm.DB) *defaultLimitOrderConfigModel {
	return &defaultLimitOrderConfigModel{
		conn:  conn,
		table: strings.Trim("`limit_order_config`", "`"),
	}
}

func (m *defaultLimitOrderConfigModel) Insert(ctx context.Context, data *LimitOrderConfig) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultLimitOrderConfigModel) FindOne(ctx context.Context, id int64) (*LimitOrderConfig, error) {
	var resp LimitOrderConfig
	err := m.conn.WithContext(ctx).Model(&LimitOrderConfig{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err

}

func (m *defaultLimitOrderConfigModel) FindOneByProgramIdNetwork(ctx context.Context, programId string, network string) (*LimitOrderConfig, error) {
	var resp LimitOrderConfig
	err := m.conn.WithContext(ctx).Model(&LimitOrderConfig{}).Where("`program_id` = ? and `network` = ?", programId, network).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultLimitOrderConfigModel) Update(ctx context.Context, data *LimitOrderConfig) error {
	db := m.conn
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultLimitOrderConfigModel) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Where("`id` = @id", sql.Named("id", id)).Delete(&LimitOrderConfig{}).Error

	return err
}
