// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: trade.proto

package trade

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Trade_CreateMarketOrder_FullMethodName      = "/trade.Trade/CreateMarketOrder"
	Trade_CreatePumpToken_FullMethodName        = "/trade.Trade/CreatePumpToken"
	Trade_UploadIpfsFile_FullMethodName         = "/trade.Trade/UploadIpfsFile"
	Trade_UploadTokenMetadata_FullMethodName    = "/trade.Trade/UploadTokenMetadata"
	Trade_ReportPumpCreateResult_FullMethodName = "/trade.Trade/ReportPumpCreateResult"
	Trade_QuotePumpTrade_FullMethodName         = "/trade.Trade/QuotePumpTrade"
	Trade_GetCpmmTokens_FullMethodName          = "/trade.Trade/GetCpmmTokens"
	Trade_GetCpmmFeeTiers_FullMethodName        = "/trade.Trade/GetCpmmFeeTiers"
	Trade_CreateCpmmPool_FullMethodName         = "/trade.Trade/CreateCpmmPool"
	Trade_AddCpmmLiquidity_FullMethodName       = "/trade.Trade/AddCpmmLiquidity"
	Trade_RemoveCpmmLiquidity_FullMethodName    = "/trade.Trade/RemoveCpmmLiquidity"
	Trade_SwapCpmm_FullMethodName               = "/trade.Trade/SwapCpmm"
	Trade_SwapClmm_FullMethodName               = "/trade.Trade/SwapClmm"
	Trade_CreateClmmPool_FullMethodName         = "/trade.Trade/CreateClmmPool"
	Trade_OpenPosition_FullMethodName           = "/trade.Trade/OpenPosition"
	Trade_IncreaseClmmLiquidity_FullMethodName  = "/trade.Trade/IncreaseClmmLiquidity"
	Trade_DecreaseClmmLiquidity_FullMethodName  = "/trade.Trade/DecreaseClmmLiquidity"
	Trade_CreateLimitOrder_FullMethodName       = "/trade.Trade/CreateLimitOrder"
	Trade_CancelLimitOrder_FullMethodName       = "/trade.Trade/CancelLimitOrder"
	Trade_DepositMargin_FullMethodName          = "/trade.Trade/DepositMargin"
	Trade_WithdrawMargin_FullMethodName         = "/trade.Trade/WithdrawMargin"
)

// TradeClient is the client API for Trade service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradeClient interface {
	CreateMarketOrder(ctx context.Context, in *CreateMarketOrderRequest, opts ...grpc.CallOption) (*CreateMarketOrderResponse, error)
	// Create a PumpFun token: backend builds unsigned tx for client signing
	CreatePumpToken(ctx context.Context, in *CreatePumpTokenRequest, opts ...grpc.CallOption) (*CreatePumpTokenResponse, error)
	// IPFS helpers: upload file and token metadata
	UploadIpfsFile(ctx context.Context, in *UploadIpfsFileRequest, opts ...grpc.CallOption) (*UploadIpfsFileResponse, error)
	UploadTokenMetadata(ctx context.Context, in *UploadMetadataRequest, opts ...grpc.CallOption) (*UploadMetadataResponse, error)
	// Frontend reports tx result for Pump create
	ReportPumpCreateResult(ctx context.Context, in *ReportPumpCreateResultRequest, opts ...grpc.CallOption) (*ReportPumpCreateResultResponse, error)
	// Quote Pump buy/sell outcomes for SOL or TOKEN inputs
	QuotePumpTrade(ctx context.Context, in *QuotePumpTradeRequest, opts ...grpc.CallOption) (*QuotePumpTradeResponse, error)
	// Liquidity configuration endpoints
	GetCpmmTokens(ctx context.Context, in *GetCpmmTokensRequest, opts ...grpc.CallOption) (*GetCpmmTokensResponse, error)
	GetCpmmFeeTiers(ctx context.Context, in *GetCpmmFeeTiersRequest, opts ...grpc.CallOption) (*GetCpmmFeeTiersResponse, error)
	CreateCpmmPool(ctx context.Context, in *CreateCpmmPoolRequest, opts ...grpc.CallOption) (*CreateCpmmPoolResponse, error)
	// Build unsigned tx for adding liquidity to CPMM pool
	AddCpmmLiquidity(ctx context.Context, in *AddCpmmLiquidityRequest, opts ...grpc.CallOption) (*AddCpmmLiquidityResponse, error)
	// Build unsigned tx for removing liquidity from CPMM pool
	RemoveCpmmLiquidity(ctx context.Context, in *RemoveCpmmLiquidityRequest, opts ...grpc.CallOption) (*RemoveCpmmLiquidityResponse, error)
	// Build unsigned tx for swapping inside a CPMM pool
	SwapCpmm(ctx context.Context, in *SwapCpmmRequest, opts ...grpc.CallOption) (*SwapCpmmResponse, error)
	// Build unsigned tx for swapping inside a CLMM pool
	SwapClmm(ctx context.Context, in *SwapClmmRequest, opts ...grpc.CallOption) (*SwapClmmResponse, error)
	// Build unsigned tx for creating a CLMM pool
	CreateClmmPool(ctx context.Context, in *CreateClmmPoolRequest, opts ...grpc.CallOption) (*CreateClmmPoolResponse, error)
	// Build unsigned tx for opening a position in CLMM pool
	OpenPosition(ctx context.Context, in *OpenPositionRequest, opts ...grpc.CallOption) (*OpenPositionResponse, error)
	// Build unsigned tx for increasing liquidity in CLMM position
	IncreaseClmmLiquidity(ctx context.Context, in *IncreaseClmmLiquidityRequest, opts ...grpc.CallOption) (*IncreaseClmmLiquidityResponse, error)
	// Build unsigned tx for decreasing liquidity in CLMM position
	DecreaseClmmLiquidity(ctx context.Context, in *DecreaseClmmLiquidityRequest, opts ...grpc.CallOption) (*DecreaseClmmLiquidityResponse, error)
	// Limit order operations
	CreateLimitOrder(ctx context.Context, in *CreateLimitOrderRequest, opts ...grpc.CallOption) (*CreateLimitOrderResponse, error)
	CancelLimitOrder(ctx context.Context, in *CancelLimitOrderRequest, opts ...grpc.CallOption) (*CancelLimitOrderResponse, error)
	DepositMargin(ctx context.Context, in *DepositMarginRequest, opts ...grpc.CallOption) (*DepositMarginResponse, error)
	WithdrawMargin(ctx context.Context, in *WithdrawMarginRequest, opts ...grpc.CallOption) (*WithdrawMarginResponse, error)
}

type tradeClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeClient(cc grpc.ClientConnInterface) TradeClient {
	return &tradeClient{cc}
}

func (c *tradeClient) CreateMarketOrder(ctx context.Context, in *CreateMarketOrderRequest, opts ...grpc.CallOption) (*CreateMarketOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMarketOrderResponse)
	err := c.cc.Invoke(ctx, Trade_CreateMarketOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) CreatePumpToken(ctx context.Context, in *CreatePumpTokenRequest, opts ...grpc.CallOption) (*CreatePumpTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePumpTokenResponse)
	err := c.cc.Invoke(ctx, Trade_CreatePumpToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) UploadIpfsFile(ctx context.Context, in *UploadIpfsFileRequest, opts ...grpc.CallOption) (*UploadIpfsFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadIpfsFileResponse)
	err := c.cc.Invoke(ctx, Trade_UploadIpfsFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) UploadTokenMetadata(ctx context.Context, in *UploadMetadataRequest, opts ...grpc.CallOption) (*UploadMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadMetadataResponse)
	err := c.cc.Invoke(ctx, Trade_UploadTokenMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) ReportPumpCreateResult(ctx context.Context, in *ReportPumpCreateResultRequest, opts ...grpc.CallOption) (*ReportPumpCreateResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportPumpCreateResultResponse)
	err := c.cc.Invoke(ctx, Trade_ReportPumpCreateResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) QuotePumpTrade(ctx context.Context, in *QuotePumpTradeRequest, opts ...grpc.CallOption) (*QuotePumpTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuotePumpTradeResponse)
	err := c.cc.Invoke(ctx, Trade_QuotePumpTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) GetCpmmTokens(ctx context.Context, in *GetCpmmTokensRequest, opts ...grpc.CallOption) (*GetCpmmTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCpmmTokensResponse)
	err := c.cc.Invoke(ctx, Trade_GetCpmmTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) GetCpmmFeeTiers(ctx context.Context, in *GetCpmmFeeTiersRequest, opts ...grpc.CallOption) (*GetCpmmFeeTiersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCpmmFeeTiersResponse)
	err := c.cc.Invoke(ctx, Trade_GetCpmmFeeTiers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) CreateCpmmPool(ctx context.Context, in *CreateCpmmPoolRequest, opts ...grpc.CallOption) (*CreateCpmmPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCpmmPoolResponse)
	err := c.cc.Invoke(ctx, Trade_CreateCpmmPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) AddCpmmLiquidity(ctx context.Context, in *AddCpmmLiquidityRequest, opts ...grpc.CallOption) (*AddCpmmLiquidityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCpmmLiquidityResponse)
	err := c.cc.Invoke(ctx, Trade_AddCpmmLiquidity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) RemoveCpmmLiquidity(ctx context.Context, in *RemoveCpmmLiquidityRequest, opts ...grpc.CallOption) (*RemoveCpmmLiquidityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveCpmmLiquidityResponse)
	err := c.cc.Invoke(ctx, Trade_RemoveCpmmLiquidity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) SwapCpmm(ctx context.Context, in *SwapCpmmRequest, opts ...grpc.CallOption) (*SwapCpmmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwapCpmmResponse)
	err := c.cc.Invoke(ctx, Trade_SwapCpmm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) SwapClmm(ctx context.Context, in *SwapClmmRequest, opts ...grpc.CallOption) (*SwapClmmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwapClmmResponse)
	err := c.cc.Invoke(ctx, Trade_SwapClmm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) CreateClmmPool(ctx context.Context, in *CreateClmmPoolRequest, opts ...grpc.CallOption) (*CreateClmmPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateClmmPoolResponse)
	err := c.cc.Invoke(ctx, Trade_CreateClmmPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) OpenPosition(ctx context.Context, in *OpenPositionRequest, opts ...grpc.CallOption) (*OpenPositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenPositionResponse)
	err := c.cc.Invoke(ctx, Trade_OpenPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) IncreaseClmmLiquidity(ctx context.Context, in *IncreaseClmmLiquidityRequest, opts ...grpc.CallOption) (*IncreaseClmmLiquidityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncreaseClmmLiquidityResponse)
	err := c.cc.Invoke(ctx, Trade_IncreaseClmmLiquidity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) DecreaseClmmLiquidity(ctx context.Context, in *DecreaseClmmLiquidityRequest, opts ...grpc.CallOption) (*DecreaseClmmLiquidityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecreaseClmmLiquidityResponse)
	err := c.cc.Invoke(ctx, Trade_DecreaseClmmLiquidity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) CreateLimitOrder(ctx context.Context, in *CreateLimitOrderRequest, opts ...grpc.CallOption) (*CreateLimitOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLimitOrderResponse)
	err := c.cc.Invoke(ctx, Trade_CreateLimitOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) CancelLimitOrder(ctx context.Context, in *CancelLimitOrderRequest, opts ...grpc.CallOption) (*CancelLimitOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelLimitOrderResponse)
	err := c.cc.Invoke(ctx, Trade_CancelLimitOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) DepositMargin(ctx context.Context, in *DepositMarginRequest, opts ...grpc.CallOption) (*DepositMarginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepositMarginResponse)
	err := c.cc.Invoke(ctx, Trade_DepositMargin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) WithdrawMargin(ctx context.Context, in *WithdrawMarginRequest, opts ...grpc.CallOption) (*WithdrawMarginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawMarginResponse)
	err := c.cc.Invoke(ctx, Trade_WithdrawMargin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeServer is the server API for Trade service.
// All implementations must embed UnimplementedTradeServer
// for forward compatibility.
type TradeServer interface {
	CreateMarketOrder(context.Context, *CreateMarketOrderRequest) (*CreateMarketOrderResponse, error)
	// Create a PumpFun token: backend builds unsigned tx for client signing
	CreatePumpToken(context.Context, *CreatePumpTokenRequest) (*CreatePumpTokenResponse, error)
	// IPFS helpers: upload file and token metadata
	UploadIpfsFile(context.Context, *UploadIpfsFileRequest) (*UploadIpfsFileResponse, error)
	UploadTokenMetadata(context.Context, *UploadMetadataRequest) (*UploadMetadataResponse, error)
	// Frontend reports tx result for Pump create
	ReportPumpCreateResult(context.Context, *ReportPumpCreateResultRequest) (*ReportPumpCreateResultResponse, error)
	// Quote Pump buy/sell outcomes for SOL or TOKEN inputs
	QuotePumpTrade(context.Context, *QuotePumpTradeRequest) (*QuotePumpTradeResponse, error)
	// Liquidity configuration endpoints
	GetCpmmTokens(context.Context, *GetCpmmTokensRequest) (*GetCpmmTokensResponse, error)
	GetCpmmFeeTiers(context.Context, *GetCpmmFeeTiersRequest) (*GetCpmmFeeTiersResponse, error)
	CreateCpmmPool(context.Context, *CreateCpmmPoolRequest) (*CreateCpmmPoolResponse, error)
	// Build unsigned tx for adding liquidity to CPMM pool
	AddCpmmLiquidity(context.Context, *AddCpmmLiquidityRequest) (*AddCpmmLiquidityResponse, error)
	// Build unsigned tx for removing liquidity from CPMM pool
	RemoveCpmmLiquidity(context.Context, *RemoveCpmmLiquidityRequest) (*RemoveCpmmLiquidityResponse, error)
	// Build unsigned tx for swapping inside a CPMM pool
	SwapCpmm(context.Context, *SwapCpmmRequest) (*SwapCpmmResponse, error)
	// Build unsigned tx for swapping inside a CLMM pool
	SwapClmm(context.Context, *SwapClmmRequest) (*SwapClmmResponse, error)
	// Build unsigned tx for creating a CLMM pool
	CreateClmmPool(context.Context, *CreateClmmPoolRequest) (*CreateClmmPoolResponse, error)
	// Build unsigned tx for opening a position in CLMM pool
	OpenPosition(context.Context, *OpenPositionRequest) (*OpenPositionResponse, error)
	// Build unsigned tx for increasing liquidity in CLMM position
	IncreaseClmmLiquidity(context.Context, *IncreaseClmmLiquidityRequest) (*IncreaseClmmLiquidityResponse, error)
	// Build unsigned tx for decreasing liquidity in CLMM position
	DecreaseClmmLiquidity(context.Context, *DecreaseClmmLiquidityRequest) (*DecreaseClmmLiquidityResponse, error)
	// Limit order operations
	CreateLimitOrder(context.Context, *CreateLimitOrderRequest) (*CreateLimitOrderResponse, error)
	CancelLimitOrder(context.Context, *CancelLimitOrderRequest) (*CancelLimitOrderResponse, error)
	DepositMargin(context.Context, *DepositMarginRequest) (*DepositMarginResponse, error)
	WithdrawMargin(context.Context, *WithdrawMarginRequest) (*WithdrawMarginResponse, error)
	mustEmbedUnimplementedTradeServer()
}

// UnimplementedTradeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTradeServer struct{}

func (UnimplementedTradeServer) CreateMarketOrder(context.Context, *CreateMarketOrderRequest) (*CreateMarketOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMarketOrder not implemented")
}
func (UnimplementedTradeServer) CreatePumpToken(context.Context, *CreatePumpTokenRequest) (*CreatePumpTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePumpToken not implemented")
}
func (UnimplementedTradeServer) UploadIpfsFile(context.Context, *UploadIpfsFileRequest) (*UploadIpfsFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadIpfsFile not implemented")
}
func (UnimplementedTradeServer) UploadTokenMetadata(context.Context, *UploadMetadataRequest) (*UploadMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadTokenMetadata not implemented")
}
func (UnimplementedTradeServer) ReportPumpCreateResult(context.Context, *ReportPumpCreateResultRequest) (*ReportPumpCreateResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportPumpCreateResult not implemented")
}
func (UnimplementedTradeServer) QuotePumpTrade(context.Context, *QuotePumpTradeRequest) (*QuotePumpTradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QuotePumpTrade not implemented")
}
func (UnimplementedTradeServer) GetCpmmTokens(context.Context, *GetCpmmTokensRequest) (*GetCpmmTokensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCpmmTokens not implemented")
}
func (UnimplementedTradeServer) GetCpmmFeeTiers(context.Context, *GetCpmmFeeTiersRequest) (*GetCpmmFeeTiersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCpmmFeeTiers not implemented")
}
func (UnimplementedTradeServer) CreateCpmmPool(context.Context, *CreateCpmmPoolRequest) (*CreateCpmmPoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCpmmPool not implemented")
}
func (UnimplementedTradeServer) AddCpmmLiquidity(context.Context, *AddCpmmLiquidityRequest) (*AddCpmmLiquidityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCpmmLiquidity not implemented")
}
func (UnimplementedTradeServer) RemoveCpmmLiquidity(context.Context, *RemoveCpmmLiquidityRequest) (*RemoveCpmmLiquidityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveCpmmLiquidity not implemented")
}
func (UnimplementedTradeServer) SwapCpmm(context.Context, *SwapCpmmRequest) (*SwapCpmmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SwapCpmm not implemented")
}
func (UnimplementedTradeServer) SwapClmm(context.Context, *SwapClmmRequest) (*SwapClmmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SwapClmm not implemented")
}
func (UnimplementedTradeServer) CreateClmmPool(context.Context, *CreateClmmPoolRequest) (*CreateClmmPoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateClmmPool not implemented")
}
func (UnimplementedTradeServer) OpenPosition(context.Context, *OpenPositionRequest) (*OpenPositionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenPosition not implemented")
}
func (UnimplementedTradeServer) IncreaseClmmLiquidity(context.Context, *IncreaseClmmLiquidityRequest) (*IncreaseClmmLiquidityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IncreaseClmmLiquidity not implemented")
}
func (UnimplementedTradeServer) DecreaseClmmLiquidity(context.Context, *DecreaseClmmLiquidityRequest) (*DecreaseClmmLiquidityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecreaseClmmLiquidity not implemented")
}
func (UnimplementedTradeServer) CreateLimitOrder(context.Context, *CreateLimitOrderRequest) (*CreateLimitOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLimitOrder not implemented")
}
func (UnimplementedTradeServer) CancelLimitOrder(context.Context, *CancelLimitOrderRequest) (*CancelLimitOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelLimitOrder not implemented")
}
func (UnimplementedTradeServer) DepositMargin(context.Context, *DepositMarginRequest) (*DepositMarginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DepositMargin not implemented")
}
func (UnimplementedTradeServer) WithdrawMargin(context.Context, *WithdrawMarginRequest) (*WithdrawMarginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WithdrawMargin not implemented")
}
func (UnimplementedTradeServer) mustEmbedUnimplementedTradeServer() {}
func (UnimplementedTradeServer) testEmbeddedByValue()               {}

// UnsafeTradeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeServer will
// result in compilation errors.
type UnsafeTradeServer interface {
	mustEmbedUnimplementedTradeServer()
}

func RegisterTradeServer(s grpc.ServiceRegistrar, srv TradeServer) {
	// If the following call panics, it indicates UnimplementedTradeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Trade_ServiceDesc, srv)
}

func _Trade_CreateMarketOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMarketOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).CreateMarketOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_CreateMarketOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).CreateMarketOrder(ctx, req.(*CreateMarketOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_CreatePumpToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePumpTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).CreatePumpToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_CreatePumpToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).CreatePumpToken(ctx, req.(*CreatePumpTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_UploadIpfsFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadIpfsFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).UploadIpfsFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_UploadIpfsFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).UploadIpfsFile(ctx, req.(*UploadIpfsFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_UploadTokenMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).UploadTokenMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_UploadTokenMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).UploadTokenMetadata(ctx, req.(*UploadMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_ReportPumpCreateResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportPumpCreateResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).ReportPumpCreateResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_ReportPumpCreateResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).ReportPumpCreateResult(ctx, req.(*ReportPumpCreateResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_QuotePumpTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuotePumpTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).QuotePumpTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_QuotePumpTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).QuotePumpTrade(ctx, req.(*QuotePumpTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_GetCpmmTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCpmmTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).GetCpmmTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_GetCpmmTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).GetCpmmTokens(ctx, req.(*GetCpmmTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_GetCpmmFeeTiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCpmmFeeTiersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).GetCpmmFeeTiers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_GetCpmmFeeTiers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).GetCpmmFeeTiers(ctx, req.(*GetCpmmFeeTiersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_CreateCpmmPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCpmmPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).CreateCpmmPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_CreateCpmmPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).CreateCpmmPool(ctx, req.(*CreateCpmmPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_AddCpmmLiquidity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCpmmLiquidityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).AddCpmmLiquidity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_AddCpmmLiquidity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).AddCpmmLiquidity(ctx, req.(*AddCpmmLiquidityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_RemoveCpmmLiquidity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCpmmLiquidityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).RemoveCpmmLiquidity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_RemoveCpmmLiquidity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).RemoveCpmmLiquidity(ctx, req.(*RemoveCpmmLiquidityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_SwapCpmm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwapCpmmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).SwapCpmm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_SwapCpmm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).SwapCpmm(ctx, req.(*SwapCpmmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_SwapClmm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwapClmmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).SwapClmm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_SwapClmm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).SwapClmm(ctx, req.(*SwapClmmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_CreateClmmPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClmmPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).CreateClmmPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_CreateClmmPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).CreateClmmPool(ctx, req.(*CreateClmmPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_OpenPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).OpenPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_OpenPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).OpenPosition(ctx, req.(*OpenPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_IncreaseClmmLiquidity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncreaseClmmLiquidityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).IncreaseClmmLiquidity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_IncreaseClmmLiquidity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).IncreaseClmmLiquidity(ctx, req.(*IncreaseClmmLiquidityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_DecreaseClmmLiquidity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecreaseClmmLiquidityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).DecreaseClmmLiquidity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_DecreaseClmmLiquidity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).DecreaseClmmLiquidity(ctx, req.(*DecreaseClmmLiquidityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_CreateLimitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLimitOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).CreateLimitOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_CreateLimitOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).CreateLimitOrder(ctx, req.(*CreateLimitOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_CancelLimitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelLimitOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).CancelLimitOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_CancelLimitOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).CancelLimitOrder(ctx, req.(*CancelLimitOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_DepositMargin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositMarginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).DepositMargin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_DepositMargin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).DepositMargin(ctx, req.(*DepositMarginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_WithdrawMargin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawMarginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).WithdrawMargin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_WithdrawMargin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).WithdrawMargin(ctx, req.(*WithdrawMarginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Trade_ServiceDesc is the grpc.ServiceDesc for Trade service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Trade_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trade.Trade",
	HandlerType: (*TradeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMarketOrder",
			Handler:    _Trade_CreateMarketOrder_Handler,
		},
		{
			MethodName: "CreatePumpToken",
			Handler:    _Trade_CreatePumpToken_Handler,
		},
		{
			MethodName: "UploadIpfsFile",
			Handler:    _Trade_UploadIpfsFile_Handler,
		},
		{
			MethodName: "UploadTokenMetadata",
			Handler:    _Trade_UploadTokenMetadata_Handler,
		},
		{
			MethodName: "ReportPumpCreateResult",
			Handler:    _Trade_ReportPumpCreateResult_Handler,
		},
		{
			MethodName: "QuotePumpTrade",
			Handler:    _Trade_QuotePumpTrade_Handler,
		},
		{
			MethodName: "GetCpmmTokens",
			Handler:    _Trade_GetCpmmTokens_Handler,
		},
		{
			MethodName: "GetCpmmFeeTiers",
			Handler:    _Trade_GetCpmmFeeTiers_Handler,
		},
		{
			MethodName: "CreateCpmmPool",
			Handler:    _Trade_CreateCpmmPool_Handler,
		},
		{
			MethodName: "AddCpmmLiquidity",
			Handler:    _Trade_AddCpmmLiquidity_Handler,
		},
		{
			MethodName: "RemoveCpmmLiquidity",
			Handler:    _Trade_RemoveCpmmLiquidity_Handler,
		},
		{
			MethodName: "SwapCpmm",
			Handler:    _Trade_SwapCpmm_Handler,
		},
		{
			MethodName: "SwapClmm",
			Handler:    _Trade_SwapClmm_Handler,
		},
		{
			MethodName: "CreateClmmPool",
			Handler:    _Trade_CreateClmmPool_Handler,
		},
		{
			MethodName: "OpenPosition",
			Handler:    _Trade_OpenPosition_Handler,
		},
		{
			MethodName: "IncreaseClmmLiquidity",
			Handler:    _Trade_IncreaseClmmLiquidity_Handler,
		},
		{
			MethodName: "DecreaseClmmLiquidity",
			Handler:    _Trade_DecreaseClmmLiquidity_Handler,
		},
		{
			MethodName: "CreateLimitOrder",
			Handler:    _Trade_CreateLimitOrder_Handler,
		},
		{
			MethodName: "CancelLimitOrder",
			Handler:    _Trade_CancelLimitOrder_Handler,
		},
		{
			MethodName: "DepositMargin",
			Handler:    _Trade_DepositMargin_Handler,
		},
		{
			MethodName: "WithdrawMargin",
			Handler:    _Trade_WithdrawMargin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trade.proto",
}
