// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: trade.proto

package tradeclient

import (
	"context"

	"richcode.cc/dex/trade/trade"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCpmmLiquidityRequest        = trade.AddCpmmLiquidityRequest
	AddCpmmLiquidityResponse       = trade.AddCpmmLiquidityResponse
	CpmmFeeTierItem                = trade.CpmmFeeTierItem
	CpmmTokenItem                  = trade.CpmmTokenItem
	CreateClmmPoolRequest          = trade.CreateClmmPoolRequest
	CreateClmmPoolResponse         = trade.CreateClmmPoolResponse
	CreateCpmmPoolRequest          = trade.CreateCpmmPoolRequest
	CreateCpmmPoolResponse         = trade.CreateCpmmPoolResponse
	CreateMarketOrderRequest       = trade.CreateMarketOrderRequest
	CreateMarketOrderResponse      = trade.CreateMarketOrderResponse
	CreatePumpTokenRequest         = trade.CreatePumpTokenRequest
	CreatePumpTokenResponse        = trade.CreatePumpTokenResponse
	DecreaseClmmLiquidityRequest   = trade.DecreaseClmmLiquidityRequest
	DecreaseClmmLiquidityResponse  = trade.DecreaseClmmLiquidityResponse
	GetCpmmFeeTiersRequest         = trade.GetCpmmFeeTiersRequest
	GetCpmmFeeTiersResponse        = trade.GetCpmmFeeTiersResponse
	GetCpmmTokensRequest           = trade.GetCpmmTokensRequest
	GetCpmmTokensResponse          = trade.GetCpmmTokensResponse
	IncreaseClmmLiquidityRequest   = trade.IncreaseClmmLiquidityRequest
	IncreaseClmmLiquidityResponse  = trade.IncreaseClmmLiquidityResponse
	OpenPositionRequest            = trade.OpenPositionRequest
	OpenPositionResponse           = trade.OpenPositionResponse
	QuotePumpTradeRequest          = trade.QuotePumpTradeRequest
	QuotePumpTradeResponse         = trade.QuotePumpTradeResponse
	RemoveCpmmLiquidityRequest     = trade.RemoveCpmmLiquidityRequest
	RemoveCpmmLiquidityResponse    = trade.RemoveCpmmLiquidityResponse
	ReportPumpCreateResultRequest  = trade.ReportPumpCreateResultRequest
	ReportPumpCreateResultResponse = trade.ReportPumpCreateResultResponse
	SwapClmmRequest                = trade.SwapClmmRequest
	SwapClmmResponse               = trade.SwapClmmResponse
	SwapCpmmRequest                = trade.SwapCpmmRequest
	SwapCpmmResponse               = trade.SwapCpmmResponse
	UploadIpfsFileRequest          = trade.UploadIpfsFileRequest
	UploadIpfsFileResponse         = trade.UploadIpfsFileResponse
	UploadMetadataRequest          = trade.UploadMetadataRequest
	UploadMetadataResponse         = trade.UploadMetadataResponse

	Trade interface {
		CreateMarketOrder(ctx context.Context, in *CreateMarketOrderRequest, opts ...grpc.CallOption) (*CreateMarketOrderResponse, error)
		// Create a PumpFun token: backend builds unsigned tx for client signing
		CreatePumpToken(ctx context.Context, in *CreatePumpTokenRequest, opts ...grpc.CallOption) (*CreatePumpTokenResponse, error)
		// IPFS helpers: upload file and token metadata
		UploadIpfsFile(ctx context.Context, in *UploadIpfsFileRequest, opts ...grpc.CallOption) (*UploadIpfsFileResponse, error)
		UploadTokenMetadata(ctx context.Context, in *UploadMetadataRequest, opts ...grpc.CallOption) (*UploadMetadataResponse, error)
		// Frontend reports tx result for Pump create
		ReportPumpCreateResult(ctx context.Context, in *ReportPumpCreateResultRequest, opts ...grpc.CallOption) (*ReportPumpCreateResultResponse, error)
		// Quote Pump buy/sell outcomes for SOL or TOKEN inputs
		QuotePumpTrade(ctx context.Context, in *QuotePumpTradeRequest, opts ...grpc.CallOption) (*QuotePumpTradeResponse, error)
		// Liquidity configuration endpoints
		GetCpmmTokens(ctx context.Context, in *GetCpmmTokensRequest, opts ...grpc.CallOption) (*GetCpmmTokensResponse, error)
		GetCpmmFeeTiers(ctx context.Context, in *GetCpmmFeeTiersRequest, opts ...grpc.CallOption) (*GetCpmmFeeTiersResponse, error)
		CreateCpmmPool(ctx context.Context, in *CreateCpmmPoolRequest, opts ...grpc.CallOption) (*CreateCpmmPoolResponse, error)
		// Build unsigned tx for adding liquidity to CPMM pool
		AddCpmmLiquidity(ctx context.Context, in *AddCpmmLiquidityRequest, opts ...grpc.CallOption) (*AddCpmmLiquidityResponse, error)
		// Build unsigned tx for removing liquidity from CPMM pool
		RemoveCpmmLiquidity(ctx context.Context, in *RemoveCpmmLiquidityRequest, opts ...grpc.CallOption) (*RemoveCpmmLiquidityResponse, error)
		// Build unsigned tx for swapping inside a CPMM pool
		SwapCpmm(ctx context.Context, in *SwapCpmmRequest, opts ...grpc.CallOption) (*SwapCpmmResponse, error)
		// Build unsigned tx for swapping inside a CLMM pool
		SwapClmm(ctx context.Context, in *SwapClmmRequest, opts ...grpc.CallOption) (*SwapClmmResponse, error)
		// Build unsigned tx for creating a CLMM pool
		CreateClmmPool(ctx context.Context, in *CreateClmmPoolRequest, opts ...grpc.CallOption) (*CreateClmmPoolResponse, error)
		// Build unsigned tx for opening a position in CLMM pool
		OpenPosition(ctx context.Context, in *OpenPositionRequest, opts ...grpc.CallOption) (*OpenPositionResponse, error)
		// Build unsigned tx for increasing liquidity in CLMM position
		IncreaseClmmLiquidity(ctx context.Context, in *IncreaseClmmLiquidityRequest, opts ...grpc.CallOption) (*IncreaseClmmLiquidityResponse, error)
		// Build unsigned tx for decreasing liquidity in CLMM position
		DecreaseClmmLiquidity(ctx context.Context, in *DecreaseClmmLiquidityRequest, opts ...grpc.CallOption) (*DecreaseClmmLiquidityResponse, error)
	}

	defaultTrade struct {
		cli zrpc.Client
	}
)

func NewTrade(cli zrpc.Client) Trade {
	return &defaultTrade{
		cli: cli,
	}
}

func (m *defaultTrade) CreateMarketOrder(ctx context.Context, in *CreateMarketOrderRequest, opts ...grpc.CallOption) (*CreateMarketOrderResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.CreateMarketOrder(ctx, in, opts...)
}

// Create a PumpFun token: backend builds unsigned tx for client signing
func (m *defaultTrade) CreatePumpToken(ctx context.Context, in *CreatePumpTokenRequest, opts ...grpc.CallOption) (*CreatePumpTokenResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.CreatePumpToken(ctx, in, opts...)
}

// IPFS helpers: upload file and token metadata
func (m *defaultTrade) UploadIpfsFile(ctx context.Context, in *UploadIpfsFileRequest, opts ...grpc.CallOption) (*UploadIpfsFileResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.UploadIpfsFile(ctx, in, opts...)
}

func (m *defaultTrade) UploadTokenMetadata(ctx context.Context, in *UploadMetadataRequest, opts ...grpc.CallOption) (*UploadMetadataResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.UploadTokenMetadata(ctx, in, opts...)
}

// Frontend reports tx result for Pump create
func (m *defaultTrade) ReportPumpCreateResult(ctx context.Context, in *ReportPumpCreateResultRequest, opts ...grpc.CallOption) (*ReportPumpCreateResultResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.ReportPumpCreateResult(ctx, in, opts...)
}

// Quote Pump buy/sell outcomes for SOL or TOKEN inputs
func (m *defaultTrade) QuotePumpTrade(ctx context.Context, in *QuotePumpTradeRequest, opts ...grpc.CallOption) (*QuotePumpTradeResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.QuotePumpTrade(ctx, in, opts...)
}

// Liquidity configuration endpoints
func (m *defaultTrade) GetCpmmTokens(ctx context.Context, in *GetCpmmTokensRequest, opts ...grpc.CallOption) (*GetCpmmTokensResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.GetCpmmTokens(ctx, in, opts...)
}

func (m *defaultTrade) GetCpmmFeeTiers(ctx context.Context, in *GetCpmmFeeTiersRequest, opts ...grpc.CallOption) (*GetCpmmFeeTiersResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.GetCpmmFeeTiers(ctx, in, opts...)
}

func (m *defaultTrade) CreateCpmmPool(ctx context.Context, in *CreateCpmmPoolRequest, opts ...grpc.CallOption) (*CreateCpmmPoolResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.CreateCpmmPool(ctx, in, opts...)
}

// Build unsigned tx for adding liquidity to CPMM pool
func (m *defaultTrade) AddCpmmLiquidity(ctx context.Context, in *AddCpmmLiquidityRequest, opts ...grpc.CallOption) (*AddCpmmLiquidityResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.AddCpmmLiquidity(ctx, in, opts...)
}

// Build unsigned tx for removing liquidity from CPMM pool
func (m *defaultTrade) RemoveCpmmLiquidity(ctx context.Context, in *RemoveCpmmLiquidityRequest, opts ...grpc.CallOption) (*RemoveCpmmLiquidityResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.RemoveCpmmLiquidity(ctx, in, opts...)
}

// Build unsigned tx for swapping inside a CPMM pool
func (m *defaultTrade) SwapCpmm(ctx context.Context, in *SwapCpmmRequest, opts ...grpc.CallOption) (*SwapCpmmResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.SwapCpmm(ctx, in, opts...)
}

// Build unsigned tx for swapping inside a CLMM pool
func (m *defaultTrade) SwapClmm(ctx context.Context, in *SwapClmmRequest, opts ...grpc.CallOption) (*SwapClmmResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.SwapClmm(ctx, in, opts...)
}

// Build unsigned tx for creating a CLMM pool
func (m *defaultTrade) CreateClmmPool(ctx context.Context, in *CreateClmmPoolRequest, opts ...grpc.CallOption) (*CreateClmmPoolResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.CreateClmmPool(ctx, in, opts...)
}

// Build unsigned tx for opening a position in CLMM pool
func (m *defaultTrade) OpenPosition(ctx context.Context, in *OpenPositionRequest, opts ...grpc.CallOption) (*OpenPositionResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.OpenPosition(ctx, in, opts...)
}

// Build unsigned tx for increasing liquidity in CLMM position
func (m *defaultTrade) IncreaseClmmLiquidity(ctx context.Context, in *IncreaseClmmLiquidityRequest, opts ...grpc.CallOption) (*IncreaseClmmLiquidityResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.IncreaseClmmLiquidity(ctx, in, opts...)
}

// Build unsigned tx for decreasing liquidity in CLMM position
func (m *defaultTrade) DecreaseClmmLiquidity(ctx context.Context, in *DecreaseClmmLiquidityRequest, opts ...grpc.CallOption) (*DecreaseClmmLiquidityResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.DecreaseClmmLiquidity(ctx, in, opts...)
}
