// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: limitorder.proto

package server

import (
	"context"

	"richcode.cc/dex/limitorder/internal/logic"
	"richcode.cc/dex/limitorder/internal/svc"
	"richcode.cc/dex/limitorder/limitorder"
)

type LimitOrderServer struct {
	svcCtx *svc.ServiceContext
	limitorder.UnimplementedLimitOrderServer
}

func NewLimitOrderServer(svcCtx *svc.ServiceContext) *LimitOrderServer {
	return &LimitOrderServer{
		svcCtx: svcCtx,
	}
}

// ????????
func (s *LimitOrderServer) InitializeMarginAccount(ctx context.Context, in *limitorder.InitializeMarginAccountRequest) (*limitorder.InitializeMarginAccountResponse, error) {
	l := logic.NewInitializeMarginAccountLogic(ctx, s.svcCtx)
	return l.InitializeMarginAccount(in)
}

// ???????????????????????????
func (s *LimitOrderServer) SyncMarginAccountStatus(ctx context.Context, in *limitorder.SyncMarginAccountStatusRequest) (*limitorder.SyncMarginAccountStatusResponse, error) {
	l := logic.NewSyncMarginAccountStatusLogic(ctx, s.svcCtx)
	return l.SyncMarginAccountStatus(in)
}

// ???????
func (s *LimitOrderServer) CreateMarket(ctx context.Context, in *limitorder.CreateMarketRequest) (*limitorder.CreateMarketResponse, error) {
	l := logic.NewCreateMarketLogic(ctx, s.svcCtx)
	return l.CreateMarket(in)
}

// ??????
func (s *LimitOrderServer) SyncMarketStatus(ctx context.Context, in *limitorder.SyncMarketStatusRequest) (*limitorder.SyncMarketStatusResponse, error) {
	l := logic.NewSyncMarketStatusLogic(ctx, s.svcCtx)
	return l.SyncMarketStatus(in)
}
