// Code generated by goctl. DO NOT EDIT!

package solmodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
)

// avoid unused err
var _ = time.Second

type (
	clmmPositionModel interface {
		Insert(ctx context.Context, data *ClmmPosition) error

		FindOne(ctx context.Context, id int64) (*ClmmPosition, error)
		FindOneByPositionNftMint(ctx context.Context, positionNftMint string) (*ClmmPosition, error)
		FindByUserWallet(ctx context.Context, userWalletAddress string) ([]*ClmmPosition, error)
		FindByUserWalletAndPool(ctx context.Context, userWalletAddress, poolState string) ([]*ClmmPosition, error)
		Update(ctx context.Context, data *ClmmPosition) error

		Delete(ctx context.Context, id int64) error
	}

	defaultClmmPositionModel struct {
		conn  *gorm.DB
		table string
	}

	ClmmPosition struct {
		Id                      int64        `gorm:"column:id"`                        // 主键ID
		ChainId                 int64        `gorm:"column:chain_id"`                  // 链 ID
		UserWalletAddress       string       `gorm:"column:user_wallet_address"`        // 用户钱包地址
		PoolState               string       `gorm:"column:pool_state"`                 // 池子状态地址
		PositionNftMint         string       `gorm:"column:position_nft_mint"`          // 持仓 NFT Mint 地址
		PositionNftAccount     string       `gorm:"column:position_nft_account"`        // 持仓 NFT 账户地址
		PersonalPosition       string       `gorm:"column:personal_position"`         // 个人持仓状态账户
		TickLowerIndex          int32        `gorm:"column:tick_lower_index"`           // 价格下限 Tick 索引
		TickUpperIndex          int32        `gorm:"column:tick_upper_index"`         // 价格上限 Tick 索引
		TickArrayLowerStartIndex int32        `gorm:"column:tick_array_lower_start_index"` // 下限 Tick 数组起始索引
		TickArrayUpperStartIndex int32        `gorm:"column:tick_array_upper_start_index"` // 上限 Tick 数组起始索引
		Liquidity               string       `gorm:"column:liquidity"`                 // 流动性数量（Uint128）
		Amount0Max              int64        `gorm:"column:amount_0_max"`              // Token0 最大数量
		Amount1Max              int64        `gorm:"column:amount_1_max"`              // Token1 最大数量
		TokenAccount0           string       `gorm:"column:token_account_0"`           // Token0 账户地址
		TokenAccount1           string       `gorm:"column:token_account_1"`           // Token1 账户地址
		TokenVault0              string       `gorm:"column:token_vault_0"`            // Token0 资金库地址
		TokenVault1              string       `gorm:"column:token_vault_1"`             // Token1 资金库地址
		TxHash                  string       `gorm:"column:tx_hash"`                  // 交易哈希
		Slot                    int64        `gorm:"column:slot"`                     // 区块 Slot
		BlockTime               time.Time    `gorm:"column:block_time"`                // 区块时间
		BlockTimeStamp          int64        `gorm:"column:block_time_stamp"`         // 区块时间戳
		PositionValueUsd        float64      `gorm:"column:position_value_usd"`       // 持仓总价值（USD）
		UnclaimedFees0           int64        `gorm:"column:unclaimed_fees_0"`          // 未提取手续费 Token0（原子单位）
		UnclaimedFees1           int64        `gorm:"column:unclaimed_fees_1"`          // 未提取手续费 Token1（原子单位）
		UnclaimedFeesUsd         float64      `gorm:"column:unclaimed_fees_usd"`        // 未提取手续费总价值（USD）
		Token0Amount              float64      `gorm:"column:token0_amount"`              // Token0 数量（已考虑 decimals）
		Token1Amount              float64      `gorm:"column:token1_amount"`              // Token1 数量（已考虑 decimals）
		CreatedAt               time.Time    `gorm:"column:created_at"`                // 创建时间
		UpdatedAt               time.Time    `gorm:"column:updated_at"`                // 更新时间
		DeletedAt               sql.NullTime `gorm:"column:deleted_at;index"`         // 删除时间
	}
)

var QClmmPosition ClmmPosition

func init() {
	InitField(&QClmmPosition)
}

func (ClmmPosition) TableName() string {
	return strings.Trim("`clmm_position`", "`")
}

func newClmmPositionModel(conn *gorm.DB) *defaultClmmPositionModel {
	return &defaultClmmPositionModel{
		conn:  conn,
		table: strings.Trim("`clmm_position`", "`"),
	}
}

func (m *defaultClmmPositionModel) Insert(ctx context.Context, data *ClmmPosition) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultClmmPositionModel) FindOne(ctx context.Context, id int64) (*ClmmPosition, error) {
	var resp ClmmPosition
	err := m.conn.WithContext(ctx).Model(&ClmmPosition{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultClmmPositionModel) FindOneByPositionNftMint(ctx context.Context, positionNftMint string) (*ClmmPosition, error) {
	var resp ClmmPosition
	err := m.conn.WithContext(ctx).Model(&ClmmPosition{}).Where("`position_nft_mint` = ?", positionNftMint).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultClmmPositionModel) FindByUserWallet(ctx context.Context, userWalletAddress string) ([]*ClmmPosition, error) {
	var resp []*ClmmPosition
	err := m.conn.WithContext(ctx).Model(&ClmmPosition{}).Where("`user_wallet_address` = ? AND `deleted_at` IS NULL", userWalletAddress).Find(&resp).Error
	return resp, err
}

func (m *defaultClmmPositionModel) FindByUserWalletAndPool(ctx context.Context, userWalletAddress, poolState string) ([]*ClmmPosition, error) {
	var resp []*ClmmPosition
	err := m.conn.WithContext(ctx).Model(&ClmmPosition{}).Where("`user_wallet_address` = ? AND `pool_state` = ? AND `deleted_at` IS NULL", userWalletAddress, poolState).Find(&resp).Error
	return resp, err
}

func (m *defaultClmmPositionModel) Update(ctx context.Context, data *ClmmPosition) error {
	db := m.conn
	err := db.WithContext(ctx).Model(&ClmmPosition{}).Where("`id` = ?", data.Id).Updates(data).Error
	return err
}

func (m *defaultClmmPositionModel) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Model(&ClmmPosition{}).Where("`id` = ?", id).Update("deleted_at", time.Now()).Error
	return err
}

