// Code generated by goctl. DO NOT EDIT!

package solmodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
)

// avoid unused err
var _ = time.Second

type (
	pumpCreateTokenUnsignedModel interface {
		Insert(ctx context.Context, data *PumpCreateTokenUnsigned) error

		FindOne(ctx context.Context, id int64) (*PumpCreateTokenUnsigned, error)
		FindOneByChainIdMint(ctx context.Context, chainId int64, mint string) (*PumpCreateTokenUnsigned, error)
		Update(ctx context.Context, data *PumpCreateTokenUnsigned) error

		Delete(ctx context.Context, id int64) error
	}

	defaultPumpCreateTokenUnsignedModel struct {
		conn  *gorm.DB
		table string
	}

	PumpCreateTokenUnsigned struct {
		Id                int64        `gorm:"column:id"`
		ChainId           int64        `gorm:"column:chain_id"`            // ID
		Mint              string       `gorm:"column:mint"`                // token mint address
		UserWalletAddress string       `gorm:"column:user_wallet_address"` // creator wallet
		Name              string       `gorm:"column:name"`                // token name
		Symbol            string       `gorm:"column:symbol"`              // token symbol
		Uri               string       `gorm:"column:uri"`                 // metadata uri
		Website           string       `gorm:"column:website"`             // website
		Twitter           string       `gorm:"column:twitter"`             // twitter
		Telegram          string       `gorm:"column:telegram"`            // telegram
		Description       string       `gorm:"column:description"`         // desc
		ImageUri          string       `gorm:"column:image_uri"`           // image uri
		UnsignedTx        string       `gorm:"column:unsigned_tx"`         // unsigned tx base64
		DexName           string       `gorm:"column:dex_name"`            // dex name, pump_fun
		Status            int64        `gorm:"column:status"`              // 0 processing,1 success,2 failed
		TxSignature       string       `gorm:"column:tx_signature"`        // tx signature
		PairAddr          string       `gorm:"column:pair_addr"`           // derived pair address (bonding curve)
		ErrorMessage      string       `gorm:"column:error_message"`       // error
		CreatedAt         time.Time    `gorm:"column:created_at"`
		UpdatedAt         time.Time    `gorm:"column:updated_at"`
		DeletedAt         sql.NullTime `gorm:"column:deleted_at;index"`
	}
)

var QPumpCreateTokenUnsigned PumpCreateTokenUnsigned

func init() {
	InitField(&QPumpCreateTokenUnsigned)
}

func (PumpCreateTokenUnsigned) TableName() string {
	return strings.Trim("`pump_create_token_unsigned`", "`")
}

func newPumpCreateTokenUnsignedModel(conn *gorm.DB) *defaultPumpCreateTokenUnsignedModel {
	return &defaultPumpCreateTokenUnsignedModel{
		conn:  conn,
		table: strings.Trim("`pump_create_token_unsigned`", "`"),
	}
}

func (m *defaultPumpCreateTokenUnsignedModel) Insert(ctx context.Context, data *PumpCreateTokenUnsigned) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultPumpCreateTokenUnsignedModel) FindOne(ctx context.Context, id int64) (*PumpCreateTokenUnsigned, error) {
	var resp PumpCreateTokenUnsigned
	err := m.conn.WithContext(ctx).Model(&PumpCreateTokenUnsigned{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err

}

func (m *defaultPumpCreateTokenUnsignedModel) FindOneByChainIdMint(ctx context.Context, chainId int64, mint string) (*PumpCreateTokenUnsigned, error) {
	var resp PumpCreateTokenUnsigned
	err := m.conn.WithContext(ctx).Model(&PumpCreateTokenUnsigned{}).Where("`chain_id` = ? and `mint` = ?", chainId, mint).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultPumpCreateTokenUnsignedModel) Update(ctx context.Context, data *PumpCreateTokenUnsigned) error {
	db := m.conn
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultPumpCreateTokenUnsignedModel) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Where("`id` = @id", sql.Named("id", id)).Delete(&PumpCreateTokenUnsigned{}).Error

	return err
}
