// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: trade.proto

package server

import (
	"context"

	"richcode.cc/dex/trade/internal/logic"
	"richcode.cc/dex/trade/internal/svc"
	"richcode.cc/dex/trade/trade"
)

type TradeServer struct {
	svcCtx *svc.ServiceContext
	trade.UnimplementedTradeServer
}

func NewTradeServer(svcCtx *svc.ServiceContext) *TradeServer {
	return &TradeServer{
		svcCtx: svcCtx,
	}
}

func (s *TradeServer) CreateMarketOrder(ctx context.Context, in *trade.CreateMarketOrderRequest) (*trade.CreateMarketOrderResponse, error) {
	l := logic.NewCreateMarketOrderLogic(ctx, s.svcCtx)
	return l.CreateMarketOrder(in)
}

// Create a PumpFun token: backend builds unsigned tx for client signing
func (s *TradeServer) CreatePumpToken(ctx context.Context, in *trade.CreatePumpTokenRequest) (*trade.CreatePumpTokenResponse, error) {
	l := logic.NewCreatePumpTokenLogic(ctx, s.svcCtx)
	return l.CreatePumpToken(in)
}

// IPFS helpers: upload file and token metadata
func (s *TradeServer) UploadIpfsFile(ctx context.Context, in *trade.UploadIpfsFileRequest) (*trade.UploadIpfsFileResponse, error) {
	l := logic.NewUploadIpfsFileLogic(ctx, s.svcCtx)
	return l.UploadIpfsFile(in)
}

func (s *TradeServer) UploadTokenMetadata(ctx context.Context, in *trade.UploadMetadataRequest) (*trade.UploadMetadataResponse, error) {
	l := logic.NewUploadTokenMetadataLogic(ctx, s.svcCtx)
	return l.UploadTokenMetadata(in)
}

// Frontend reports tx result for Pump create
func (s *TradeServer) ReportPumpCreateResult(ctx context.Context, in *trade.ReportPumpCreateResultRequest) (*trade.ReportPumpCreateResultResponse, error) {
	l := logic.NewReportPumpCreateResultLogic(ctx, s.svcCtx)
	return l.ReportPumpCreateResult(in)
}

// Quote Pump buy/sell outcomes for SOL or TOKEN inputs
func (s *TradeServer) QuotePumpTrade(ctx context.Context, in *trade.QuotePumpTradeRequest) (*trade.QuotePumpTradeResponse, error) {
	l := logic.NewQuotePumpTradeLogic(ctx, s.svcCtx)
	return l.QuotePumpTrade(in)
}

// Liquidity configuration endpoints
func (s *TradeServer) GetCpmmTokens(ctx context.Context, in *trade.GetCpmmTokensRequest) (*trade.GetCpmmTokensResponse, error) {
	l := logic.NewGetCpmmTokensLogic(ctx, s.svcCtx)
	return l.GetCpmmTokens(in)
}

func (s *TradeServer) GetCpmmFeeTiers(ctx context.Context, in *trade.GetCpmmFeeTiersRequest) (*trade.GetCpmmFeeTiersResponse, error) {
	l := logic.NewGetCpmmFeeTiersLogic(ctx, s.svcCtx)
	return l.GetCpmmFeeTiers(in)
}

func (s *TradeServer) CreateCpmmPool(ctx context.Context, in *trade.CreateCpmmPoolRequest) (*trade.CreateCpmmPoolResponse, error) {
	l := logic.NewCreateCpmmPoolLogic(ctx, s.svcCtx)
	return l.CreateCpmmPool(in)
}

// Build unsigned tx for adding liquidity to CPMM pool
func (s *TradeServer) AddCpmmLiquidity(ctx context.Context, in *trade.AddCpmmLiquidityRequest) (*trade.AddCpmmLiquidityResponse, error) {
	l := logic.NewAddCpmmLiquidityLogic(ctx, s.svcCtx)
	return l.AddCpmmLiquidity(in)
}

// Build unsigned tx for removing liquidity from CPMM pool
func (s *TradeServer) RemoveCpmmLiquidity(ctx context.Context, in *trade.RemoveCpmmLiquidityRequest) (*trade.RemoveCpmmLiquidityResponse, error) {
	l := logic.NewRemoveCpmmLiquidityLogic(ctx, s.svcCtx)
	return l.RemoveCpmmLiquidity(in)
}

// Build unsigned tx for swapping inside a CPMM pool
func (s *TradeServer) SwapCpmm(ctx context.Context, in *trade.SwapCpmmRequest) (*trade.SwapCpmmResponse, error) {
	l := logic.NewSwapCpmmLogic(ctx, s.svcCtx)
	return l.SwapCpmm(in)
}

// Build unsigned tx for swapping inside a CLMM pool
func (s *TradeServer) SwapClmm(ctx context.Context, in *trade.SwapClmmRequest) (*trade.SwapClmmResponse, error) {
	l := logic.NewSwapClmmLogic(ctx, s.svcCtx)
	return l.SwapClmm(in)
}

// Build unsigned tx for creating a CLMM pool
func (s *TradeServer) CreateClmmPool(ctx context.Context, in *trade.CreateClmmPoolRequest) (*trade.CreateClmmPoolResponse, error) {
	l := logic.NewCreateClmmPoolLogic(ctx, s.svcCtx)
	return l.CreateClmmPool(in)
}

// Build unsigned tx for opening a position in CLMM pool
func (s *TradeServer) OpenPosition(ctx context.Context, in *trade.OpenPositionRequest) (*trade.OpenPositionResponse, error) {
	l := logic.NewOpenPositionLogic(ctx, s.svcCtx)
	return l.OpenPosition(in)
}

// Build unsigned tx for increasing liquidity in CLMM position
func (s *TradeServer) IncreaseClmmLiquidity(ctx context.Context, in *trade.IncreaseClmmLiquidityRequest) (*trade.IncreaseClmmLiquidityResponse, error) {
	l := logic.NewIncreaseClmmLiquidityLogic(ctx, s.svcCtx)
	return l.IncreaseClmmLiquidity(in)
}

// Build unsigned tx for decreasing liquidity in CLMM position
func (s *TradeServer) DecreaseClmmLiquidity(ctx context.Context, in *trade.DecreaseClmmLiquidityRequest) (*trade.DecreaseClmmLiquidityResponse, error) {
	l := logic.NewDecreaseClmmLiquidityLogic(ctx, s.svcCtx)
	return l.DecreaseClmmLiquidity(in)
}
