// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: limitorder.proto

package limitorder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LimitOrder_InitializeMarginAccount_FullMethodName = "/limitorder.LimitOrder/InitializeMarginAccount"
	LimitOrder_SyncMarginAccountStatus_FullMethodName = "/limitorder.LimitOrder/SyncMarginAccountStatus"
	LimitOrder_CreateMarket_FullMethodName            = "/limitorder.LimitOrder/CreateMarket"
	LimitOrder_SyncMarketStatus_FullMethodName        = "/limitorder.LimitOrder/SyncMarketStatus"
)

// LimitOrderClient is the client API for LimitOrder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============================================================
// LimitOrder Service (only gateway-used RPCs)
// ============================================================
type LimitOrderClient interface {
	// Initialize margin account
	InitializeMarginAccount(ctx context.Context, in *InitializeMarginAccountRequest, opts ...grpc.CallOption) (*InitializeMarginAccountResponse, error)
	// Sync margin account status (check chain + update DB)
	SyncMarginAccountStatus(ctx context.Context, in *SyncMarginAccountStatusRequest, opts ...grpc.CallOption) (*SyncMarginAccountStatusResponse, error)
	// Create limit order market
	CreateMarket(ctx context.Context, in *CreateMarketRequest, opts ...grpc.CallOption) (*CreateMarketResponse, error)
	// Sync market status
	SyncMarketStatus(ctx context.Context, in *SyncMarketStatusRequest, opts ...grpc.CallOption) (*SyncMarketStatusResponse, error)
}

type limitOrderClient struct {
	cc grpc.ClientConnInterface
}

func NewLimitOrderClient(cc grpc.ClientConnInterface) LimitOrderClient {
	return &limitOrderClient{cc}
}

func (c *limitOrderClient) InitializeMarginAccount(ctx context.Context, in *InitializeMarginAccountRequest, opts ...grpc.CallOption) (*InitializeMarginAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeMarginAccountResponse)
	err := c.cc.Invoke(ctx, LimitOrder_InitializeMarginAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *limitOrderClient) SyncMarginAccountStatus(ctx context.Context, in *SyncMarginAccountStatusRequest, opts ...grpc.CallOption) (*SyncMarginAccountStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncMarginAccountStatusResponse)
	err := c.cc.Invoke(ctx, LimitOrder_SyncMarginAccountStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *limitOrderClient) CreateMarket(ctx context.Context, in *CreateMarketRequest, opts ...grpc.CallOption) (*CreateMarketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMarketResponse)
	err := c.cc.Invoke(ctx, LimitOrder_CreateMarket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *limitOrderClient) SyncMarketStatus(ctx context.Context, in *SyncMarketStatusRequest, opts ...grpc.CallOption) (*SyncMarketStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncMarketStatusResponse)
	err := c.cc.Invoke(ctx, LimitOrder_SyncMarketStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LimitOrderServer is the server API for LimitOrder service.
// All implementations must embed UnimplementedLimitOrderServer
// for forward compatibility.
//
// ============================================================
// LimitOrder Service (only gateway-used RPCs)
// ============================================================
type LimitOrderServer interface {
	// Initialize margin account
	InitializeMarginAccount(context.Context, *InitializeMarginAccountRequest) (*InitializeMarginAccountResponse, error)
	// Sync margin account status (check chain + update DB)
	SyncMarginAccountStatus(context.Context, *SyncMarginAccountStatusRequest) (*SyncMarginAccountStatusResponse, error)
	// Create limit order market
	CreateMarket(context.Context, *CreateMarketRequest) (*CreateMarketResponse, error)
	// Sync market status
	SyncMarketStatus(context.Context, *SyncMarketStatusRequest) (*SyncMarketStatusResponse, error)
	mustEmbedUnimplementedLimitOrderServer()
}

// UnimplementedLimitOrderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLimitOrderServer struct{}

func (UnimplementedLimitOrderServer) InitializeMarginAccount(context.Context, *InitializeMarginAccountRequest) (*InitializeMarginAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitializeMarginAccount not implemented")
}
func (UnimplementedLimitOrderServer) SyncMarginAccountStatus(context.Context, *SyncMarginAccountStatusRequest) (*SyncMarginAccountStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncMarginAccountStatus not implemented")
}
func (UnimplementedLimitOrderServer) CreateMarket(context.Context, *CreateMarketRequest) (*CreateMarketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMarket not implemented")
}
func (UnimplementedLimitOrderServer) SyncMarketStatus(context.Context, *SyncMarketStatusRequest) (*SyncMarketStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncMarketStatus not implemented")
}
func (UnimplementedLimitOrderServer) mustEmbedUnimplementedLimitOrderServer() {}
func (UnimplementedLimitOrderServer) testEmbeddedByValue()                    {}

// UnsafeLimitOrderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LimitOrderServer will
// result in compilation errors.
type UnsafeLimitOrderServer interface {
	mustEmbedUnimplementedLimitOrderServer()
}

func RegisterLimitOrderServer(s grpc.ServiceRegistrar, srv LimitOrderServer) {
	// If the following call pancis, it indicates UnimplementedLimitOrderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LimitOrder_ServiceDesc, srv)
}

func _LimitOrder_InitializeMarginAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeMarginAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimitOrderServer).InitializeMarginAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LimitOrder_InitializeMarginAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimitOrderServer).InitializeMarginAccount(ctx, req.(*InitializeMarginAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LimitOrder_SyncMarginAccountStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncMarginAccountStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimitOrderServer).SyncMarginAccountStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LimitOrder_SyncMarginAccountStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimitOrderServer).SyncMarginAccountStatus(ctx, req.(*SyncMarginAccountStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LimitOrder_CreateMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimitOrderServer).CreateMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LimitOrder_CreateMarket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimitOrderServer).CreateMarket(ctx, req.(*CreateMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LimitOrder_SyncMarketStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncMarketStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LimitOrderServer).SyncMarketStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LimitOrder_SyncMarketStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LimitOrderServer).SyncMarketStatus(ctx, req.(*SyncMarketStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LimitOrder_ServiceDesc is the grpc.ServiceDesc for LimitOrder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LimitOrder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "limitorder.LimitOrder",
	HandlerType: (*LimitOrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitializeMarginAccount",
			Handler:    _LimitOrder_InitializeMarginAccount_Handler,
		},
		{
			MethodName: "SyncMarginAccountStatus",
			Handler:    _LimitOrder_SyncMarginAccountStatus_Handler,
		},
		{
			MethodName: "CreateMarket",
			Handler:    _LimitOrder_CreateMarket_Handler,
		},
		{
			MethodName: "SyncMarketStatus",
			Handler:    _LimitOrder_SyncMarketStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "limitorder.proto",
}
