// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: limitorder.proto

package limitorder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============================================================
// Initialize margin account
// ============================================================
type InitializeMarginAccountRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChainId           int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`                                // Chain ID
	UserWalletAddress string                 `protobuf:"bytes,2,opt,name=user_wallet_address,json=userWalletAddress,proto3" json:"user_wallet_address,omitempty"` // User wallet address
	MarketPda         string                 `protobuf:"bytes,3,opt,name=market_pda,json=marketPda,proto3" json:"market_pda,omitempty"`                           // Market PDA
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InitializeMarginAccountRequest) Reset() {
	*x = InitializeMarginAccountRequest{}
	mi := &file_limitorder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeMarginAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeMarginAccountRequest) ProtoMessage() {}

func (x *InitializeMarginAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limitorder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeMarginAccountRequest.ProtoReflect.Descriptor instead.
func (*InitializeMarginAccountRequest) Descriptor() ([]byte, []int) {
	return file_limitorder_proto_rawDescGZIP(), []int{0}
}

func (x *InitializeMarginAccountRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *InitializeMarginAccountRequest) GetUserWalletAddress() string {
	if x != nil {
		return x.UserWalletAddress
	}
	return ""
}

func (x *InitializeMarginAccountRequest) GetMarketPda() string {
	if x != nil {
		return x.MarketPda
	}
	return ""
}

type InitializeMarginAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MarginPda     string                 `protobuf:"bytes,3,opt,name=margin_pda,json=marginPda,proto3" json:"margin_pda,omitempty"` // Margin account PDA
	TxHash        string                 `protobuf:"bytes,4,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`          // Transaction hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeMarginAccountResponse) Reset() {
	*x = InitializeMarginAccountResponse{}
	mi := &file_limitorder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeMarginAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeMarginAccountResponse) ProtoMessage() {}

func (x *InitializeMarginAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limitorder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeMarginAccountResponse.ProtoReflect.Descriptor instead.
func (*InitializeMarginAccountResponse) Descriptor() ([]byte, []int) {
	return file_limitorder_proto_rawDescGZIP(), []int{1}
}

func (x *InitializeMarginAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitializeMarginAccountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InitializeMarginAccountResponse) GetMarginPda() string {
	if x != nil {
		return x.MarginPda
	}
	return ""
}

func (x *InitializeMarginAccountResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

// ============================================================
// Sync margin account data (used internally, no RPC exposed)
// ============================================================
type SyncMarginAccountRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChainId           int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`                                // Chain ID
	UserWalletAddress string                 `protobuf:"bytes,2,opt,name=user_wallet_address,json=userWalletAddress,proto3" json:"user_wallet_address,omitempty"` // User wallet address
	MarketPda         string                 `protobuf:"bytes,3,opt,name=market_pda,json=marketPda,proto3" json:"market_pda,omitempty"`                           // Market PDA
	TxHash            string                 `protobuf:"bytes,4,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                                    // Init tx hash (optional, for DB update)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncMarginAccountRequest) Reset() {
	*x = SyncMarginAccountRequest{}
	mi := &file_limitorder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMarginAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMarginAccountRequest) ProtoMessage() {}

func (x *SyncMarginAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limitorder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMarginAccountRequest.ProtoReflect.Descriptor instead.
func (*SyncMarginAccountRequest) Descriptor() ([]byte, []int) {
	return file_limitorder_proto_rawDescGZIP(), []int{2}
}

func (x *SyncMarginAccountRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *SyncMarginAccountRequest) GetUserWalletAddress() string {
	if x != nil {
		return x.UserWalletAddress
	}
	return ""
}

func (x *SyncMarginAccountRequest) GetMarketPda() string {
	if x != nil {
		return x.MarketPda
	}
	return ""
}

func (x *SyncMarginAccountRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type SyncMarginAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Margin        *MarginAccount         `protobuf:"bytes,3,opt,name=margin,proto3" json:"margin,omitempty"` // Synced margin account data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMarginAccountResponse) Reset() {
	*x = SyncMarginAccountResponse{}
	mi := &file_limitorder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMarginAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMarginAccountResponse) ProtoMessage() {}

func (x *SyncMarginAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limitorder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMarginAccountResponse.ProtoReflect.Descriptor instead.
func (*SyncMarginAccountResponse) Descriptor() ([]byte, []int) {
	return file_limitorder_proto_rawDescGZIP(), []int{3}
}

func (x *SyncMarginAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncMarginAccountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncMarginAccountResponse) GetMargin() *MarginAccount {
	if x != nil {
		return x.Margin
	}
	return nil
}

// ============================================================
// Sync margin account status
// ============================================================
type SyncMarginAccountStatusRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChainId           int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`                                // Chain ID
	UserWalletAddress string                 `protobuf:"bytes,2,opt,name=user_wallet_address,json=userWalletAddress,proto3" json:"user_wallet_address,omitempty"` // User wallet address
	MarketPda         string                 `protobuf:"bytes,3,opt,name=market_pda,json=marketPda,proto3" json:"market_pda,omitempty"`                           // Market PDA
	TxHash            string                 `protobuf:"bytes,4,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                                    // Init tx hash (optional, for DB update)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncMarginAccountStatusRequest) Reset() {
	*x = SyncMarginAccountStatusRequest{}
	mi := &file_limitorder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMarginAccountStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMarginAccountStatusRequest) ProtoMessage() {}

func (x *SyncMarginAccountStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limitorder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMarginAccountStatusRequest.ProtoReflect.Descriptor instead.
func (*SyncMarginAccountStatusRequest) Descriptor() ([]byte, []int) {
	return file_limitorder_proto_rawDescGZIP(), []int{4}
}

func (x *SyncMarginAccountStatusRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *SyncMarginAccountStatusRequest) GetUserWalletAddress() string {
	if x != nil {
		return x.UserWalletAddress
	}
	return ""
}

func (x *SyncMarginAccountStatusRequest) GetMarketPda() string {
	if x != nil {
		return x.MarketPda
	}
	return ""
}

func (x *SyncMarginAccountStatusRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type SyncMarginAccountStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`                       // 0=Creating (not on-chain) 1=Active 2=Closed
	MarginPda     string                 `protobuf:"bytes,4,opt,name=margin_pda,json=marginPda,proto3" json:"margin_pda,omitempty"` // Margin account PDA
	TxBase64      string                 `protobuf:"bytes,5,opt,name=tx_base64,json=txBase64,proto3" json:"tx_base64,omitempty"`    // Unsigned tx if account missing on-chain
	Margin        *MarginAccount         `protobuf:"bytes,6,opt,name=margin,proto3" json:"margin,omitempty"`                        // Margin data if account exists
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMarginAccountStatusResponse) Reset() {
	*x = SyncMarginAccountStatusResponse{}
	mi := &file_limitorder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMarginAccountStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMarginAccountStatusResponse) ProtoMessage() {}

func (x *SyncMarginAccountStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limitorder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMarginAccountStatusResponse.ProtoReflect.Descriptor instead.
func (*SyncMarginAccountStatusResponse) Descriptor() ([]byte, []int) {
	return file_limitorder_proto_rawDescGZIP(), []int{5}
}

func (x *SyncMarginAccountStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncMarginAccountStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncMarginAccountStatusResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SyncMarginAccountStatusResponse) GetMarginPda() string {
	if x != nil {
		return x.MarginPda
	}
	return ""
}

func (x *SyncMarginAccountStatusResponse) GetTxBase64() string {
	if x != nil {
		return x.TxBase64
	}
	return ""
}

func (x *SyncMarginAccountStatusResponse) GetMargin() *MarginAccount {
	if x != nil {
		return x.Margin
	}
	return nil
}

// ============================================================
// Margin account data structure
// ============================================================
type MarginAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MarginPda     string                 `protobuf:"bytes,2,opt,name=margin_pda,json=marginPda,proto3" json:"margin_pda,omitempty"`
	MarketPda     string                 `protobuf:"bytes,3,opt,name=market_pda,json=marketPda,proto3" json:"market_pda,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	BaseFree      string                 `protobuf:"bytes,5,opt,name=base_free,json=baseFree,proto3" json:"base_free,omitempty"`          // Base free balance (display)
	BaseLocked    string                 `protobuf:"bytes,6,opt,name=base_locked,json=baseLocked,proto3" json:"base_locked,omitempty"`    // Base locked balance (display)
	QuoteFree     string                 `protobuf:"bytes,7,opt,name=quote_free,json=quoteFree,proto3" json:"quote_free,omitempty"`       // Quote free balance (display)
	QuoteLocked   string                 `protobuf:"bytes,8,opt,name=quote_locked,json=quoteLocked,proto3" json:"quote_locked,omitempty"` // Quote locked balance (display)
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`                             // 0=Creating 1=Active 2=Closed
	InitTxHash    string                 `protobuf:"bytes,10,opt,name=init_tx_hash,json=initTxHash,proto3" json:"init_tx_hash,omitempty"` // Init tx hash
	LastSyncSlot  int64                  `protobuf:"varint,11,opt,name=last_sync_slot,json=lastSyncSlot,proto3" json:"last_sync_slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarginAccount) Reset() {
	*x = MarginAccount{}
	mi := &file_limitorder_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarginAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarginAccount) ProtoMessage() {}

func (x *MarginAccount) ProtoReflect() protoreflect.Message {
	mi := &file_limitorder_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarginAccount.ProtoReflect.Descriptor instead.
func (*MarginAccount) Descriptor() ([]byte, []int) {
	return file_limitorder_proto_rawDescGZIP(), []int{6}
}

func (x *MarginAccount) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MarginAccount) GetMarginPda() string {
	if x != nil {
		return x.MarginPda
	}
	return ""
}

func (x *MarginAccount) GetMarketPda() string {
	if x != nil {
		return x.MarketPda
	}
	return ""
}

func (x *MarginAccount) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *MarginAccount) GetBaseFree() string {
	if x != nil {
		return x.BaseFree
	}
	return ""
}

func (x *MarginAccount) GetBaseLocked() string {
	if x != nil {
		return x.BaseLocked
	}
	return ""
}

func (x *MarginAccount) GetQuoteFree() string {
	if x != nil {
		return x.QuoteFree
	}
	return ""
}

func (x *MarginAccount) GetQuoteLocked() string {
	if x != nil {
		return x.QuoteLocked
	}
	return ""
}

func (x *MarginAccount) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MarginAccount) GetInitTxHash() string {
	if x != nil {
		return x.InitTxHash
	}
	return ""
}

func (x *MarginAccount) GetLastSyncSlot() int64 {
	if x != nil {
		return x.LastSyncSlot
	}
	return 0
}

// ============================================================
// Create limit order market
// ============================================================
type CreateMarketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`                     // Chain ID
	Admin         string                 `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`                                         // Market admin wallet address
	BaseMint      string                 `protobuf:"bytes,3,opt,name=base_mint,json=baseMint,proto3" json:"base_mint,omitempty"`                   // Base token mint address
	QuoteMint     string                 `protobuf:"bytes,4,opt,name=quote_mint,json=quoteMint,proto3" json:"quote_mint,omitempty"`                // Quote token mint address
	BaseSymbol    string                 `protobuf:"bytes,5,opt,name=base_symbol,json=baseSymbol,proto3" json:"base_symbol,omitempty"`             // Base token symbol
	QuoteSymbol   string                 `protobuf:"bytes,6,opt,name=quote_symbol,json=quoteSymbol,proto3" json:"quote_symbol,omitempty"`          // Quote token symbol
	BaseDecimals  int32                  `protobuf:"varint,7,opt,name=base_decimals,json=baseDecimals,proto3" json:"base_decimals,omitempty"`      // Base token decimals
	QuoteDecimals int32                  `protobuf:"varint,8,opt,name=quote_decimals,json=quoteDecimals,proto3" json:"quote_decimals,omitempty"`   // Quote token decimals
	TickSize      float64                `protobuf:"fixed64,9,opt,name=tick_size,json=tickSize,proto3" json:"tick_size,omitempty"`                 // Price tick size (display value, e.g., 0.01)
	MinBaseLot    float64                `protobuf:"fixed64,10,opt,name=min_base_lot,json=minBaseLot,proto3" json:"min_base_lot,omitempty"`        // Minimum base lot size (display value, e.g., 0.001 SOL)
	MakerFeeBps   int32                  `protobuf:"varint,11,opt,name=maker_fee_bps,json=makerFeeBps,proto3" json:"maker_fee_bps,omitempty"`      // Maker fee in basis points
	TakerFeeBps   int32                  `protobuf:"varint,12,opt,name=taker_fee_bps,json=takerFeeBps,proto3" json:"taker_fee_bps,omitempty"`      // Taker fee in basis points
	PythPriceFeed string                 `protobuf:"bytes,13,opt,name=pyth_price_feed,json=pythPriceFeed,proto3" json:"pyth_price_feed,omitempty"` // Pyth price feed address (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMarketRequest) Reset() {
	*x = CreateMarketRequest{}
	mi := &file_limitorder_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMarketRequest) ProtoMessage() {}

func (x *CreateMarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limitorder_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMarketRequest.ProtoReflect.Descriptor instead.
func (*CreateMarketRequest) Descriptor() ([]byte, []int) {
	return file_limitorder_proto_rawDescGZIP(), []int{7}
}

func (x *CreateMarketRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *CreateMarketRequest) GetAdmin() string {
	if x != nil {
		return x.Admin
	}
	return ""
}

func (x *CreateMarketRequest) GetBaseMint() string {
	if x != nil {
		return x.BaseMint
	}
	return ""
}

func (x *CreateMarketRequest) GetQuoteMint() string {
	if x != nil {
		return x.QuoteMint
	}
	return ""
}

func (x *CreateMarketRequest) GetBaseSymbol() string {
	if x != nil {
		return x.BaseSymbol
	}
	return ""
}

func (x *CreateMarketRequest) GetQuoteSymbol() string {
	if x != nil {
		return x.QuoteSymbol
	}
	return ""
}

func (x *CreateMarketRequest) GetBaseDecimals() int32 {
	if x != nil {
		return x.BaseDecimals
	}
	return 0
}

func (x *CreateMarketRequest) GetQuoteDecimals() int32 {
	if x != nil {
		return x.QuoteDecimals
	}
	return 0
}

func (x *CreateMarketRequest) GetTickSize() float64 {
	if x != nil {
		return x.TickSize
	}
	return 0
}

func (x *CreateMarketRequest) GetMinBaseLot() float64 {
	if x != nil {
		return x.MinBaseLot
	}
	return 0
}

func (x *CreateMarketRequest) GetMakerFeeBps() int32 {
	if x != nil {
		return x.MakerFeeBps
	}
	return 0
}

func (x *CreateMarketRequest) GetTakerFeeBps() int32 {
	if x != nil {
		return x.TakerFeeBps
	}
	return 0
}

func (x *CreateMarketRequest) GetPythPriceFeed() string {
	if x != nil {
		return x.PythPriceFeed
	}
	return ""
}

type CreateMarketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MarketPda     string                 `protobuf:"bytes,3,opt,name=market_pda,json=marketPda,proto3" json:"market_pda,omitempty"`  // Created market PDA
	TxBase64      string                 `protobuf:"bytes,4,opt,name=tx_base64,json=txBase64,proto3" json:"tx_base64,omitempty"`     // Unsigned tx (init_market + init_vaults)
	ExpiresAt     int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Transaction expiration timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMarketResponse) Reset() {
	*x = CreateMarketResponse{}
	mi := &file_limitorder_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMarketResponse) ProtoMessage() {}

func (x *CreateMarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limitorder_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMarketResponse.ProtoReflect.Descriptor instead.
func (*CreateMarketResponse) Descriptor() ([]byte, []int) {
	return file_limitorder_proto_rawDescGZIP(), []int{8}
}

func (x *CreateMarketResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateMarketResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateMarketResponse) GetMarketPda() string {
	if x != nil {
		return x.MarketPda
	}
	return ""
}

func (x *CreateMarketResponse) GetTxBase64() string {
	if x != nil {
		return x.TxBase64
	}
	return ""
}

func (x *CreateMarketResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// ============================================================
// Sync market status
// ============================================================
type SyncMarketStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`      // Chain ID
	MarketPda     string                 `protobuf:"bytes,2,opt,name=market_pda,json=marketPda,proto3" json:"market_pda,omitempty"` // Market PDA address
	TxHash        string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`          // Transaction hash (optional, for DB update)
	Admin         string                 `protobuf:"bytes,4,opt,name=admin,proto3" json:"admin,omitempty"`                          // Admin wallet address (optional, for tx rebuild)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMarketStatusRequest) Reset() {
	*x = SyncMarketStatusRequest{}
	mi := &file_limitorder_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMarketStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMarketStatusRequest) ProtoMessage() {}

func (x *SyncMarketStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limitorder_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMarketStatusRequest.ProtoReflect.Descriptor instead.
func (*SyncMarketStatusRequest) Descriptor() ([]byte, []int) {
	return file_limitorder_proto_rawDescGZIP(), []int{9}
}

func (x *SyncMarketStatusRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *SyncMarketStatusRequest) GetMarketPda() string {
	if x != nil {
		return x.MarketPda
	}
	return ""
}

func (x *SyncMarketStatusRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *SyncMarketStatusRequest) GetAdmin() string {
	if x != nil {
		return x.Admin
	}
	return ""
}

type SyncMarketStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`                       // 0=Creating (not on-chain) 1=Active 2=Closed
	MarketPda     string                 `protobuf:"bytes,4,opt,name=market_pda,json=marketPda,proto3" json:"market_pda,omitempty"` // Market PDA
	TxBase64      string                 `protobuf:"bytes,5,opt,name=tx_base64,json=txBase64,proto3" json:"tx_base64,omitempty"`    // Unsigned tx if market missing on-chain
	Market        *MarketInfo            `protobuf:"bytes,6,opt,name=market,proto3" json:"market,omitempty"`                        // Market data if exists
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMarketStatusResponse) Reset() {
	*x = SyncMarketStatusResponse{}
	mi := &file_limitorder_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMarketStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMarketStatusResponse) ProtoMessage() {}

func (x *SyncMarketStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limitorder_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMarketStatusResponse.ProtoReflect.Descriptor instead.
func (*SyncMarketStatusResponse) Descriptor() ([]byte, []int) {
	return file_limitorder_proto_rawDescGZIP(), []int{10}
}

func (x *SyncMarketStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncMarketStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncMarketStatusResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SyncMarketStatusResponse) GetMarketPda() string {
	if x != nil {
		return x.MarketPda
	}
	return ""
}

func (x *SyncMarketStatusResponse) GetTxBase64() string {
	if x != nil {
		return x.TxBase64
	}
	return ""
}

func (x *SyncMarketStatusResponse) GetMarket() *MarketInfo {
	if x != nil {
		return x.Market
	}
	return nil
}

// Market info from database
type MarketInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MarketPda     string                 `protobuf:"bytes,2,opt,name=market_pda,json=marketPda,proto3" json:"market_pda,omitempty"`
	BaseMint      string                 `protobuf:"bytes,3,opt,name=base_mint,json=baseMint,proto3" json:"base_mint,omitempty"`
	QuoteMint     string                 `protobuf:"bytes,4,opt,name=quote_mint,json=quoteMint,proto3" json:"quote_mint,omitempty"`
	BaseSymbol    string                 `protobuf:"bytes,5,opt,name=base_symbol,json=baseSymbol,proto3" json:"base_symbol,omitempty"`
	QuoteSymbol   string                 `protobuf:"bytes,6,opt,name=quote_symbol,json=quoteSymbol,proto3" json:"quote_symbol,omitempty"`
	BaseDecimals  int32                  `protobuf:"varint,7,opt,name=base_decimals,json=baseDecimals,proto3" json:"base_decimals,omitempty"`
	QuoteDecimals int32                  `protobuf:"varint,8,opt,name=quote_decimals,json=quoteDecimals,proto3" json:"quote_decimals,omitempty"`
	BaseVault     string                 `protobuf:"bytes,9,opt,name=base_vault,json=baseVault,proto3" json:"base_vault,omitempty"`
	QuoteVault    string                 `protobuf:"bytes,10,opt,name=quote_vault,json=quoteVault,proto3" json:"quote_vault,omitempty"`
	TickSize      int64                  `protobuf:"varint,11,opt,name=tick_size,json=tickSize,proto3" json:"tick_size,omitempty"`
	MinBaseLot    int64                  `protobuf:"varint,12,opt,name=min_base_lot,json=minBaseLot,proto3" json:"min_base_lot,omitempty"`
	MinQuoteLot   int64                  `protobuf:"varint,13,opt,name=min_quote_lot,json=minQuoteLot,proto3" json:"min_quote_lot,omitempty"`
	MakerFeeBps   int32                  `protobuf:"varint,14,opt,name=maker_fee_bps,json=makerFeeBps,proto3" json:"maker_fee_bps,omitempty"`
	TakerFeeBps   int32                  `protobuf:"varint,15,opt,name=taker_fee_bps,json=takerFeeBps,proto3" json:"taker_fee_bps,omitempty"`
	Status        int32                  `protobuf:"varint,16,opt,name=status,proto3" json:"status,omitempty"`
	Paused        bool                   `protobuf:"varint,17,opt,name=paused,proto3" json:"paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketInfo) Reset() {
	*x = MarketInfo{}
	mi := &file_limitorder_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketInfo) ProtoMessage() {}

func (x *MarketInfo) ProtoReflect() protoreflect.Message {
	mi := &file_limitorder_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketInfo.ProtoReflect.Descriptor instead.
func (*MarketInfo) Descriptor() ([]byte, []int) {
	return file_limitorder_proto_rawDescGZIP(), []int{11}
}

func (x *MarketInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MarketInfo) GetMarketPda() string {
	if x != nil {
		return x.MarketPda
	}
	return ""
}

func (x *MarketInfo) GetBaseMint() string {
	if x != nil {
		return x.BaseMint
	}
	return ""
}

func (x *MarketInfo) GetQuoteMint() string {
	if x != nil {
		return x.QuoteMint
	}
	return ""
}

func (x *MarketInfo) GetBaseSymbol() string {
	if x != nil {
		return x.BaseSymbol
	}
	return ""
}

func (x *MarketInfo) GetQuoteSymbol() string {
	if x != nil {
		return x.QuoteSymbol
	}
	return ""
}

func (x *MarketInfo) GetBaseDecimals() int32 {
	if x != nil {
		return x.BaseDecimals
	}
	return 0
}

func (x *MarketInfo) GetQuoteDecimals() int32 {
	if x != nil {
		return x.QuoteDecimals
	}
	return 0
}

func (x *MarketInfo) GetBaseVault() string {
	if x != nil {
		return x.BaseVault
	}
	return ""
}

func (x *MarketInfo) GetQuoteVault() string {
	if x != nil {
		return x.QuoteVault
	}
	return ""
}

func (x *MarketInfo) GetTickSize() int64 {
	if x != nil {
		return x.TickSize
	}
	return 0
}

func (x *MarketInfo) GetMinBaseLot() int64 {
	if x != nil {
		return x.MinBaseLot
	}
	return 0
}

func (x *MarketInfo) GetMinQuoteLot() int64 {
	if x != nil {
		return x.MinQuoteLot
	}
	return 0
}

func (x *MarketInfo) GetMakerFeeBps() int32 {
	if x != nil {
		return x.MakerFeeBps
	}
	return 0
}

func (x *MarketInfo) GetTakerFeeBps() int32 {
	if x != nil {
		return x.TakerFeeBps
	}
	return 0
}

func (x *MarketInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MarketInfo) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

var File_limitorder_proto protoreflect.FileDescriptor

const file_limitorder_proto_rawDesc = "" +
	"\n" +
	"\x10limitorder.proto\x12\n" +
	"limitorder\"\x8a\x01\n" +
	"\x1eInitializeMarginAccountRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12.\n" +
	"\x13user_wallet_address\x18\x02 \x01(\tR\x11userWalletAddress\x12\x1d\n" +
	"\n" +
	"market_pda\x18\x03 \x01(\tR\tmarketPda\"\x8d\x01\n" +
	"\x1fInitializeMarginAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"margin_pda\x18\x03 \x01(\tR\tmarginPda\x12\x17\n" +
	"\atx_hash\x18\x04 \x01(\tR\x06txHash\"\x9d\x01\n" +
	"\x18SyncMarginAccountRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12.\n" +
	"\x13user_wallet_address\x18\x02 \x01(\tR\x11userWalletAddress\x12\x1d\n" +
	"\n" +
	"market_pda\x18\x03 \x01(\tR\tmarketPda\x12\x17\n" +
	"\atx_hash\x18\x04 \x01(\tR\x06txHash\"\x82\x01\n" +
	"\x19SyncMarginAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x06margin\x18\x03 \x01(\v2\x19.limitorder.MarginAccountR\x06margin\"\xa3\x01\n" +
	"\x1eSyncMarginAccountStatusRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12.\n" +
	"\x13user_wallet_address\x18\x02 \x01(\tR\x11userWalletAddress\x12\x1d\n" +
	"\n" +
	"market_pda\x18\x03 \x01(\tR\tmarketPda\x12\x17\n" +
	"\atx_hash\x18\x04 \x01(\tR\x06txHash\"\xdc\x01\n" +
	"\x1fSyncMarginAccountStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"margin_pda\x18\x04 \x01(\tR\tmarginPda\x12\x1b\n" +
	"\ttx_base64\x18\x05 \x01(\tR\btxBase64\x121\n" +
	"\x06margin\x18\x06 \x01(\v2\x19.limitorder.MarginAccountR\x06margin\"\xd3\x02\n" +
	"\rMarginAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"margin_pda\x18\x02 \x01(\tR\tmarginPda\x12\x1d\n" +
	"\n" +
	"market_pda\x18\x03 \x01(\tR\tmarketPda\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x1b\n" +
	"\tbase_free\x18\x05 \x01(\tR\bbaseFree\x12\x1f\n" +
	"\vbase_locked\x18\x06 \x01(\tR\n" +
	"baseLocked\x12\x1d\n" +
	"\n" +
	"quote_free\x18\a \x01(\tR\tquoteFree\x12!\n" +
	"\fquote_locked\x18\b \x01(\tR\vquoteLocked\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12 \n" +
	"\finit_tx_hash\x18\n" +
	" \x01(\tR\n" +
	"initTxHash\x12$\n" +
	"\x0elast_sync_slot\x18\v \x01(\x03R\flastSyncSlot\"\xc1\x03\n" +
	"\x13CreateMarketRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12\x14\n" +
	"\x05admin\x18\x02 \x01(\tR\x05admin\x12\x1b\n" +
	"\tbase_mint\x18\x03 \x01(\tR\bbaseMint\x12\x1d\n" +
	"\n" +
	"quote_mint\x18\x04 \x01(\tR\tquoteMint\x12\x1f\n" +
	"\vbase_symbol\x18\x05 \x01(\tR\n" +
	"baseSymbol\x12!\n" +
	"\fquote_symbol\x18\x06 \x01(\tR\vquoteSymbol\x12#\n" +
	"\rbase_decimals\x18\a \x01(\x05R\fbaseDecimals\x12%\n" +
	"\x0equote_decimals\x18\b \x01(\x05R\rquoteDecimals\x12\x1b\n" +
	"\ttick_size\x18\t \x01(\x01R\btickSize\x12 \n" +
	"\fmin_base_lot\x18\n" +
	" \x01(\x01R\n" +
	"minBaseLot\x12\"\n" +
	"\rmaker_fee_bps\x18\v \x01(\x05R\vmakerFeeBps\x12\"\n" +
	"\rtaker_fee_bps\x18\f \x01(\x05R\vtakerFeeBps\x12&\n" +
	"\x0fpyth_price_feed\x18\r \x01(\tR\rpythPriceFeed\"\xa5\x01\n" +
	"\x14CreateMarketResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"market_pda\x18\x03 \x01(\tR\tmarketPda\x12\x1b\n" +
	"\ttx_base64\x18\x04 \x01(\tR\btxBase64\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\"\x82\x01\n" +
	"\x17SyncMarketStatusRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12\x1d\n" +
	"\n" +
	"market_pda\x18\x02 \x01(\tR\tmarketPda\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12\x14\n" +
	"\x05admin\x18\x04 \x01(\tR\x05admin\"\xd2\x01\n" +
	"\x18SyncMarketStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"market_pda\x18\x04 \x01(\tR\tmarketPda\x12\x1b\n" +
	"\ttx_base64\x18\x05 \x01(\tR\btxBase64\x12.\n" +
	"\x06market\x18\x06 \x01(\v2\x16.limitorder.MarketInfoR\x06market\"\xa2\x04\n" +
	"\n" +
	"MarketInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"market_pda\x18\x02 \x01(\tR\tmarketPda\x12\x1b\n" +
	"\tbase_mint\x18\x03 \x01(\tR\bbaseMint\x12\x1d\n" +
	"\n" +
	"quote_mint\x18\x04 \x01(\tR\tquoteMint\x12\x1f\n" +
	"\vbase_symbol\x18\x05 \x01(\tR\n" +
	"baseSymbol\x12!\n" +
	"\fquote_symbol\x18\x06 \x01(\tR\vquoteSymbol\x12#\n" +
	"\rbase_decimals\x18\a \x01(\x05R\fbaseDecimals\x12%\n" +
	"\x0equote_decimals\x18\b \x01(\x05R\rquoteDecimals\x12\x1d\n" +
	"\n" +
	"base_vault\x18\t \x01(\tR\tbaseVault\x12\x1f\n" +
	"\vquote_vault\x18\n" +
	" \x01(\tR\n" +
	"quoteVault\x12\x1b\n" +
	"\ttick_size\x18\v \x01(\x03R\btickSize\x12 \n" +
	"\fmin_base_lot\x18\f \x01(\x03R\n" +
	"minBaseLot\x12\"\n" +
	"\rmin_quote_lot\x18\r \x01(\x03R\vminQuoteLot\x12\"\n" +
	"\rmaker_fee_bps\x18\x0e \x01(\x05R\vmakerFeeBps\x12\"\n" +
	"\rtaker_fee_bps\x18\x0f \x01(\x05R\vtakerFeeBps\x12\x16\n" +
	"\x06status\x18\x10 \x01(\x05R\x06status\x12\x16\n" +
	"\x06paused\x18\x11 \x01(\bR\x06paused2\xa6\x03\n" +
	"\n" +
	"LimitOrder\x12r\n" +
	"\x17InitializeMarginAccount\x12*.limitorder.InitializeMarginAccountRequest\x1a+.limitorder.InitializeMarginAccountResponse\x12r\n" +
	"\x17SyncMarginAccountStatus\x12*.limitorder.SyncMarginAccountStatusRequest\x1a+.limitorder.SyncMarginAccountStatusResponse\x12Q\n" +
	"\fCreateMarket\x12\x1f.limitorder.CreateMarketRequest\x1a .limitorder.CreateMarketResponse\x12]\n" +
	"\x10SyncMarketStatus\x12#.limitorder.SyncMarketStatusRequest\x1a$.limitorder.SyncMarketStatusResponseB\x0eZ\f./limitorderb\x06proto3"

var (
	file_limitorder_proto_rawDescOnce sync.Once
	file_limitorder_proto_rawDescData []byte
)

func file_limitorder_proto_rawDescGZIP() []byte {
	file_limitorder_proto_rawDescOnce.Do(func() {
		file_limitorder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_limitorder_proto_rawDesc), len(file_limitorder_proto_rawDesc)))
	})
	return file_limitorder_proto_rawDescData
}

var file_limitorder_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_limitorder_proto_goTypes = []any{
	(*InitializeMarginAccountRequest)(nil),  // 0: limitorder.InitializeMarginAccountRequest
	(*InitializeMarginAccountResponse)(nil), // 1: limitorder.InitializeMarginAccountResponse
	(*SyncMarginAccountRequest)(nil),        // 2: limitorder.SyncMarginAccountRequest
	(*SyncMarginAccountResponse)(nil),       // 3: limitorder.SyncMarginAccountResponse
	(*SyncMarginAccountStatusRequest)(nil),  // 4: limitorder.SyncMarginAccountStatusRequest
	(*SyncMarginAccountStatusResponse)(nil), // 5: limitorder.SyncMarginAccountStatusResponse
	(*MarginAccount)(nil),                   // 6: limitorder.MarginAccount
	(*CreateMarketRequest)(nil),             // 7: limitorder.CreateMarketRequest
	(*CreateMarketResponse)(nil),            // 8: limitorder.CreateMarketResponse
	(*SyncMarketStatusRequest)(nil),         // 9: limitorder.SyncMarketStatusRequest
	(*SyncMarketStatusResponse)(nil),        // 10: limitorder.SyncMarketStatusResponse
	(*MarketInfo)(nil),                      // 11: limitorder.MarketInfo
}
var file_limitorder_proto_depIdxs = []int32{
	6,  // 0: limitorder.SyncMarginAccountResponse.margin:type_name -> limitorder.MarginAccount
	6,  // 1: limitorder.SyncMarginAccountStatusResponse.margin:type_name -> limitorder.MarginAccount
	11, // 2: limitorder.SyncMarketStatusResponse.market:type_name -> limitorder.MarketInfo
	0,  // 3: limitorder.LimitOrder.InitializeMarginAccount:input_type -> limitorder.InitializeMarginAccountRequest
	4,  // 4: limitorder.LimitOrder.SyncMarginAccountStatus:input_type -> limitorder.SyncMarginAccountStatusRequest
	7,  // 5: limitorder.LimitOrder.CreateMarket:input_type -> limitorder.CreateMarketRequest
	9,  // 6: limitorder.LimitOrder.SyncMarketStatus:input_type -> limitorder.SyncMarketStatusRequest
	1,  // 7: limitorder.LimitOrder.InitializeMarginAccount:output_type -> limitorder.InitializeMarginAccountResponse
	5,  // 8: limitorder.LimitOrder.SyncMarginAccountStatus:output_type -> limitorder.SyncMarginAccountStatusResponse
	8,  // 9: limitorder.LimitOrder.CreateMarket:output_type -> limitorder.CreateMarketResponse
	10, // 10: limitorder.LimitOrder.SyncMarketStatus:output_type -> limitorder.SyncMarketStatusResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_limitorder_proto_init() }
func file_limitorder_proto_init() {
	if File_limitorder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_limitorder_proto_rawDesc), len(file_limitorder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_limitorder_proto_goTypes,
		DependencyIndexes: file_limitorder_proto_depIdxs,
		MessageInfos:      file_limitorder_proto_msgTypes,
	}.Build()
	File_limitorder_proto = out.File
	file_limitorder_proto_goTypes = nil
	file_limitorder_proto_depIdxs = nil
}
