// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: block.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BlockMessage 主消息（仅包含过滤后的相关交易）
type BlockMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础信息
	Slot       uint64 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	BlockTime  int64  `protobuf:"varint,2,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
	BlockHash  string `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	ParentSlot uint64 `protobuf:"varint,4,opt,name=parent_slot,json=parentSlot,proto3" json:"parent_slot,omitempty"`
	// 公共数据（生产者已解析，仅基于过滤后的交易）
	TokenAccounts        map[string]*TokenAccount     `protobuf:"bytes,5,rep,name=token_accounts,json=tokenAccounts,proto3" json:"token_accounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	InnerInstructionsMap map[int32]*InnerInstructions `protobuf:"bytes,6,rep,name=inner_instructions_map,json=innerInstructionsMap,proto3" json:"inner_instructions_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AccountKeys          []string                     `protobuf:"bytes,7,rep,name=account_keys,json=accountKeys,proto3" json:"account_keys,omitempty"`
	// 🔥 仅包含过滤后的交易数据（50-100笔相关交易）
	Transactions []*RawTransaction `protobuf:"bytes,8,rep,name=transactions,proto3" json:"transactions,omitempty"`
	// 元数据
	TransactionCount         int32   `protobuf:"varint,9,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`                            // 过滤后的交易数量
	OriginalTransactionCount int32   `protobuf:"varint,10,opt,name=original_transaction_count,json=originalTransactionCount,proto3" json:"original_transaction_count,omitempty"` // 原始区块交易总数
	SolPrice                 float64 `protobuf:"fixed64,11,opt,name=sol_price,json=solPrice,proto3" json:"sol_price,omitempty"`                                                  // 预计算的 SOL 价格
	// 过滤统计
	FilterStats *FilterStats `protobuf:"bytes,12,opt,name=filter_stats,json=filterStats,proto3" json:"filter_stats,omitempty"`
	// 🔥 按协议分组的交易（生产者已分组，消费者可并发处理）
	ProtocolGroups map[string]*ProtocolTransactionGroup `protobuf:"bytes,13,rep,name=protocol_groups,json=protocolGroups,proto3" json:"protocol_groups,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlockMessage) Reset() {
	*x = BlockMessage{}
	mi := &file_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockMessage) ProtoMessage() {}

func (x *BlockMessage) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockMessage.ProtoReflect.Descriptor instead.
func (*BlockMessage) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{0}
}

func (x *BlockMessage) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *BlockMessage) GetBlockTime() int64 {
	if x != nil {
		return x.BlockTime
	}
	return 0
}

func (x *BlockMessage) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *BlockMessage) GetParentSlot() uint64 {
	if x != nil {
		return x.ParentSlot
	}
	return 0
}

func (x *BlockMessage) GetTokenAccounts() map[string]*TokenAccount {
	if x != nil {
		return x.TokenAccounts
	}
	return nil
}

func (x *BlockMessage) GetInnerInstructionsMap() map[int32]*InnerInstructions {
	if x != nil {
		return x.InnerInstructionsMap
	}
	return nil
}

func (x *BlockMessage) GetAccountKeys() []string {
	if x != nil {
		return x.AccountKeys
	}
	return nil
}

func (x *BlockMessage) GetTransactions() []*RawTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *BlockMessage) GetTransactionCount() int32 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

func (x *BlockMessage) GetOriginalTransactionCount() int32 {
	if x != nil {
		return x.OriginalTransactionCount
	}
	return 0
}

func (x *BlockMessage) GetSolPrice() float64 {
	if x != nil {
		return x.SolPrice
	}
	return 0
}

func (x *BlockMessage) GetFilterStats() *FilterStats {
	if x != nil {
		return x.FilterStats
	}
	return nil
}

func (x *BlockMessage) GetProtocolGroups() map[string]*ProtocolTransactionGroup {
	if x != nil {
		return x.ProtocolGroups
	}
	return nil
}

// 协议交易分组
type ProtocolTransactionGroup struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProtocolName     string                 `protobuf:"bytes,1,opt,name=protocol_name,json=protocolName,proto3" json:"protocol_name,omitempty"`              // 协议名称 (PumpFun, PumpSwap, Raydium_CLMM, etc.)
	Transactions     []*RawTransaction      `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`                                  // 该协议的所有交易
	TransactionCount int32                  `protobuf:"varint,3,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"` // 交易数量
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProtocolTransactionGroup) Reset() {
	*x = ProtocolTransactionGroup{}
	mi := &file_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolTransactionGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolTransactionGroup) ProtoMessage() {}

func (x *ProtocolTransactionGroup) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolTransactionGroup.ProtoReflect.Descriptor instead.
func (*ProtocolTransactionGroup) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{1}
}

func (x *ProtocolTransactionGroup) GetProtocolName() string {
	if x != nil {
		return x.ProtocolName
	}
	return ""
}

func (x *ProtocolTransactionGroup) GetTransactions() []*RawTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ProtocolTransactionGroup) GetTransactionCount() int32 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

// Token 账户信息
type TokenAccount struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Owner               string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	TokenAccountAddress string                 `protobuf:"bytes,2,opt,name=token_account_address,json=tokenAccountAddress,proto3" json:"token_account_address,omitempty"`
	TokenAddress        string                 `protobuf:"bytes,3,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	TokenSymbol         string                 `protobuf:"bytes,4,opt,name=token_symbol,json=tokenSymbol,proto3" json:"token_symbol,omitempty"`
	TokenName           string                 `protobuf:"bytes,5,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`
	TokenDecimal        uint32                 `protobuf:"varint,6,opt,name=token_decimal,json=tokenDecimal,proto3" json:"token_decimal,omitempty"`
	PreValue            int64                  `protobuf:"varint,7,opt,name=pre_value,json=preValue,proto3" json:"pre_value,omitempty"`
	PostValue           int64                  `protobuf:"varint,8,opt,name=post_value,json=postValue,proto3" json:"post_value,omitempty"`
	Init                bool                   `protobuf:"varint,9,opt,name=init,proto3" json:"init,omitempty"`
	Closed              bool                   `protobuf:"varint,10,opt,name=closed,proto3" json:"closed,omitempty"`
	PreValueUiString    string                 `protobuf:"bytes,11,opt,name=pre_value_ui_string,json=preValueUiString,proto3" json:"pre_value_ui_string,omitempty"`
	PostValueUiString   string                 `protobuf:"bytes,12,opt,name=post_value_ui_string,json=postValueUiString,proto3" json:"post_value_ui_string,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TokenAccount) Reset() {
	*x = TokenAccount{}
	mi := &file_block_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenAccount) ProtoMessage() {}

func (x *TokenAccount) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenAccount.ProtoReflect.Descriptor instead.
func (*TokenAccount) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{2}
}

func (x *TokenAccount) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *TokenAccount) GetTokenAccountAddress() string {
	if x != nil {
		return x.TokenAccountAddress
	}
	return ""
}

func (x *TokenAccount) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *TokenAccount) GetTokenSymbol() string {
	if x != nil {
		return x.TokenSymbol
	}
	return ""
}

func (x *TokenAccount) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *TokenAccount) GetTokenDecimal() uint32 {
	if x != nil {
		return x.TokenDecimal
	}
	return 0
}

func (x *TokenAccount) GetPreValue() int64 {
	if x != nil {
		return x.PreValue
	}
	return 0
}

func (x *TokenAccount) GetPostValue() int64 {
	if x != nil {
		return x.PostValue
	}
	return 0
}

func (x *TokenAccount) GetInit() bool {
	if x != nil {
		return x.Init
	}
	return false
}

func (x *TokenAccount) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

func (x *TokenAccount) GetPreValueUiString() string {
	if x != nil {
		return x.PreValueUiString
	}
	return ""
}

func (x *TokenAccount) GetPostValueUiString() string {
	if x != nil {
		return x.PostValueUiString
	}
	return ""
}

// Inner Instructions
type InnerInstructions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Instructions  []*CompiledInstruction `protobuf:"bytes,2,rep,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerInstructions) Reset() {
	*x = InnerInstructions{}
	mi := &file_block_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerInstructions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerInstructions) ProtoMessage() {}

func (x *InnerInstructions) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerInstructions.ProtoReflect.Descriptor instead.
func (*InnerInstructions) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{3}
}

func (x *InnerInstructions) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *InnerInstructions) GetInstructions() []*CompiledInstruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

// 编译后的指令
type CompiledInstruction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProgramIdIndex uint32                 `protobuf:"varint,1,opt,name=program_id_index,json=programIdIndex,proto3" json:"program_id_index,omitempty"`
	Accounts       []uint32               `protobuf:"varint,2,rep,packed,name=accounts,proto3" json:"accounts,omitempty"`
	Data           []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompiledInstruction) Reset() {
	*x = CompiledInstruction{}
	mi := &file_block_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompiledInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledInstruction) ProtoMessage() {}

func (x *CompiledInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledInstruction.ProtoReflect.Descriptor instead.
func (*CompiledInstruction) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{4}
}

func (x *CompiledInstruction) GetProgramIdIndex() uint32 {
	if x != nil {
		return x.ProgramIdIndex
	}
	return 0
}

func (x *CompiledInstruction) GetAccounts() []uint32 {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *CompiledInstruction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 原始交易
type RawTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signatures    [][]byte               `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures,omitempty"`
	Message       *Message               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Meta          *TransactionMeta       `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	AccountKeys   [][]byte               `protobuf:"bytes,4,rep,name=account_keys,json=accountKeys,proto3" json:"account_keys,omitempty"` // 交易的 AccountKeys
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawTransaction) Reset() {
	*x = RawTransaction{}
	mi := &file_block_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawTransaction) ProtoMessage() {}

func (x *RawTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawTransaction.ProtoReflect.Descriptor instead.
func (*RawTransaction) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{5}
}

func (x *RawTransaction) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *RawTransaction) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *RawTransaction) GetMeta() *TransactionMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *RawTransaction) GetAccountKeys() [][]byte {
	if x != nil {
		return x.AccountKeys
	}
	return nil
}

type Message struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountKeys     [][]byte               `protobuf:"bytes,1,rep,name=account_keys,json=accountKeys,proto3" json:"account_keys,omitempty"`
	RecentBlockhash []byte                 `protobuf:"bytes,2,opt,name=recent_blockhash,json=recentBlockhash,proto3" json:"recent_blockhash,omitempty"`
	Instructions    []*CompiledInstruction `protobuf:"bytes,3,rep,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_block_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{6}
}

func (x *Message) GetAccountKeys() [][]byte {
	if x != nil {
		return x.AccountKeys
	}
	return nil
}

func (x *Message) GetRecentBlockhash() []byte {
	if x != nil {
		return x.RecentBlockhash
	}
	return nil
}

func (x *Message) GetInstructions() []*CompiledInstruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

type TransactionMeta struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Err               []byte                 `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"` // null if success
	Fee               uint64                 `protobuf:"varint,2,opt,name=fee,proto3" json:"fee,omitempty"`
	PreBalances       []int64                `protobuf:"varint,3,rep,packed,name=pre_balances,json=preBalances,proto3" json:"pre_balances,omitempty"`
	PostBalances      []int64                `protobuf:"varint,4,rep,packed,name=post_balances,json=postBalances,proto3" json:"post_balances,omitempty"`
	InnerInstructions []*InnerInstructions   `protobuf:"bytes,5,rep,name=inner_instructions,json=innerInstructions,proto3" json:"inner_instructions,omitempty"`
	PreTokenBalances  []*TokenBalance        `protobuf:"bytes,6,rep,name=pre_token_balances,json=preTokenBalances,proto3" json:"pre_token_balances,omitempty"`
	PostTokenBalances []*TokenBalance        `protobuf:"bytes,7,rep,name=post_token_balances,json=postTokenBalances,proto3" json:"post_token_balances,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransactionMeta) Reset() {
	*x = TransactionMeta{}
	mi := &file_block_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionMeta) ProtoMessage() {}

func (x *TransactionMeta) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionMeta.ProtoReflect.Descriptor instead.
func (*TransactionMeta) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionMeta) GetErr() []byte {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *TransactionMeta) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *TransactionMeta) GetPreBalances() []int64 {
	if x != nil {
		return x.PreBalances
	}
	return nil
}

func (x *TransactionMeta) GetPostBalances() []int64 {
	if x != nil {
		return x.PostBalances
	}
	return nil
}

func (x *TransactionMeta) GetInnerInstructions() []*InnerInstructions {
	if x != nil {
		return x.InnerInstructions
	}
	return nil
}

func (x *TransactionMeta) GetPreTokenBalances() []*TokenBalance {
	if x != nil {
		return x.PreTokenBalances
	}
	return nil
}

func (x *TransactionMeta) GetPostTokenBalances() []*TokenBalance {
	if x != nil {
		return x.PostTokenBalances
	}
	return nil
}

type TokenBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountIndex  uint32                 `protobuf:"varint,1,opt,name=account_index,json=accountIndex,proto3" json:"account_index,omitempty"`
	Mint          string                 `protobuf:"bytes,2,opt,name=mint,proto3" json:"mint,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	UiTokenAmount *UITokenAmount         `protobuf:"bytes,4,opt,name=ui_token_amount,json=uiTokenAmount,proto3" json:"ui_token_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenBalance) Reset() {
	*x = TokenBalance{}
	mi := &file_block_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenBalance) ProtoMessage() {}

func (x *TokenBalance) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenBalance.ProtoReflect.Descriptor instead.
func (*TokenBalance) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{8}
}

func (x *TokenBalance) GetAccountIndex() uint32 {
	if x != nil {
		return x.AccountIndex
	}
	return 0
}

func (x *TokenBalance) GetMint() string {
	if x != nil {
		return x.Mint
	}
	return ""
}

func (x *TokenBalance) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *TokenBalance) GetUiTokenAmount() *UITokenAmount {
	if x != nil {
		return x.UiTokenAmount
	}
	return nil
}

type UITokenAmount struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UiAmountString string                 `protobuf:"bytes,1,opt,name=ui_amount_string,json=uiAmountString,proto3" json:"ui_amount_string,omitempty"`
	Decimals       uint32                 `protobuf:"varint,2,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Amount         string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UITokenAmount) Reset() {
	*x = UITokenAmount{}
	mi := &file_block_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UITokenAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UITokenAmount) ProtoMessage() {}

func (x *UITokenAmount) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UITokenAmount.ProtoReflect.Descriptor instead.
func (*UITokenAmount) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{9}
}

func (x *UITokenAmount) GetUiAmountString() string {
	if x != nil {
		return x.UiAmountString
	}
	return ""
}

func (x *UITokenAmount) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *UITokenAmount) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

// 过滤统计信息
type FilterStats struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TotalTransactions    int32                  `protobuf:"varint,1,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	FilteredTransactions int32                  `protobuf:"varint,2,opt,name=filtered_transactions,json=filteredTransactions,proto3" json:"filtered_transactions,omitempty"`
	FilterRatio          float64                `protobuf:"fixed64,3,opt,name=filter_ratio,json=filterRatio,proto3" json:"filter_ratio,omitempty"`
	ProtocolCounts       map[string]int32       `protobuf:"bytes,4,rep,name=protocol_counts,json=protocolCounts,proto3" json:"protocol_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 各协议的交易数
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FilterStats) Reset() {
	*x = FilterStats{}
	mi := &file_block_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterStats) ProtoMessage() {}

func (x *FilterStats) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterStats.ProtoReflect.Descriptor instead.
func (*FilterStats) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{10}
}

func (x *FilterStats) GetTotalTransactions() int32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *FilterStats) GetFilteredTransactions() int32 {
	if x != nil {
		return x.FilteredTransactions
	}
	return 0
}

func (x *FilterStats) GetFilterRatio() float64 {
	if x != nil {
		return x.FilterRatio
	}
	return 0
}

func (x *FilterStats) GetProtocolCounts() map[string]int32 {
	if x != nil {
		return x.ProtocolCounts
	}
	return nil
}

var File_block_proto protoreflect.FileDescriptor

const file_block_proto_rawDesc = "" +
	"\n" +
	"\vblock.proto\x12\x0fdex.consumer.mq\"\x92\b\n" +
	"\fBlockMessage\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12\x1d\n" +
	"\n" +
	"block_time\x18\x02 \x01(\x03R\tblockTime\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x03 \x01(\tR\tblockHash\x12\x1f\n" +
	"\vparent_slot\x18\x04 \x01(\x04R\n" +
	"parentSlot\x12W\n" +
	"\x0etoken_accounts\x18\x05 \x03(\v20.dex.consumer.mq.BlockMessage.TokenAccountsEntryR\rtokenAccounts\x12m\n" +
	"\x16inner_instructions_map\x18\x06 \x03(\v27.dex.consumer.mq.BlockMessage.InnerInstructionsMapEntryR\x14innerInstructionsMap\x12!\n" +
	"\faccount_keys\x18\a \x03(\tR\vaccountKeys\x12C\n" +
	"\ftransactions\x18\b \x03(\v2\x1f.dex.consumer.mq.RawTransactionR\ftransactions\x12+\n" +
	"\x11transaction_count\x18\t \x01(\x05R\x10transactionCount\x12<\n" +
	"\x1aoriginal_transaction_count\x18\n" +
	" \x01(\x05R\x18originalTransactionCount\x12\x1b\n" +
	"\tsol_price\x18\v \x01(\x01R\bsolPrice\x12?\n" +
	"\ffilter_stats\x18\f \x01(\v2\x1c.dex.consumer.mq.FilterStatsR\vfilterStats\x12Z\n" +
	"\x0fprotocol_groups\x18\r \x03(\v21.dex.consumer.mq.BlockMessage.ProtocolGroupsEntryR\x0eprotocolGroups\x1a_\n" +
	"\x12TokenAccountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.dex.consumer.mq.TokenAccountR\x05value:\x028\x01\x1ak\n" +
	"\x19InnerInstructionsMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".dex.consumer.mq.InnerInstructionsR\x05value:\x028\x01\x1al\n" +
	"\x13ProtocolGroupsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12?\n" +
	"\x05value\x18\x02 \x01(\v2).dex.consumer.mq.ProtocolTransactionGroupR\x05value:\x028\x01\"\xb1\x01\n" +
	"\x18ProtocolTransactionGroup\x12#\n" +
	"\rprotocol_name\x18\x01 \x01(\tR\fprotocolName\x12C\n" +
	"\ftransactions\x18\x02 \x03(\v2\x1f.dex.consumer.mq.RawTransactionR\ftransactions\x12+\n" +
	"\x11transaction_count\x18\x03 \x01(\x05R\x10transactionCount\"\xac\x03\n" +
	"\fTokenAccount\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x122\n" +
	"\x15token_account_address\x18\x02 \x01(\tR\x13tokenAccountAddress\x12#\n" +
	"\rtoken_address\x18\x03 \x01(\tR\ftokenAddress\x12!\n" +
	"\ftoken_symbol\x18\x04 \x01(\tR\vtokenSymbol\x12\x1d\n" +
	"\n" +
	"token_name\x18\x05 \x01(\tR\ttokenName\x12#\n" +
	"\rtoken_decimal\x18\x06 \x01(\rR\ftokenDecimal\x12\x1b\n" +
	"\tpre_value\x18\a \x01(\x03R\bpreValue\x12\x1d\n" +
	"\n" +
	"post_value\x18\b \x01(\x03R\tpostValue\x12\x12\n" +
	"\x04init\x18\t \x01(\bR\x04init\x12\x16\n" +
	"\x06closed\x18\n" +
	" \x01(\bR\x06closed\x12-\n" +
	"\x13pre_value_ui_string\x18\v \x01(\tR\x10preValueUiString\x12/\n" +
	"\x14post_value_ui_string\x18\f \x01(\tR\x11postValueUiString\"s\n" +
	"\x11InnerInstructions\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12H\n" +
	"\finstructions\x18\x02 \x03(\v2$.dex.consumer.mq.CompiledInstructionR\finstructions\"o\n" +
	"\x13CompiledInstruction\x12(\n" +
	"\x10program_id_index\x18\x01 \x01(\rR\x0eprogramIdIndex\x12\x1a\n" +
	"\baccounts\x18\x02 \x03(\rR\baccounts\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xbd\x01\n" +
	"\x0eRawTransaction\x12\x1e\n" +
	"\n" +
	"signatures\x18\x01 \x03(\fR\n" +
	"signatures\x122\n" +
	"\amessage\x18\x02 \x01(\v2\x18.dex.consumer.mq.MessageR\amessage\x124\n" +
	"\x04meta\x18\x03 \x01(\v2 .dex.consumer.mq.TransactionMetaR\x04meta\x12!\n" +
	"\faccount_keys\x18\x04 \x03(\fR\vaccountKeys\"\xa1\x01\n" +
	"\aMessage\x12!\n" +
	"\faccount_keys\x18\x01 \x03(\fR\vaccountKeys\x12)\n" +
	"\x10recent_blockhash\x18\x02 \x01(\fR\x0frecentBlockhash\x12H\n" +
	"\finstructions\x18\x03 \x03(\v2$.dex.consumer.mq.CompiledInstructionR\finstructions\"\xec\x02\n" +
	"\x0fTransactionMeta\x12\x10\n" +
	"\x03err\x18\x01 \x01(\fR\x03err\x12\x10\n" +
	"\x03fee\x18\x02 \x01(\x04R\x03fee\x12!\n" +
	"\fpre_balances\x18\x03 \x03(\x03R\vpreBalances\x12#\n" +
	"\rpost_balances\x18\x04 \x03(\x03R\fpostBalances\x12Q\n" +
	"\x12inner_instructions\x18\x05 \x03(\v2\".dex.consumer.mq.InnerInstructionsR\x11innerInstructions\x12K\n" +
	"\x12pre_token_balances\x18\x06 \x03(\v2\x1d.dex.consumer.mq.TokenBalanceR\x10preTokenBalances\x12M\n" +
	"\x13post_token_balances\x18\a \x03(\v2\x1d.dex.consumer.mq.TokenBalanceR\x11postTokenBalances\"\xa5\x01\n" +
	"\fTokenBalance\x12#\n" +
	"\raccount_index\x18\x01 \x01(\rR\faccountIndex\x12\x12\n" +
	"\x04mint\x18\x02 \x01(\tR\x04mint\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12F\n" +
	"\x0fui_token_amount\x18\x04 \x01(\v2\x1e.dex.consumer.mq.UITokenAmountR\ruiTokenAmount\"m\n" +
	"\rUITokenAmount\x12(\n" +
	"\x10ui_amount_string\x18\x01 \x01(\tR\x0euiAmountString\x12\x1a\n" +
	"\bdecimals\x18\x02 \x01(\rR\bdecimals\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"\xb2\x02\n" +
	"\vFilterStats\x12-\n" +
	"\x12total_transactions\x18\x01 \x01(\x05R\x11totalTransactions\x123\n" +
	"\x15filtered_transactions\x18\x02 \x01(\x05R\x14filteredTransactions\x12!\n" +
	"\ffilter_ratio\x18\x03 \x01(\x01R\vfilterRatio\x12Y\n" +
	"\x0fprotocol_counts\x18\x04 \x03(\v20.dex.consumer.mq.FilterStats.ProtocolCountsEntryR\x0eprotocolCounts\x1aA\n" +
	"\x13ProtocolCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B,Z*richcode.cc/dex/consumer/internal/mq/protob\x06proto3"

var (
	file_block_proto_rawDescOnce sync.Once
	file_block_proto_rawDescData []byte
)

func file_block_proto_rawDescGZIP() []byte {
	file_block_proto_rawDescOnce.Do(func() {
		file_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)))
	})
	return file_block_proto_rawDescData
}

var file_block_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_block_proto_goTypes = []any{
	(*BlockMessage)(nil),             // 0: dex.consumer.mq.BlockMessage
	(*ProtocolTransactionGroup)(nil), // 1: dex.consumer.mq.ProtocolTransactionGroup
	(*TokenAccount)(nil),             // 2: dex.consumer.mq.TokenAccount
	(*InnerInstructions)(nil),        // 3: dex.consumer.mq.InnerInstructions
	(*CompiledInstruction)(nil),      // 4: dex.consumer.mq.CompiledInstruction
	(*RawTransaction)(nil),           // 5: dex.consumer.mq.RawTransaction
	(*Message)(nil),                  // 6: dex.consumer.mq.Message
	(*TransactionMeta)(nil),          // 7: dex.consumer.mq.TransactionMeta
	(*TokenBalance)(nil),             // 8: dex.consumer.mq.TokenBalance
	(*UITokenAmount)(nil),            // 9: dex.consumer.mq.UITokenAmount
	(*FilterStats)(nil),              // 10: dex.consumer.mq.FilterStats
	nil,                              // 11: dex.consumer.mq.BlockMessage.TokenAccountsEntry
	nil,                              // 12: dex.consumer.mq.BlockMessage.InnerInstructionsMapEntry
	nil,                              // 13: dex.consumer.mq.BlockMessage.ProtocolGroupsEntry
	nil,                              // 14: dex.consumer.mq.FilterStats.ProtocolCountsEntry
}
var file_block_proto_depIdxs = []int32{
	11, // 0: dex.consumer.mq.BlockMessage.token_accounts:type_name -> dex.consumer.mq.BlockMessage.TokenAccountsEntry
	12, // 1: dex.consumer.mq.BlockMessage.inner_instructions_map:type_name -> dex.consumer.mq.BlockMessage.InnerInstructionsMapEntry
	5,  // 2: dex.consumer.mq.BlockMessage.transactions:type_name -> dex.consumer.mq.RawTransaction
	10, // 3: dex.consumer.mq.BlockMessage.filter_stats:type_name -> dex.consumer.mq.FilterStats
	13, // 4: dex.consumer.mq.BlockMessage.protocol_groups:type_name -> dex.consumer.mq.BlockMessage.ProtocolGroupsEntry
	5,  // 5: dex.consumer.mq.ProtocolTransactionGroup.transactions:type_name -> dex.consumer.mq.RawTransaction
	4,  // 6: dex.consumer.mq.InnerInstructions.instructions:type_name -> dex.consumer.mq.CompiledInstruction
	6,  // 7: dex.consumer.mq.RawTransaction.message:type_name -> dex.consumer.mq.Message
	7,  // 8: dex.consumer.mq.RawTransaction.meta:type_name -> dex.consumer.mq.TransactionMeta
	4,  // 9: dex.consumer.mq.Message.instructions:type_name -> dex.consumer.mq.CompiledInstruction
	3,  // 10: dex.consumer.mq.TransactionMeta.inner_instructions:type_name -> dex.consumer.mq.InnerInstructions
	8,  // 11: dex.consumer.mq.TransactionMeta.pre_token_balances:type_name -> dex.consumer.mq.TokenBalance
	8,  // 12: dex.consumer.mq.TransactionMeta.post_token_balances:type_name -> dex.consumer.mq.TokenBalance
	9,  // 13: dex.consumer.mq.TokenBalance.ui_token_amount:type_name -> dex.consumer.mq.UITokenAmount
	14, // 14: dex.consumer.mq.FilterStats.protocol_counts:type_name -> dex.consumer.mq.FilterStats.ProtocolCountsEntry
	2,  // 15: dex.consumer.mq.BlockMessage.TokenAccountsEntry.value:type_name -> dex.consumer.mq.TokenAccount
	3,  // 16: dex.consumer.mq.BlockMessage.InnerInstructionsMapEntry.value:type_name -> dex.consumer.mq.InnerInstructions
	1,  // 17: dex.consumer.mq.BlockMessage.ProtocolGroupsEntry.value:type_name -> dex.consumer.mq.ProtocolTransactionGroup
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_block_proto_init() }
func file_block_proto_init() {
	if File_block_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_proto_goTypes,
		DependencyIndexes: file_block_proto_depIdxs,
		MessageInfos:      file_block_proto_msgTypes,
	}.Build()
	File_block_proto = out.File
	file_block_proto_goTypes = nil
	file_block_proto_depIdxs = nil
}
